"""
@module grpcbridge.java_bridge

Project assembly for the Polari Hardware Bridge (grpc-j1): given a
HardwareBridgeDefinition (the knob) whose exposed classes ALL hold
CURRENT gRPC contracts (grpc-1 — which in turn requires stabilized
schemas), emit a complete buildable Maven project as
{relative_path: text} and a tar.gz. Stdlib-only string templating —
the same idiom as proto_gen, now targeting Java.

The tarball is NOT stored; it is rebuilt deterministically at
download time from the same contract rows. The bridge row keeps the
manifest + the contract hashes it was generated against, so drift
is visible (a stale contract shuts the gate with evidence).

@consumers
  - grpcbridge.java_bridge_api
  - grpcbridge.selftest_javabridge
"""

import hashlib
import io
import json
import tarfile
from datetime import datetime, timezone

from grpcbridge import java_bridge_codegen as jcg
from grpcbridge import java_bridge_templates as jt
from grpcbridge.proto_gen import (
    SHARED_MESSAGES, get_exposure, get_versions, render_message,
    render_service, _rows, _save_row,
)

JAVA_DIR = 'src/main/java/org/polari/bridge'


def _now():
    return datetime.now(timezone.utc).isoformat()


def render(template, **tokens):
    """__TOKEN__ replacement — no brace escaping in Java templates."""
    out = template
    for key, value in tokens.items():
        out = out.replace(f'__{key}__', str(value))
    return out


def get_bridge(manager, bridge_name):
    for row in _rows(manager, 'HardwareBridgeDefinition').values():
        if getattr(row, 'bridge_name', '') == bridge_name:
            return row
    return None


def bridge_classes(bridge):
    try:
        classes = json.loads(
            getattr(bridge, 'exposed_classes_json', '[]') or '[]')
    except Exception:
        return []
    return [c for c in classes if isinstance(c, str) and c]


def class_readiness(manager, class_name):
    """Is this class's contract ready to embed? Refusals name the
    exact knob that opens the gate."""
    exposure = get_exposure(manager, class_name)
    if exposure is None:
        return {'class': class_name, 'ready': False,
                'why': 'no gRPC exposure',
                'knob': f'/api/grpc/exposures/{class_name}',
                'how': 'POST {"action": "enable"} (requires a '
                       'stabilized schema)'}
    status = getattr(exposure, 'contract_status', 'never-generated')
    if status != 'current':
        return {'class': class_name, 'ready': False,
                'why': f'contract is {status}',
                'knob': f'/api/grpc/exposures/{class_name}',
                'how': 'POST {"action": "regenerate"}',
                'evidence': getattr(exposure, 'notes', '')}
    if not getattr(exposure, 'enabled', False):
        return {'class': class_name, 'ready': False,
                'why': 'exposure is disabled',
                'knob': f'/api/grpc/exposures/{class_name}',
                'how': 'POST {"action": "enable"}'}
    return {'class': class_name, 'ready': True,
            'version': getattr(exposure, 'proto_version', 0),
            'contractHash': getattr(exposure, 'contract_hash', '')}


def _field_map_for(manager, class_name, version):
    for row in get_versions(manager, class_name):
        if int(getattr(row, 'version', 0)) == int(version):
            try:
                return json.loads(
                    getattr(row, 'field_map_json', '{}') or '{}')
            except Exception:
                return None
    return None


def bundle_proto(classes_with_maps):
    """ONE polari_bridge.proto: shared messages once + every class
    message + its sync service (protoc-clean for the Maven build)."""
    parts = [
        '// Generated by Polari grpcbridge (grpc-j1) — the bundled',
        '// contract of every class this bridge carries.',
        'syntax = "proto3";',
        '',
        'package polari.sync;',
        '',
        'option java_package = "org.polari.sync";',
        'option java_multiple_files = true;',
        '',
        SHARED_MESSAGES,
    ]
    for class_name, field_map in classes_with_maps:
        parts += ['', render_message(class_name, field_map),
                  '', render_service(class_name)]
    parts.append('')
    return '\n'.join(parts)


def generate_project(manager, bridge):
    """The whole app as {path: text}. Refuses (naming the knob) when
    any exposed class's contract gate is shut."""
    bridge_name = getattr(bridge, 'bridge_name', '') or 'bridge'
    classes = bridge_classes(bridge)
    if not classes:
        return {'ok': False,
                'error': 'bridge has no exposed classes — set '
                         'exposed_classes_json to an ordered list of '
                         'class names (order defines msg_type)'}
    readiness = [class_readiness(manager, c) for c in classes]
    blocked = [r for r in readiness if not r['ready']]
    if blocked:
        return {'ok': False,
                'error': 'contract gate shut for: '
                         + ', '.join(b['class'] for b in blocked),
                'blocked': blocked}

    classes_with_maps = []
    for r in readiness:
        field_map = _field_map_for(manager, r['class'], r['version'])
        if not field_map or not field_map.get('fields'):
            return {'ok': False,
                    'error': f'no field map stored for '
                             f'{r["class"]} v{r["version"]} — '
                             'regenerate the contract'}
        classes_with_maps.append((r['class'], field_map))

    files = {}
    files['pom.xml'] = render(jt.POM_XML, BRIDGE_NAME=bridge_name)
    files['src/main/proto/polari_bridge.proto'] = \
        bundle_proto(classes_with_maps)
    files[f'{JAVA_DIR}/PolariPacket.java'] = jt.POLARI_PACKET_JAVA
    files[f'{JAVA_DIR}/DevicePort.java'] = jt.DEVICE_PORT_JAVA
    files[f'{JAVA_DIR}/SimulatedDevice.java'] = \
        jt.SIMULATED_DEVICE_JAVA
    files[f'{JAVA_DIR}/SerialCdcPort.java'] = jt.SERIAL_PORT_JAVA
    files[f'{JAVA_DIR}/BridgeConfig.java'] = jt.BRIDGE_CONFIG_JAVA
    files[f'{JAVA_DIR}/BridgeMain.java'] = jt.BRIDGE_MAIN_JAVA
    files[f'{JAVA_DIR}/LoopbackSelfTest.java'] = \
        jt.LOOPBACK_SELFTEST_JAVA
    for idx, (class_name, field_map) in enumerate(classes_with_maps):
        msg_type = idx + 1
        exposure = get_exposure(manager, class_name)
        files[f'{JAVA_DIR}/codec/{class_name}Record.java'] = \
            jcg.render_record(
                class_name, field_map,
                getattr(exposure, 'proto_version', 0),
                getattr(exposure, 'contract_hash', ''))
        files[f'{JAVA_DIR}/codec/{class_name}Codec.java'] = \
            jcg.render_codec(class_name, field_map, msg_type)
    files[f'{JAVA_DIR}/CodecRegistry.java'] = \
        jcg.render_registry([c for c, _ in classes_with_maps])
    files[f'{JAVA_DIR}/grpc/GrpcForwarder.java'] = \
        jcg.render_forwarder(classes_with_maps)

    files['bridge.properties'] = '\n'.join([
        '# Polari Hardware Bridge knobs (generated defaults).',
        f'source={getattr(bridge, "source", "simulated")}',
        f'serial.device='
        f'{getattr(bridge, "serial_device", "/dev/ttyACM0")}',
        f'serial.baud={getattr(bridge, "baud", 115200)}',
        f'sim.rate_hz={getattr(bridge, "sim_rate_hz", 10)}',
        'max_frames=0',
        f'device.id={getattr(bridge, "device_id", 1)}',
        f'grpc.enabled='
        f'{str(bool(getattr(bridge, "grpc_enabled", False))).lower()}',
        f'grpc.target='
        f'{getattr(bridge, "grpc_target", "localhost:3002")}',
        '',
    ])
    files[f'systemd/polari-hw-bridge-{bridge_name}.service'] = \
        render(jt.SYSTEMD_UNIT, BRIDGE_NAME=bridge_name)
    files['install-ubuntu.sh'] = render(jt.INSTALL_SH,
                                        BRIDGE_NAME=bridge_name)
    class_table = '\n'.join(
        f'- msg_type {i + 1}: `{c}` (contract v{r["version"]}, '
        f'hash {r["contractHash"]})'
        for i, (c, r) in enumerate(
            zip([c for c, _ in classes_with_maps], readiness)))
    files['README.md'] = render(jt.README_MD,
                                BRIDGE_NAME=bridge_name,
                                CLASS_TABLE=class_table)

    manifest = [{'path': p,
                 'bytes': len(t.encode('utf-8')),
                 'sha256': hashlib.sha256(
                     t.encode('utf-8')).hexdigest()[:12]}
                for p, t in sorted(files.items())]
    return {'ok': True, 'bridge': bridge_name, 'files': files,
            'manifest': manifest,
            'classes': [c for c, _ in classes_with_maps],
            'contractHashes': {r['class']: r['contractHash']
                               for r in readiness}}


def stamp_generation(manager, bridge, report):
    """Record what was generated on the knob row (the manifest, not
    the artifact — downloads rebuild deterministically)."""
    bridge.last_generated_at = _now()
    bridge.manifest_json = json.dumps(report['manifest'])
    bridge.contract_hashes_json = json.dumps(report['contractHashes'])
    _save_row(manager, bridge)


def tarball(report):
    """tar.gz bytes of a generate_project report (deterministic:
    fixed mtimes/owners, sorted paths)."""
    root = f'polari-hw-bridge-{report["bridge"]}'
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode='w:gz') as tar:
        for path in sorted(report['files']):
            data = report['files'][path].encode('utf-8')
            info = tarfile.TarInfo(name=f'{root}/{path}')
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o755 if path.endswith('.sh') else 0o644
            tar.addfile(info, io.BytesIO(data))
    return buf.getvalue()
