/* Generated by Polari grpcbridge.c_twin (grpc-j3) — do not edit.
 * class: SimRigState   contract v2   hash 2bcc9d1a2774ef33
 * Byte-exact twin of the Java SimRigStateCodec / PolariPacket:
 * regenerate when the contract regenerates. */
#ifndef SIMRIGSTATE_PACKETS_H
#define SIMRIGSTATE_PACKETS_H

#ifndef POLARI_RX_PAYLOAD_MAX
#define POLARI_RX_PAYLOAD_MAX 157u
#endif

#ifndef POLARI_PACKET_COMMON_H
#define POLARI_PACKET_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#define POLARI_MAGIC      0x504CU  /* wire bytes: 0x4C 0x50 */
#define POLARI_VERSION    1U
#define POLARI_HEADER_LEN 12U

/* CRC32 (IEEE reflected, poly 0xEDB88320) — identical to
 * java.util.zip.CRC32 and Python zlib.crc32. Bitwise (no table):
 * cycles are cheap at telemetry rates, flash is not. */
static uint32_t polari_crc32(const uint8_t *d, size_t n)
{
    uint32_t c = 0xFFFFFFFFu;
    size_t i;
    int k;
    for (i = 0; i < n; i++) {
        c ^= d[i];
        for (k = 0; k < 8; k++)
            c = (c >> 1) ^ (0xEDB88320u
                            & (uint32_t)(-(int32_t)(c & 1u)));
    }
    return ~c;
}

static void polari_put_u16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
}

static void polari_put_u32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v;         p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static uint16_t polari_get_u16(const uint8_t *p)
{
    return (uint16_t)(p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t polari_get_u32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

/* Frame a payload into `out` (must hold POLARI_HEADER_LEN+len+4).
 * Returns the wire length. */
static size_t polari_packet_encode(uint8_t *out, uint8_t msg_type,
                                   uint16_t device_id, uint32_t seq,
                                   const uint8_t *payload,
                                   uint16_t len)
{
    polari_put_u16(out, POLARI_MAGIC);
    out[2] = POLARI_VERSION;
    out[3] = msg_type;
    polari_put_u16(out + 4, device_id);
    polari_put_u32(out + 6, seq);
    polari_put_u16(out + 10, len);
    memcpy(out + POLARI_HEADER_LEN, payload, len);
    polari_put_u32(out + POLARI_HEADER_LEN + len,
                   polari_crc32(out, POLARI_HEADER_LEN + len));
    return POLARI_HEADER_LEN + (size_t)len + 4u;
}

/* Incremental receive parser: feed one byte at a time; returns 1
 * when rx holds a complete CRC-valid packet (msg_type/payload/len
 * fields populated), 0 otherwise. Resync-safe: bad magic, oversize
 * or bad CRC restart the hunt. */
typedef struct {
    uint8_t buf[POLARI_HEADER_LEN + POLARI_RX_PAYLOAD_MAX + 4u];
    size_t have;
    uint16_t need_payload;
    uint8_t msg_type;
    uint16_t device_id;
    uint32_t sequence;
    const uint8_t *payload;
    uint16_t payload_len;
} polari_rx_t;

static int polari_rx_feed(polari_rx_t *rx, uint8_t b)
{
    if (rx->have == 0u) {
        if (b != (uint8_t)(POLARI_MAGIC & 0xFFu)) return 0;
    } else if (rx->have == 1u) {
        if (b != (uint8_t)(POLARI_MAGIC >> 8)) { rx->have = 0u; return 0; }
    }
    rx->buf[rx->have++] = b;
    if (rx->have == POLARI_HEADER_LEN) {
        if (rx->buf[2] != POLARI_VERSION) { rx->have = 0u; return 0; }
        rx->need_payload = polari_get_u16(rx->buf + 10);
        if (rx->need_payload > POLARI_RX_PAYLOAD_MAX) {
            rx->have = 0u;
            return 0;
        }
    }
    if (rx->have >= POLARI_HEADER_LEN
        && rx->have == POLARI_HEADER_LEN + (size_t)rx->need_payload + 4u) {
        size_t body = POLARI_HEADER_LEN + (size_t)rx->need_payload;
        uint32_t crc = polari_get_u32(rx->buf + body);
        rx->have = 0u;
        if (crc != polari_crc32(rx->buf, body)) return 0;
        rx->msg_type = rx->buf[3];
        rx->device_id = polari_get_u16(rx->buf + 4);
        rx->sequence = polari_get_u32(rx->buf + 6);
        rx->payload = rx->buf + POLARI_HEADER_LEN;
        rx->payload_len = rx->need_payload;
        return 1;
    }
    return 0;
}

#endif /* POLARI_PACKET_COMMON_H */

#define SIMRIGSTATE_MSG_TYPE 1u
#define SIMRIGSTATE_PAYLOAD_MAX 157u

typedef struct {
    char name[64];
    int64_t pwm_duty;
    char status[64];
    double temp_c;
    int64_t uptime_ms;
    uint8_t led_on;
} SimRigState_t;

/* struct -> payload bytes (tag order). Returns payload length. */
static uint16_t SimRigState_encode(const SimRigState_t *s,
                                    uint8_t *p)
{
    uint8_t *start = p;
    uint16_t n;
    (void)n;
    n = (uint16_t)strlen(s->name);
    polari_put_u16(p, n); p += 2;
    memcpy(p, s->name, n); p += n;
    polari_put_u32(p, (uint32_t)s->pwm_duty);
    polari_put_u32(p + 4, (uint32_t)((uint64_t)s->pwm_duty >> 32)); p += 8;
    n = (uint16_t)strlen(s->status);
    polari_put_u16(p, n); p += 2;
    memcpy(p, s->status, n); p += n;
    memcpy(p, &s->temp_c, 8); p += 8;  /* LE host assumed (Cortex-M / x86) */
    polari_put_u32(p, (uint32_t)s->uptime_ms);
    polari_put_u32(p + 4, (uint32_t)((uint64_t)s->uptime_ms >> 32)); p += 8;
    *p++ = s->led_on ? 1u : 0u;
    return (uint16_t)(p - start);
}

/* payload bytes -> struct. Returns 0, or -1 on truncated input. */
static int SimRigState_decode(const uint8_t *p, uint16_t len,
                               SimRigState_t *s)
{
    const uint8_t *end = p + len;
    uint16_t n, cp;
    (void)n; (void)cp;
    if (end - p < 2) return -1;
    n = polari_get_u16(p); p += 2;
    if (end - p < n) return -1;
    cp = n < 63u ? n : 63u;  /* bounded: SAMD21-tier honest truncation */
    memcpy(s->name, p, cp); s->name[cp] = 0; p += n;
    if (end - p < 8) return -1;
    s->pwm_duty = (int64_t)((uint64_t)polari_get_u32(p)
        | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    if (end - p < 2) return -1;
    n = polari_get_u16(p); p += 2;
    if (end - p < n) return -1;
    cp = n < 63u ? n : 63u;  /* bounded: SAMD21-tier honest truncation */
    memcpy(s->status, p, cp); s->status[cp] = 0; p += n;
    if (end - p < 8) return -1;
    memcpy(&s->temp_c, p, 8); p += 8;
    if (end - p < 8) return -1;
    s->uptime_ms = (int64_t)((uint64_t)polari_get_u32(p)
        | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    if (end - p < 1) return -1;
    s->led_on = (*p++ != 0u);
    return 0;
}

#endif /* SIMRIGSTATE_PACKETS_H */
