"""
@module cmod.custom.code_interface

ucd-iso-0 (His ruling 2026-10-10, AI-Notes/plans/UNO_CORE_DEMO_PLAN.md "the C-atom's CODE INTERFACE and
C-ISOTOPES"). His words: "in the CFunctionAtom details page, we will want to be able to see a code-interface that
shows it as though it is actual c-code, with the variables that come from board and pin specifications and other
data-sheets laid out in the code clearly with comment that should autogenerate saying which data-sheet they should
come from."

THE CODE INTERFACE of one atom (`render(atom_name, binding=None, manager=None)`) is its function's own C text,
VERBATIM from the project file (`line` to the matching closing brace — never re-indented, never re-authored), plus
one IDENTIFIER per datasheet-sourced thing the function touches:

  register    a register the atom's own manifest resources name (cmod.custom.analyse.resources, kind='register')
              -> soc (the ATmega328P datasheet, board.custom.register_fields_atmega328p) — SoC-fixed, never
              substituted (its value does not depend on which binding is in use)
  pin-macro   a declared board_config.h pin macro (an atom's own uses() resource, kind='declared') OR, for an
              '_init' atom with no uses() of its own (hal_led_init: its body touches only a GPIO-port register,
              LED_DDR/LED_BIT — themselves macros of LED_PIN, never the literal name), the SAME convention
              `cmod.custom.targets._init_counterpart_match` already established at the graph level: its runtime
              counterpart (hal_led, uses(LED_PIN)) names the macro, read here via the counterpart's own resolved
              board pin (a seeded graph's TargetDefinition row, pure, no binding needed) -> board (the UNO pinout
              document) + the soc pin's own pinout fact
  knob        a build-time setting substituted away by the PREPROCESSOR before the atom parser ever sees the body
              (UBRR0_VALUE, USART_U2X, F_CPU — never resources(), which only sees what survives preprocessing), found
              by scanning the function's own VERBATIM text for this small, named vocabulary (`_KNOB_FACTS`) ->
              programming (boards.txt — the actual baud/clock target these knobs are computed to hit)
  global      a file-scope global the atom reads/writes -> no datasheet (his design: "a global/library resource
  library     carries no datasheet" — kind/datasheet/datasheet_kind/fact all '', `why` says so)

`datasheet_kind`/`datasheet`/`fact` are STRUCTURAL — resolved from the project's own committed facts (never a
binding): a register's datasheet never depends on which board a solution targets (this slice: only the UNO's
atmega328p is materialized, UNO_CORE_DEMO_PLAN.md ucd-0b2b's own Phase-1 posture); a pin-macro's/knob's KIND is
likewise known without a binding (board_config.h's own literal default + the hardware-fixed BUTTON_PIN/SENSE_PIN
table already settle which pin they name). Only `value` depends on a binding (`binding=<solution>[@<board>]`,
resolved through `cmod.custom.binding` + `cmod.custom.claims.pin_claims` exactly as the hardware-chain scope door
already does) — without one, every identifier's `value` is '' (never guessed at a specific resolved number with no
binding in hand, even when the project's own board_config.h default WOULD settle one).

A literal occurrence of an identifier's own name inside the function's text gets ONE autogenerated comment on its
first line (`/* <- <kind>: <slug> — <fact> */`); when the name is never spelled out literally (macro indirection —
LED_PIN/BUTTON_PIN/SENSE_PIN are never written inside hal_led_init/hal_button_init/hal_sense_init's own bodies, only
their macro-expanded aliases are), the comment is anchored at the function's own FIRST line instead — a named,
honest fallback (never a guessed textual site), so EVERY identifier still gets exactly one comment. `rendered` is
the function's text with every comment inserted; `lines` carries the same per-line `comment` (joined with '; ' when
more than one identifier anchors to the same line) without the insertion (the page's own `code` column format, iso-1,
renders from this).

CIsotope rows (`isotopes_for_binding`) are the SAME render(), one per atom that has >= 1 datasheet-bound identifier,
with the binding's own PinClaims substituted into the text wherever the identifier's literal name IS spelled out
(a pin-macro/knob only — a register is never substituted, see above); `derive_isotope` is pure, called by the
firmware API's materialize idiom and by `GET /api/cmod/atoms/{atom}/isotopes`.
"""
import hashlib
import json
import os
import re

from cmod.custom import projects as P

#: the runtime ladder THIS slice's minimum_level reads from — hwnocode.custom.runtimes.RUNTIME_ROWS names WHERE a
#: node's code executes (python-backend / typescript-browser / c-device / c-twin / java-bridge / javafx-native,
#: demo-4b's own vocabulary) and carries no RTOS-capability ordering at all (board vs twin is the SAME runtime,
#: `runtime_for_kind`'s own docstring: "does not split the RUNTIME"). His ruling here is a DIFFERENT axis — which
#: OS (or none) a c-device atom needs AT MINIMUM ("some forms of multithreading and handling only being available
#: at FreeRTOS or ZephyrRTOS levels") — so `LEVEL_ORDER` is defined HERE, citing hwnocode.custom.runtimes as the
#: place a c-device atom's own RUNTIME lives (unchanged, never replaced): bare-c (plain polled/ISR C, no OS) <
#: freertos < esp-idf (FreeRTOS + Espressif's own services) < zephyr (a different kernel/driver model entirely).
LEVEL_ORDER = ('bare-c', 'freertos', 'esp-idf', 'zephyr')


class CodeInterfaceRefused(ValueError):
    """No such atom/binding, or the function's closing brace could not be found — never a guess."""


# ------------------------------------------------------------------ finding one atom in a committed manifest (pure)

def _manifest_candidates():
    """[(project, manifest_dict, atom_dict), ...] every atom of every committed TEMPLATE project's manifest — pure,
    no engine, no manager (the committed polari-firmware.json is the derived truth; a live CFunctionAtom row's own
    resources_summary/registers/peripherals are already flattened CSV strings — this needs the full structured
    `resources`/`ports`/`annotation` the manifest alone carries, cmod.custom.rows.project_rows)."""
    out = []
    for name in sorted(P.TEMPLATES):
        spec = P.resolve(name)
        path = P.manifest_path(spec)
        if os.path.isfile(path):
            m = json.load(open(path))
            for a in m.get('atoms', []):
                out.append((name, m, a))
    return out


def find_atom(atom_name):
    """(project, manifest, atom) for `atom_name` — '<project>:<module>.<function>' (the manifest's own atom name,
    prefixed), the bare manifest name, or the bare function/ISR name when it names exactly one atom across every
    project (the same ambiguity posture as cmod_api.CModAPI._find, over committed manifests)."""
    cands = _manifest_candidates()
    exact = [(p, m, a) for p, m, a in cands if ('%s:%s' % (p, a['name'])) == atom_name or a['name'] == atom_name]
    if exact:
        return exact[0]
    hits = [(p, m, a) for p, m, a in cands if a['function'] == atom_name or (a.get('isr_vector') or None) == atom_name]
    if len(hits) == 1:
        return hits[0]
    if not hits:
        raise CodeInterfaceRefused('no atom named %r (GET /api/cmod/atoms lists them)' % atom_name)
    raise CodeInterfaceRefused('%r names several atoms: %s — use the full name' % (
        atom_name, ', '.join('%s:%s' % (p, a['name']) for p, _m, a in hits)))


# ------------------------------------------------------------------ the verbatim source slice (line -> closing brace)

def _function_span(root, module, start_line):
    """(path, raw_lines[start_line..end_line], start_line, end_line) — `raw_lines` is VERBATIM text (never
    re-indented); the closing brace is found over a COMMENT-STRIPPED copy (cmod.custom.annotation._strip_comments,
    newlines preserved so line numbers hold) so a brace printed inside a comment is never miscounted."""
    from cmod.custom.annotation import _strip_comments
    path = os.path.join(root, module)
    if not os.path.isfile(path):
        raise CodeInterfaceRefused('%s: no such file under %s' % (module, root))
    text = open(path, encoding='utf-8').read()
    lines = text.split('\n')
    stripped_lines = _strip_comments(text).split('\n')
    i = start_line - 1
    while i < len(stripped_lines) and '{' not in stripped_lines[i]:
        i += 1
    depth, end_i = 0, None
    for j in range(i, len(stripped_lines)):
        depth += stripped_lines[j].count('{') - stripped_lines[j].count('}')
        if depth == 0:
            end_i = j
            break
    if end_i is None:
        raise CodeInterfaceRefused('%s:%d: the function\'s closing brace was not found' % (module, start_line))
    return path, lines[start_line - 1:end_i + 1], start_line, end_i + 1


# ------------------------------------------------------------------ structural datasheet resolution (never a binding)

def _fact_datasheet(document, revision, url=''):
    """(slug, kind) for a bare (document, revision[, url]) triple — reuses board.custom.datasheets' own static
    table/index (never a second index retyped here); '' when nothing recognizes it (never guessed)."""
    from board.custom import datasheets as DS
    by_doc_rev, by_url = DS._build_indices(DS._static_rows())
    name = by_doc_rev.get((document or '', revision or '')) or (by_url.get(url) if url else '') or ''
    if not name:
        return '', ''
    row = next((d for d in DS._static_rows() if d['name'] == name), None)
    return name, (row or {}).get('kind', '')


def _signal_for_pin(bare_pin):
    """The INTn alternate function of one bare SoC pin ('PD2' -> 'INT0') — board.custom.soc_atmega328p.PINS' own
    functions list (the same source `cmod.custom.claims._int_capable` reads via SocPin.functions_json); '' when the
    pin carries no INTn function (every EXINT-capable pin on this chip is PD2/PD3 only)."""
    from board.custom.soc_atmega328p import PINS
    fns = PINS.get(bare_pin, ('', []))[1]
    return next((f for f in fns if f.startswith('INT') and f[3:].isdigit()), '')


def _register_fact(register, affects_pin=None):
    """(RegisterField row name, datasheet kind, datasheet slug, field description) for one register — the field
    affecting the INTn SIGNAL of `affects_pin` when this register is signal-keyed (EICRA/EIFR/EIMSK/PCICR/PCMSKx —
    their own fields carry `affects_signal`, never `affects_pin`, e.g. EICRA.ISC0 is INT0's field regardless of
    which pin happens to carry INT0), else the field affecting `affects_pin` directly (a port-bit register —
    DDRx/PORTx/PINx, cited bit by bit per pin), else the first field of that register (a representative citation;
    no bit is ever invented). '' everywhere when this register has no cited bit-level field at all (board.custom.
    register_fields_atmega328p.FIELDS does not cover it this slice, e.g. UBRR0H/UCSR0x — named, never guessed into
    the chip datasheet anyway)."""
    from board.custom import register_fields_atmega328p as RF
    from board.custom.soc_atmega328p import SOC
    from board.custom.uno_facts import M328_DOC, M328_REV, M328_URL
    fields = [f for f in RF.FIELDS if f['register'] == register]
    if not fields:
        return '', '', '', ''
    signal = _signal_for_pin(affects_pin) if affects_pin else ''
    f = (next((x for x in fields if signal and x.get('affects_signal') == signal), None)
         or next((x for x in fields if affects_pin and x.get('affects_pin') == affects_pin), None)
         or fields[0])
    name = '%s:%s.%s' % (SOC, register, f['field'])
    slug, kind = _fact_datasheet(M328_DOC, M328_REV, M328_URL)
    return name, kind, slug, f['description']


def _register_value(name):
    """'<Register row name> <space> <addr>[ (<addr_mem>)]' — e.g. 'atmega328p:DDRD io 0x0A (0x2A)'; SoC-fixed, so
    this never depends on a binding (pure, board.custom.hardware_chain's own register/address-mapping rows)."""
    from board.custom import hardware_chain as HC
    from board.custom.soc_atmega328p import SOC
    regs = {r['register']: r for r in HC.registers()}
    r = regs.get(name)
    if r is None:
        return ''
    maps = {}
    for m in HC.register_address_mappings():
        maps.setdefault(m['register'], {})[m['address_space']] = m['address']
    addrs = maps.get('%s:%s' % (SOC, name), {})
    addr = addrs.get('%s:io' % SOC) or addrs.get('%s:data' % SOC) or r.get('addr', '')
    addr_mem = addrs.get('%s:data' % SOC, '') if r.get('space') == 'io' else ''
    return '%s %s %s%s' % (r['name'], r.get('space', ''), addr, (' (%s)' % addr_mem) if addr_mem else '')


#: board_config.h pin macro -> the one pin it ALWAYS names, hardware-fixed regardless of variant (the SAME table
#: cmod.custom.targets._FIXED_DECLARED_CANONICALS already carries, read FROM there — never a second copy)
def _fixed_canonicals():
    from cmod.custom.targets import _FIXED_DECLARED_CANONICALS
    return _FIXED_DECLARED_CANONICALS


def _project_board_defaults(root):
    """{MACRO: literal text} read straight off this project's own committed board_config.h (a #define NAME VALUE
    line, trailing u/U/l/L stripped) — the pure, no-binding fallback for a VARIANT pin knob (LED_PIN et al)."""
    path = os.path.join(root, 'board_config.h')
    if not os.path.isfile(path):
        return {}
    out = {}
    for m in re.finditer(r'(?m)^\s*#define\s+([A-Z][A-Z0-9_]*)\s+([^\s/]+)', open(path, encoding='utf-8').read()):
        out[m.group(1)] = m.group(2).rstrip('uUlL')
    return out


def _board_pin_row(board, canonical):
    from board.custom import board_object as BO
    try:
        return next((p for p in BO.rows_for(board)['pins'] if p['canonical'] == canonical), None)
    except BO.BoardObjectRefused:
        return None


def _declared_canonical(macro, root):
    """The canonical board pin (e.g. 'D13') a declared pin macro names, WITHOUT a binding: the hardware-fixed table
    first, else this project's own board_config.h literal default (cmod.custom.targets._VARIANT_PIN_KNOBS' own
    vocabulary — the macros a variant MAY override). '' when neither settles it (never guessed)."""
    from cmod.custom.targets import _VARIANT_PIN_KNOBS
    fixed = _fixed_canonicals().get(macro)
    if fixed:
        return fixed
    if macro in _VARIANT_PIN_KNOBS:
        n = _project_board_defaults(root).get(macro)
        if n is not None and n.lstrip('-').isdigit():
            return ('A%s' % n) if macro == 'ADC_CHANNEL' else ('D%s' % n)
    return ''


def _counterpart_pin_macro(atom_full_name):
    """The declared pin macro an '_init' atom's runtime counterpart carries (hal_led_init -> LED_PIN via hal_led),
    read from a seeded graph's own TargetDefinition rows (cmod.custom.targets.derive, pure — the SAME convention
    `_init_counterpart_match` already established at the graph level, reused here by reading its OUTPUT instead of
    recomputing it): the first graph whose node IS this atom and whose row resolved a board pin names that pin's
    own `firmware_symbol`. '' when the atom is not a node of any seeded graph, or resolved no pin."""
    from cmod.custom.graph_seed import SEED_GRAPHS, seed_graph
    from cmod.custom import targets as T
    for g in SEED_GRAPHS:
        rows = seed_graph(g['name'])
        if rows is None:
            continue
        node = next((n for n in rows['nodes'] if n.get('atom') == atom_full_name), None)
        if node is None:
            continue
        for t in T.derive(g['name']):
            if t['node'] == node['instance'] and t.get('lives_on', 'unbound') != 'unbound':
                board, canonical = t['lives_on'].split(':', 1)
                pin = _board_pin_row(board, canonical)
                sym = (pin or {}).get('firmware_symbol') or ''
                if sym:
                    return sym
    return ''


#: a build-time KNOB the preprocessor substitutes away before the atom parser ever sees the function body -> the
#: cited fact its CURRENT value is computed to hit — found by scanning the function's own VERBATIM text (never
#: resources(), which only sees what SURVIVES preprocessing: UBRR0_VALUE/USART_U2X are hal.c's own #define/
#: board_config.h knobs, gone by the time pycparser sees `UBRR0H = (uint8_t)(UBRR0_VALUE >> 8);`).
#:   F_CPU         -> boards.txt build.f_cpu (programming: the toolchain's own clock setting)
#:   USART_U2X     -> boards.txt upload.speed (programming: the Optiboot baud this flag targets); its OWN literal
#:                    value (board_config.h's #define) is still what gets substituted, below
#:   UBRR0_VALUE   -> the ATmega328P datasheet's own Table 20-7 fact (soc) for whichever USART_U2X this project's
#:                    board_config.h currently carries — the REGISTER value hal.c computes, never the baud target
_KNOB_FACTS = {'F_CPU': ('build.f_cpu', None), 'USART_U2X': ('upload.speed', None),
              'UBRR0_VALUE': ('usart0.ubrr_115200_u2x1', 'usart0.ubrr_115200_u2x0')}


def _knob_fact_row(macro, root):
    from board.custom.uno_facts import SEED_UNO_FACTS
    spec = _KNOB_FACTS.get(macro)
    if spec is None:
        return None
    on_key, off_key = spec
    key = on_key
    if off_key:
        u2x = _project_board_defaults(root).get('USART_U2X', '1')
        key = on_key if u2x not in ('0', '', None) else off_key
    return next((f for f in SEED_UNO_FACTS if f['fact_key'] == key), None)


# ------------------------------------------------------------------ one identifier dict

def _comment_text(kind, slug, fact):
    tail = fact.rsplit(':', 1)[-1] if fact else ''
    return '/* <- %s: %s%s */' % (kind, slug, (' — %s' % tail) if tail else '')


def _identifier(name, kind, datasheet_kind, datasheet, fact, value, why):
    return {'name': name, 'kind': kind, 'datasheet_kind': datasheet_kind, 'datasheet': datasheet, 'fact': fact,
            'value': value, 'why': why}


def _pin_macro_identifier(macro, atom, atom_full_name, root, board, binding_dict, graph, manager):
    declared_direct = any(r.get('kind') == 'declared' and r.get('name') == macro for r in atom.get('resources') or [])
    canonical = _declared_canonical(macro, root)
    source_said = ('uses(%s)' % macro) if declared_direct else ('its runtime counterpart\'s uses(%s)' % macro)
    datasheet_kind, datasheet, fact, soc_pin = '', '', '', ''
    if canonical:
        pin = _board_pin_row(board, canonical)
        soc_pin = (pin or {}).get('soc_pin', '')
        facts_json = json.loads((pin or {}).get('facts_json') or '[]')
        pinout_fact = next((f for f in facts_json if f.endswith(':pinout.%s' % canonical)), '')
        from board.custom import board_uno as U
        datasheet, datasheet_kind = _fact_datasheet(U.DOC, U.REV, U.URL)
        fact = pinout_fact
    why = ('a declared pin macro (%s) -> %s' % (source_said or ('uses(%s)' % macro), canonical)
           if canonical else 'a declared pin macro (%s) with no resolved board pin this slice' % macro)
    value = ''
    if binding_dict is not None and canonical:
        from cmod.custom import claims as C
        try:
            claims = C.pin_claims(binding_dict, graph, manager=manager)
        except Exception:  # noqa: BLE001 — a binding with no materialized chain yet: value stays '', never a crash
            claims = []
        claim = next((c for c in claims if c['board_pin'] == ('%s:%s' % (board, canonical))), None)
        if claim is not None:
            num = canonical[1:] if canonical[:1] in ('D', 'A') else canonical
            value = '%s (%s = %s)' % (num, canonical, soc_pin or claim.get('soc_pin', '').rsplit(':', 1)[-1])
    return _identifier(macro, 'pin-macro', datasheet_kind, datasheet, fact, value, why), soc_pin


def _knob_identifier(macro, binding_dict, root):
    row = _knob_fact_row(macro, root)
    if row is None:
        return _identifier(macro, 'knob', '', '', '', '', 'a build-time knob with no cited fact this slice')
    datasheet, kind = _fact_datasheet(row['document'], row['revision'], row.get('url', ''))
    why = '%s -> %s (%s%s)' % (macro, row['name'], row['value'], (' %s' % row['unit']) if row['unit'] else '')
    value = ''
    if binding_dict is not None:
        # the literal THIS project's own board_config.h carries for the knob when it is one (USART_U2X) — else
        # (F_CPU/UBRR0_VALUE are never board_config.h literals themselves) the cited fact's own computed value
        literal = _project_board_defaults(root).get(macro)
        value = literal if literal is not None else str(row['value'])
    return _identifier(macro, 'knob', kind, datasheet, row['name'], value, why)


def _register_identifier(name, affects_pin, binding_dict):
    field_name, kind, slug, desc = _register_fact(name, affects_pin)
    why = ('%s — %s' % (field_name.rsplit(':', 1)[-1], desc) if field_name
           else 'a %s register with no bit-level citation this slice (register-summary only)' % name)
    value = _register_value(name) if binding_dict is not None else ''
    return _identifier(name, 'register', kind, slug, field_name, value, why)


# ------------------------------------------------------------------ render()

def _solution_graph(solution_name, manager=None):
    from cmod.custom.binding import _solution_dict
    sol = _solution_dict(solution_name, manager=manager)
    return (sol or {}).get('graph', '')


def render(atom_name, binding=None, manager=None):
    """{ok, atom, source, lines, identifiers, bindings, rendered} for one atom (see module docstring). `binding` =
    None | '<solution>[@<board>]' | an already-resolved HardwareBinding dict/row."""
    project, _m, atom = find_atom(atom_name)
    spec = P.resolve(project)
    atom_full_name = '%s:%s' % (project, atom['name'])
    path, raw_lines, start_line, end_line = _function_span(spec['root'], atom['module'], atom['line'])
    source = '\n'.join(raw_lines)

    binding_dict, graph, board = None, '', spec.get('board', '')
    if binding is not None:
        if isinstance(binding, dict):
            binding_dict = binding
        else:
            from cmod.custom import binding as BND
            binding_dict = BND.resolve(binding, manager=manager)
        if binding_dict is None:
            raise CodeInterfaceRefused('no binding %r (GET /api/firmware/solutions lists them)' % binding)
        board = binding_dict.get('board') or board
        graph = _solution_graph(binding_dict.get('solution', ''), manager=manager)

    identifiers = []
    declared_names = [r['name'] for r in atom.get('resources') or [] if r.get('kind') == 'declared']
    if not declared_names:
        sym = _counterpart_pin_macro(atom_full_name)
        if sym:
            declared_names = [sym]
    # pin-macro identifiers FIRST: their own resolved SoC pin (e.g. 'PB5') lets the register identifiers below cite
    # the EXACT RegisterField bit this atom's own declared pin touches, never a generic representative one — the
    # same single physical pin every register resource of an '_init' atom this slice sets (hal_led_init: LED_PIN's
    # PB5 -> DDRB.DDB5; never a different pin per register of the same atom, this slice has none that mix two).
    pin_hint = ''
    seen_declared = set()
    for name in declared_names:
        if name in seen_declared:
            continue
        seen_declared.add(name)
        ident, soc_pin = _pin_macro_identifier(name, atom, atom_full_name, spec['root'], board, binding_dict, graph, manager)
        identifiers.append(ident)
        pin_hint = pin_hint or soc_pin
    for r in atom.get('resources') or []:
        kind = r.get('kind')
        if kind == 'register':
            identifiers.append(_register_identifier(r['name'], pin_hint or None, binding_dict))
        elif kind == 'global':
            identifiers.append(_identifier(r['name'], 'global', '', '', '', '', 'a file-scope global — no datasheet'))
        elif kind == 'library':
            identifiers.append(_identifier(r['name'], 'library', '', '', '', '', 'an avr-libc/library call — no datasheet'))
    for name in _KNOB_FACTS:
        if re.search(r'\b%s\b' % re.escape(name), source):
            identifiers.append(_knob_identifier(name, binding_dict, spec['root']))

    bindings_out = {'soc': '', 'board': '', 'programming': ''}
    for i in identifiers:
        if i['datasheet_kind'] in bindings_out and i['datasheet']:
            bindings_out[i['datasheet_kind']] = i['datasheet']

    # ---- comments: one per identifier WITH a resolved datasheet_kind, anchored at its literal first use, or the
    # function's own first body line (just after the opening brace) when the name is never spelled out (macro
    # indirection — never a guessed site)
    default_anchor = next((idx for idx, line in enumerate(raw_lines) if '{' in line), 0)
    default_anchor = min(default_anchor + 1, len(raw_lines) - 1)
    comments_by_idx = {}
    for ident in identifiers:
        if not ident['datasheet_kind']:
            continue
        text = _comment_text(ident['datasheet_kind'], ident['datasheet'], ident['fact'])
        anchor = default_anchor
        pat = re.compile(r'\b%s\b' % re.escape(ident['name']))
        for idx, line in enumerate(raw_lines):
            if pat.search(line):
                anchor = idx
                break
        comments_by_idx.setdefault(anchor, []).append(text)

    lines_out, rendered_parts = [], []
    for idx, line in enumerate(raw_lines):
        comments = comments_by_idx.get(idx, [])
        lines_out.append({'n': start_line + idx, 'text': line, 'comment': '; '.join(comments)})
        rendered_parts.append(line)
        for c in comments:
            indent = re.match(r'[ \t]*', line).group(0)
            rendered_parts.append('%s%s' % (indent, c))
    rendered = '\n'.join(rendered_parts)

    return {'ok': True, 'atom': atom_full_name, 'source': source, 'lines': lines_out, 'identifiers': identifiers,
            'bindings': bindings_out, 'rendered': rendered}


# ------------------------------------------------------------------ CIsotope derivation

def level_ok(isotope_minimum_level, runtime_level):
    """True when `runtime_level` (a binding/board's own runtime level name, LEVEL_ORDER vocabulary) is at least as
    capable as `isotope_minimum_level` — False (refused BY NAME, never silently allowed) when the isotope needs a
    level the binding does not carry, or either name is not on the ladder at all."""
    if isotope_minimum_level not in LEVEL_ORDER or runtime_level not in LEVEL_ORDER:
        return False
    return LEVEL_ORDER.index(runtime_level) >= LEVEL_ORDER.index(isotope_minimum_level)


def _apply_substitutions(source, identifiers):
    """`source` with ONLY the literal occurrences of a pin-macro/knob identifier's OWN name replaced by
    '<value> /* <- <kind>: <slug> — <fact> */' (a register is never substituted — its value is SoC-fixed, not
    binding-dependent, see the module docstring); `substitutions_json`-worthy entries are exactly the ones that
    found a literal site (an identifier reached only through a runtime counterpart, with no literal name in this
    function's own text, applies no substitution — named in the isotope's own `notes`, never guessed into one)."""
    applied = []
    out = source
    for ident in identifiers:
        if ident['kind'] not in ('pin-macro', 'knob') or not ident.get('value'):
            continue
        pat = re.compile(r'\b%s\b' % re.escape(ident['name']))
        if not pat.search(out):
            continue
        repl = '%s /* <- %s: %s%s */' % (ident['value'], ident['datasheet_kind'], ident['datasheet'],
                                         (' — %s' % ident['fact'].rsplit(':', 1)[-1]) if ident['fact'] else '')
        out = pat.sub(repl.replace('\\', r'\\'), out)
        applied.append({'identifier': ident['name'], 'value': ident['value'], 'datasheet_kind': ident['datasheet_kind'],
                        'datasheet': ident['datasheet'], 'fact': ident['fact']})
    return out, applied


def isotope_name(atom_full_name, binding_name_):
    return '%s@%s' % (atom_full_name, binding_name_)


def derive_isotope(atom_name, binding, manager=None):
    """One CIsotope dict for (atom x binding), or None when the atom has no datasheet-bound identifier at all
    (ucd-iso-0: derived only for an atom with >= 1 — his ruling: "C-isotopes ... at least one binding out of
    three"). Pure over `render()`; `binding` is a string ('<solution>[@<board>]') or an already-resolved
    HardwareBinding dict/row."""
    rendered = render(atom_name, binding=binding, manager=manager)
    if not any(i['datasheet_kind'] for i in rendered['identifiers']):
        return None
    source, applied = _apply_substitutions(rendered['source'], rendered['identifiers'])
    sha = hashlib.sha256(source.encode('utf-8')).hexdigest()
    if isinstance(binding, dict):
        binding_dict = binding
    else:
        from cmod.custom import binding as BND
        binding_dict = BND.resolve(binding, manager=manager)
    project = rendered['atom'].split(':', 1)[0]
    name = isotope_name(rendered['atom'], binding_dict['name'])
    skipped = sorted({i['name'] for i in rendered['identifiers'] if i['kind'] in ('pin-macro', 'knob') and i.get('value')}
                     - {a['identifier'] for a in applied})
    notes = ('no literal textual site for: %s (reached only through a runtime counterpart/macro alias — carried in '
            'bindings_json/identifiers but not substituted into `source`)' % ', '.join(skipped)) if skipped else ''
    return {'name': name, 'parent': rendered['atom'], 'project': project, 'bindings_json': json.dumps(rendered['bindings']),
            'substitutions_json': json.dumps(applied), 'source': source, 'minimum_level': 'bare-c', 'sha256': sha,
            'foundational': False, 'provenance': 'derived', 'notes': notes}


def isotopes_for_atom(atom_name, manager=None):
    """One CIsotope per HardwareBinding of this atom's own project solutions that has >= 1 datasheet-bound
    identifier (one per atom x binding, never one per board alone — two bindings to the same board are two distinct
    isotopes, same posture as `cmod.custom.binding.bindings_for_solution`)."""
    from cmod.custom.binding import bindings_for_solution
    project, _m, atom = find_atom(atom_name)
    atom_full_name = '%s:%s' % (project, atom['name'])
    out = []
    for sol_name in _project_solution_names(project, manager=manager):
        for b in bindings_for_solution(sol_name, manager=manager):
            iso = derive_isotope(atom_full_name, b, manager=manager)
            if iso is not None:
                out.append(iso)
    return out


def isotopes_for_binding(binding, manager=None):
    """One CIsotope per atom of this binding's own graph that has >= 1 datasheet-bound identifier — the materialize
    idiom's own caller (cmod_firmware_api, on every GET of a solution/binding) and `GET /api/cmod/atoms/{atom}/code`'s
    sibling door `.../isotopes` (one atom at a time) both read FROM this, never recompute it twice."""
    if isinstance(binding, dict):
        binding_dict = binding
    else:
        from cmod.custom import binding as BND
        binding_dict = BND.resolve(binding, manager=manager)
    if binding_dict is None:
        return []
    graph = _solution_graph(binding_dict.get('solution', ''), manager=manager)
    from cmod.custom.graph_seed import seed_graph
    rows = seed_graph(graph)
    if rows is None:
        return []
    out = []
    for n in rows['nodes']:
        if n.get('kind') != 'c-atom' or not n.get('atom'):
            continue
        iso = derive_isotope(n['atom'], binding_dict, manager=manager)
        if iso is not None:
            out.append(iso)
    return out


def _project_solution_names(project, manager=None):
    """Every FirmwareSolution of this project — live rows when a manager has them, else the pure seed (same
    duality the rest of cmod uses)."""
    if manager is not None:
        rows = [getattr(r, 'name', '') for r in (manager.objectTables or {}).get('FirmwareSolution', {}).values()]
        if rows:
            return sorted(set(rows))
    from cmod.cmod_seed import CMOD_SEED_PAIRS
    rows = next((rs for n, _c, rs in CMOD_SEED_PAIRS if n == 'FirmwareSolution'), [])
    return sorted({r['name'] for r in rows})


# ------------------------------------------------------------------ the foundational example (ucd-iso-0 point 3)
#: the ESP32-C3's FreeRTOS firmware (board/custom/firmware/esp32c3) is NOT a cmod project today — `cmod.custom.
#: projects.TEMPLATES` names only 'uno' (checked 2026-10-10: no 'esp32c3'/'c3' key, and the directory has no
#: Makefile a 'plain' project could resolve against either — board.custom.gen renders it straight from CMakeLists,
#: outside cmod's own parser entirely). So THIS ONE isotope is modelled BY HAND, seeded with provenance='authored',
#: as the example his ruling asks for ("some forms of multithreading ... only available at FreeRTOS or ZephyrRTOS
#: levels ... we should specify a minimum-level property") — `polari_telemetry_start` (board/custom/firmware/
#: esp32c3/main/polari_c3.c:138-146), the function that CREATES the telemetry FreeRTOS task (xTaskCreate): no bare-C
#: UNO atom does this (bare-c has no task scheduler at all), so minimum_level='freertos' is not a substitution of
#: any parent — it is the isotope's OWN floor.
FOUNDATIONAL_ISOTOPE = {
    'name': 'polari_telemetry_start@esp32c3-freertos', 'parent': '', 'project': 'esp32c3',
    'bindings_json': json.dumps({'soc': 'espressif-esp32-c3-datasheet', 'board': '', 'programming': ''}),
    'substitutions_json': '[]',
    'source': (
        'void polari_telemetry_start(SemaphoreHandle_t gate, UBaseType_t prio)\n'
        '{\n'
        '    TaskHandle_t h;\n'
        '    memset(&s_state, 0, sizeof s_state);\n'
        '    strncpy(s_state.name, RIG_NAME, sizeof s_state.name - 1);\n'
        '    s_gate = gate;\n'
        '    xTaskCreate(telemetry_task, "tel", 3072, NULL, prio, &h);   /* <- soc: espressif-esp32-c3-datasheet — a '
        'FreeRTOS task; no bare-C runtime has a scheduler to create one on */\n'
        '    polari_trace_task(h, 9, "TEL");\n'
        '}'
    ),
    'minimum_level': 'freertos', 'sha256': '', 'foundational': True, 'provenance': 'authored',
    'notes': ('board/custom/firmware/esp32c3/main/polari_c3.c:138-146 — cmod does not parse the C3 project this '
             'slice (no entry in cmod.custom.projects.TEMPLATES; no Makefile a \'plain\' project resolve() could '
             'use either), so this ONE row is hand-modelled as the example his ruling asks for, not derived by '
             'render(). xTaskCreate is FreeRTOS\'s own API (soc datasheet: it is the chip the task runs on; no '
             'board/programming reference is cited — named, not guessed). level_ok(\'freertos\', \'bare-c\') is '
             'False: a bare-c binding refuses this isotope by name.')}
FOUNDATIONAL_ISOTOPE['sha256'] = hashlib.sha256(FOUNDATIONAL_ISOTOPE['source'].encode('utf-8')).hexdigest()
