"""
@module cmod.custom.export_cmake

THE FIRMWARE EXPORT (ucd-0f pulled forward, UNO_CORE_DEMO_PLAN.md §5b; FIRMWARE_EXPORT_PLAN.md exp-0; his words
2026-10-07/08: "each of the apps need to be buildable and their code exportable and inspectable and installable via
normal cmake for firmware so we can inspect the final code", "the key thing we need is a link that shows just the UI
for firmware no code and an export").

`export(fs)` takes one FirmwareSolution and writes a DIRECTORY a person carries away and builds WITHOUT Polari:

    <solution>@<stamp>/
      hal.c hal.h polari_graph.c polari_graph.h board_config.h <class>_packets.h   the rendered plain-C project, byte for
      Makefile polari-firmware.json                                                 byte what cmod-glue committed
      CMakeLists.txt                     the person-facing build: cmake -S . -B build && cmake --build build
      avr-gcc.toolchain.cmake            the cross toolchain (avr-gcc / avr-objcopy / avr-size / avrdude)
      polari-build.cmake                 the ONE-COMMAND build (cmake -P polari-build.cmake) — also what verify() runs
      README.md                          what the firmware does, its tasks, schedule, register map, the board, the
                                         sizes, the shas, how to build / simulate / flash — rendered from the rows
      polari-export.json                 the manifest: solution, graph, board (usb ids / programmer / baud as DATA),
                                         every file's sha256, the Makefile build's hex sha, provenance
    <solution>@<stamp>.tar.gz

CMake targets: `board` (ALL: firmware.elf → firmware.hex), `twin` (firmware.elf — the simavr twin runs the SAME bytes
the board gets; `-DPOLARI_TARGET=twin|board` only sets a compile definition the C does not read today, which the
identical sha PROVES — the two cases are the same code, readable side by side), `size`, `flash` (the exact avrdude argv
board.custom.flash renders, port from -DPOLARI_PORT=/dev/ttyACM0; the gate: never flash what did not rebuild to the
recorded sha). `verify(path)` runs polari-build.cmake on the board engines image (cmod_engines 'cmake', beside avr-gcc —
the same rung `make alone` proves on) and compares the hex sha with the committed Makefile build's: parity identical |
differs, never assumed. D-exp-1: exports live under module_home('exp'), transient; the FirmwareExport row is the record.
"""
import datetime
import hashlib
import io
import json
import os
import shutil
import tarfile

from cmod.custom import glue as GL
from cmod.custom import glue_build as GB

MCU = 'atmega328p'
F_CPU = '16000000UL'
BAUD = 115200


class ExportRefused(ValueError):
    pass


def _sha(b):
    return hashlib.sha256(b).hexdigest()


def home(env=None):
    from polariApiServer.module_home import module_home
    return module_home('exp', env if env is not None else os.environ.get('POLARI_EXP_HOME'))


def _stamp():
    return datetime.datetime.now().strftime('%Y-%m-%dT%H-%M-%S')


def _graph(fs):
    from cmod.custom.graph_seed import seed_graph
    graph = fs.get('graph') if isinstance(fs, dict) else getattr(fs, 'graph', '')
    rows = seed_graph(graph)
    if rows is None:
        raise ExportRefused('no graph %r (pol cmod graphs lists them)' % graph)
    return graph, rows['graph']


def _board_facts(board, manager=None):
    """The board as DATA for the manifest (usb ids, programmer, transport) from the BoardDefinition row — the seed when
    no server; never typed here."""
    from board.custom import board_object as BO
    rows = None
    if manager is not None:
        t = (getattr(manager, 'objectTables', {}) or {}).get('BoardDefinition', {}) or {}
        rows = [BO.as_dict(r, 'BoardDefinition') for r in t.values()]
    if not rows:
        rows = BO.seed_tables().get('BoardDefinition', [])
    b = next((r for r in rows if r.get('name') == board), None) or {}
    return {'name': board, 'soc': b.get('soc', ''), 'usb_ids': json.loads(b.get('usb_ids_json') or '[]'), 'programmer': b.get('programmer', ''),
            'transport': b.get('transport', ''), 'twin': b.get('twin', ''), 'baud': BAUD, 'flash_kb': b.get('flash_kb', 0), 'ram_kb': b.get('ram_kb', 0)}


# ---------------------------------------------------------------- the generated build files

def cmakelists(solution, sources, headers, board):
    # ucd-0b: a project whose claims generated pin_config.c carries the SAME -DPOLARI_PIN_CONFIG=1 the committed
    # Makefile defines (cmod.custom.glue) — else hal.c's #ifndef branches would ALSO compile here and the hex would
    # never match the Makefile build (parity would always say "differs").
    pin_config_define = ' POLARI_PIN_CONFIG=1' if 'pin_config.c' in sources else ''
    return '''# CMakeLists.txt — generated by Polari (cmod.custom.export_cmake) for firmware solution "%(sol)s" on %(board)s.
# Build WITHOUT Polari:   cmake -S . -B build && cmake --build build        (→ build/firmware.hex)
# One command:            cmake -P polari-build.cmake                        (→ ./firmware.hex)
# Simulate:               cmake --build build --target twin  → build/firmware.elf, run by simavr / polari-avr-twin
# Flash (the gate: only a build whose sha matches polari-export.json):
#                         cmake --build build --target flash -- POLARI_PORT=/dev/ttyACM0   (or -DPOLARI_PORT=… at configure)
cmake_minimum_required(VERSION 3.13)
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/avr-gcc.toolchain.cmake" CACHE FILEPATH "the avr-gcc cross toolchain")
project(%(proj)s C)

set(POLARI_TARGET "board" CACHE STRING "board | twin — which case this build is for (today the same bytes; see README)")
set(POLARI_PORT "/dev/ttyACM0" CACHE STRING "the serial port the flash target uses")
set(MCU %(mcu)s)
set(F_CPU %(fcpu)s)
string(TOUPPER "${POLARI_TARGET}" POLARI_TARGET_UC)

add_executable(firmware.elf %(sources)s)
set_target_properties(firmware.elf PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
target_compile_definitions(firmware.elf PRIVATE F_CPU=${F_CPU} POLARI_TARGET_${POLARI_TARGET_UC}=1%(pin_config_define)s)
# the SAME flags the committed Makefile uses (parity is checked by Polari: polari-export.json makefile_hex_sha256)
target_compile_options(firmware.elf PRIVATE -mmcu=${MCU} -Os -std=gnu99 -Wall -Wextra -Werror -ffunction-sections -fdata-sections)
target_link_options(firmware.elf PRIVATE -mmcu=${MCU} -Wl,--gc-sections)
# headers: %(headers)s (CMake's own dependency scan tracks them)

add_custom_command(OUTPUT "${CMAKE_BINARY_DIR}/firmware.hex"
                   COMMAND ${CMAKE_OBJCOPY} -O ihex -R .eeprom "$<TARGET_FILE:firmware.elf>" "${CMAKE_BINARY_DIR}/firmware.hex"
                   DEPENDS firmware.elf COMMENT "firmware.hex (Intel HEX for avrdude)")
add_custom_target(board ALL DEPENDS "${CMAKE_BINARY_DIR}/firmware.hex")
add_custom_target(twin DEPENDS firmware.elf COMMENT "the twin runs firmware.hex/elf in simavr (polari-avr-twin --hex firmware.hex --mcu ${MCU} --freq ${F_CPU})")
add_custom_target(size COMMAND ${CMAKE_SIZE} -A "$<TARGET_FILE:firmware.elf>" DEPENDS firmware.elf)
add_custom_target(flash COMMAND ${AVRDUDE} -p ${MCU} -c arduino -P ${POLARI_PORT} -b %(baud)d -D -U "flash:w:${CMAKE_BINARY_DIR}/firmware.hex:i"
                  DEPENDS "${CMAKE_BINARY_DIR}/firmware.hex" COMMENT "avrdude → ${POLARI_PORT} (Optiboot); verify the sha first")
''' % {'sol': solution, 'board': board, 'proj': solution.replace('-', '_'), 'mcu': MCU, 'fcpu': F_CPU,
       'sources': ' '.join(sources), 'headers': ' '.join(headers), 'baud': BAUD, 'pin_config_define': pin_config_define}


TOOLCHAIN = '''# avr-gcc.toolchain.cmake — the cross toolchain for the ATmega328P (generated by Polari; plain CMake)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_CXX_COMPILER avr-g++)
set(CMAKE_OBJCOPY avr-objcopy)
set(CMAKE_SIZE avr-size)
set(AVRDUDE avrdude)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)   # no host runtime: a try-compile must not link an executable
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# toolchain packages (Debian/Ubuntu): gcc-avr binutils-avr avr-libc avrdude cmake   — the same ones prf-board-engines installs
'''

ONE_COMMAND = '''# polari-build.cmake — the one-command build:  cmake -P polari-build.cmake   (optionally -DPOLARI_TARGET=twin first)
# configure + build in ./build, then copy firmware.hex beside the sources (what Polari's verify() compares by sha).
if(NOT DEFINED POLARI_TARGET)
  set(POLARI_TARGET board)
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}" -B "${CMAKE_CURRENT_LIST_DIR}/build"
                        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_CURRENT_LIST_DIR}/avr-gcc.toolchain.cmake -DPOLARI_TARGET=${POLARI_TARGET}
                RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "configure failed (${rc})")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_CURRENT_LIST_DIR}/build" --target board RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "build failed (${rc})")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${CMAKE_CURRENT_LIST_DIR}/build" --target size)
file(COPY "${CMAKE_CURRENT_LIST_DIR}/build/firmware.hex" DESTINATION "${CMAKE_CURRENT_LIST_DIR}")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/build/firmware.elf" DESTINATION "${CMAKE_CURRENT_LIST_DIR}")
message(STATUS "firmware.hex written beside the sources")
'''


def readme(solution, fs, graph, g, board, schedule, assigns, record, files, makefile_sha, proof=None):
    proof = proof or {'advice': 'no proof summary', 'proof_why': '', 'purposes': []}
    build = (record or {}).get('build') or {}
    lanes = {}
    for s in schedule:
        lanes.setdefault(s.get('lane', '?'), []).append(s)
    lines = ['# %s — firmware export' % (fs.get('title') or solution), '',
             (fs.get('purpose') or g.get('description') or 'A Polari Firmware Solution: the C tasks below, scheduled and bound to the board\'s pins.'), '',
             'Generated by Polari on %s from Firmware Solution `%s` (graph `%s`) for board **%s**. Everything in this folder is' % (_stamp(), solution, graph, board['name']),
             'plain C + plain CMake: nothing here needs Polari to build, simulate or flash. Inspect it; the README is rendered from',
             'the same rows the Polari pages show, never hand-written.', '',
             '## Proof — is this firmware advised for a real board?', '',
             '**%s** — %s' % (proof['advice'], proof['proof_why']), '',
             '| Purpose | status | latest proof |', '|---|---|---|'] + \
            ['| %s | %s | %s |' % (r['name'], r['status'], r['last_proof'] or '—') for r in proof['purposes']] + ['',
             'A Purpose is proven on the sim by its acceptance scenario on the simavr twin (`pol capability prove <name> --twin`) and on',
             'hardware by the same scenario on a detected board (`--hardware`). Building this folder is always allowed; flashing an',
             'unproven firmware is a person\'s own call.', '',
             '## Build (no Polari)', '', '```', 'cmake -S . -B build && cmake --build build      # → build/firmware.hex (target board)',
             'cmake -P polari-build.cmake                      # the same in one command → ./firmware.hex',
             'cmake --build build --target size                # avr-size', '```', '',
             'Toolchain (Debian/Ubuntu): `apt install gcc-avr binutils-avr avr-libc avrdude cmake` — the same packages the `prf-board-engines` image',
             'carries. The committed `Makefile` is the build Polari itself proved (`make` alone); the CMake build is checked against it by sha:',
             'makefile firmware.hex sha256 `%s`.' % (makefile_sha or 'not recorded'), '',
             '## The two cases — simulation and the board', '',
             'The simavr digital twin runs the SAME `firmware.hex` the board is flashed with: there is one firmware, not two. `-DPOLARI_TARGET=twin|board`',
             'sets a compile definition the code does not read today; the identical sha proves the two cases are one code. Targets: `board` (hex),',
             '`twin` (elf, run it with `polari-avr-twin --hex build/firmware.hex --mcu %s --freq %s` from the engines image, or `pol board twin`),' % (MCU, F_CPU.rstrip('UL')),
             '`flash` (below).', '',
             '## Flash (the gate)', '',
             'Never flash what did not rebuild to the recorded sha. Then, with the board on USB (Optiboot, %d baud):' % BAUD, '',
             '```', 'cmake -S . -B build -DPOLARI_PORT=/dev/ttyACM0 && cmake --build build --target flash', '```', '',
             'That runs exactly: `avrdude -p %s -c arduino -P /dev/ttyACM0 -b %d -D -U flash:w:build/firmware.hex:i`.' % (MCU, BAUD), '',
             '## The board', '',
             '| fact | value |', '|---|---|', '| board | %s |' % board['name'], '| SoC | %s @ %s Hz |' % (board.get('soc') or MCU, F_CPU.rstrip('UL')),
             '| USB ids | %s |' % (', '.join(board.get('usb_ids') or []) or 'see Polari'), '| programmer | %s (%s) |' % (board.get('programmer') or '?', board.get('transport') or '?'),
             '| twin | %s |' % (board.get('twin') or '?'), '| flash / RAM | %s KB / %s KB |' % (board.get('flash_kb') or '?', board.get('ram_kb') or '?'), '',
             '## Tasks and schedule (derived from the C, never authored)', '']
    for lane in ('init', 'isr', 'tick', 'loop'):
        rows = sorted(lanes.get(lane, []), key=lambda s: s.get('order', 0))
        if rows:
            lines.append('**%s**' % lane)
            for s in rows:
                lines.append('- `%s` — %s%s' % (s.get('task'), s.get('kind', ''), (' · ' + s['notes']) if s.get('notes') else ''))
            lines.append('')
    for lane, rows in lanes.items():
        if lane not in ('init', 'isr', 'tick', 'loop'):
            lines.append('**%s**' % lane)
            lines += ['- `%s`' % s.get('task') for s in rows] + ['']
    lines += ['## Register map (each task\'s target on the board\'s pins)', '', '| task | port | kind | lives on | status |', '|---|---|---|---|---|']
    for a in assigns:
        lines.append('| `%s` | %s | %s | %s | %s |' % (a.get('task'), a.get('port') or '—', a.get('target_kind'), a.get('lives_on'), a.get('status')))
    lines += ['', '## Sizes (the Makefile build, measured)', '']
    if build:
        lines.append('text %s B · data %s B · bss %s B · built by %s' % (build.get('size_text'), build.get('size_data'), build.get('size_bss'), build.get('built_by', '?')))
    else:
        lines.append('not built yet in Polari (pol firmware build %s)' % solution)
    lines += ['', '## Files (sha256)', '', '| file | sha256 | bytes |', '|---|---|---|']
    lines += ['| %s | %s | %d |' % (f['file'], f['sha256'], f['bytes']) for f in files]
    lines += ['', '## Provenance', '', '- the C project is the one cmod-glue rendered and committed for graph `%s` (`modules/cmod/custom/graphs/`);' % graph,
              '- schedule and register map come from the atoms\' own annotations and the solution\'s RegisterAssignment rows;',
              '- the export is transient (regenerated on request); its record is the `FirmwareExport` row in Polari;',
              '- Polari: https://github.com/dausume/polari-suite (GPLv3).', '']
    return '\n'.join(lines)


# ---------------------------------------------------------------- the export

#: FirmwareExport.form (ucd-frames+bundle, UNO_CORE_DEMO_PLAN.md §5b): source-dir (the original, unchanged) + two new
#: forms — install-bundle (ONLY what a person flashes with: firmware.hex + polari-install.json + INSTALL.md, no
#: sources) and solution (the board-agnostic C + graph/requirements/purposes as data, no pin_config.*/board_config.h/
#: Makefile — "builds nothing by itself").
FORMS = ('source-dir', 'install-bundle', 'solution')


def export(fs, manager=None, target='both', out_root=None, verify_build=False, statuses=None, form='source-dir'):
    """Write the export directory + tar.gz for one FirmwareSolution (dict or row), in one of FORMS. -> the
    FirmwareExport row fields (+ 'files'). Raises ExportRefused with the reason (no graph, no rendered project,
    validation refused, an unknown form)."""
    if form not in FORMS:
        raise ExportRefused('form %r is not one of %s' % (form, ', '.join(FORMS)))
    from cmod.custom import firmware as FW
    sol, bnd = FW.as_solution_target(fs, manager=manager)
    guard = FW._binding_build_guard(bnd, sol)
    if guard:
        raise ExportRefused(guard)
    fsd = sol if isinstance(sol, dict) else {k: getattr(sol, k, '') for k in ('name', 'title', 'graph', 'purpose', 'board_definition', 'board_variable')}
    solution = fsd.get('name', '')
    if target not in ('both', 'board', 'twin'):
        raise ExportRefused('target %r is not both | board | twin' % target)
    ok, why, details = FW.validate(fsd, manager=manager)
    if not ok:
        raise ExportRefused(why)
    graph, g = _graph(fsd)
    # his rulings 2026-10-09: the firmware's state = a summary of its Purposes; ADVISE on an unproven hardware build, never block
    # ("useful to still have it try and compile … to see what happens for debugging")
    from cmod.custom import capabilities as CAP
    proof = CAP.purpose_summary(graph, manager=manager, board=details['board'], statuses=statuses)
    d = GL.project_dir(g)
    if not os.path.isdir(d) or not any(f.endswith('.c') for f in os.listdir(d)):
        raise ExportRefused('graph %s has no rendered project at %s (pol cmod render %s)' % (graph, d, graph))
    board = _board_facts(details['board'], manager=manager)
    record = GL.load_record(graph)
    makefile_sha = ((record or {}).get('build') or {}).get('hex_sha256', '')
    name = '%s@%s' % (solution, _stamp())
    root = out_root or home()
    path = os.path.join(root, name)
    if os.path.exists(path):
        shutil.rmtree(path)
    os.makedirs(path)
    if form == 'install-bundle':
        return _export_install_bundle(path, name, solution, board, record, makefile_sha, proof, d, target, graph)
    if form == 'solution':
        return _export_solution(path, name, solution, fsd, graph, proof, d)
    return _export_source_dir(path, name, solution, fsd, graph, g, board, record, makefile_sha, proof, d, target, verify_build)


def _export_source_dir(path, name, solution, fsd, graph, g, board, record, makefile_sha, proof, d, target, verify_build):
    from cmod.custom import firmware as FW
    project = {f: open(os.path.join(d, f), 'rb').read() for f in sorted(os.listdir(d))
               if os.path.isfile(os.path.join(d, f)) and not f.startswith('firmware.')}
    sources = sorted(f for f in project if f.endswith('.c'))
    headers = sorted(f for f in project if f.endswith('.h'))
    out = dict(project)
    out['CMakeLists.txt'] = cmakelists(solution, sources, headers, board['name']).encode()
    out['avr-gcc.toolchain.cmake'] = TOOLCHAIN.encode()
    out['polari-build.cmake'] = ONE_COMMAND.encode()
    schedule = FW.schedule_for(graph, solution_name=solution)
    assigns = FW.assignments_for(graph, solution_name=solution)
    files = [{'file': f, 'sha256': _sha(b), 'bytes': len(b)} for f, b in sorted(out.items())]
    out['README.md'] = readme(solution, fsd, graph, g, board, schedule, assigns, record, files, makefile_sha, proof).encode()
    manifest = {'schema': 'polari-export/1', 'solution': solution, 'title': fsd.get('title', ''), 'graph': graph, 'board': board,
                'proof': proof,   # the Purposes and their proofs; `advice` says whether a real board is advised
                'target': target, 'form': 'source-dir', 'mode': 'online', 'generated_at': _stamp(), 'mcu': MCU, 'f_cpu': F_CPU,
                'makefile_hex_sha256': makefile_sha, 'files': files + [{'file': 'README.md', 'sha256': _sha(out['README.md']), 'bytes': len(out['README.md'])}],
                'build': 'cmake -S . -B build && cmake --build build', 'one_command': 'cmake -P polari-build.cmake',
                'flash_argv': ['avrdude', '-p', MCU, '-c', 'arduino', '-P', '<port>', '-b', str(BAUD), '-D', '-U', 'flash:w:build/firmware.hex:i'],
                'gate': 'never flash what did not rebuild to makefile_hex_sha256 (cmake_hex_sha256 in the FirmwareExport row)'}
    out['polari-export.json'] = (json.dumps(manifest, indent=1, ensure_ascii=False) + '\n').encode()
    for f, b in out.items():
        open(os.path.join(path, f), 'wb').write(b)
    tar_path = path + '.tar.gz'
    with tarfile.open(tar_path, 'w:gz') as tar:
        tar.add(path, arcname=name)
    tar_sha = _sha(open(tar_path, 'rb').read())
    row = {'name': name, 'solution': solution, 'graph': graph, 'board': board['name'], 'form': 'source-dir', 'target': target, 'mode': 'online',
           'path': path, 'tar_path': tar_path, 'tar_sha256': tar_sha, 'files_json': json.dumps(manifest['files']), 'makefile_sha256': makefile_sha,
           'cmake_sha256': '', 'parity': 'not-run', 'verify_log': '', 'download_url': '/api/firmware/exports/%s/download' % name,
           'created_at': datetime.datetime.now().isoformat(timespec='seconds'), 'status': 'created', 'why': '',
           'notes': '%s · %s' % (proof['proof_status'], proof['advice'])}
    if verify_build:
        row.update(verify(path, makefile_sha))
    return row


# ---------------------------------------------------------------- form: install-bundle (ucd-frames+bundle)

def _install_bundle_hex(d, makefile_sha, solution):
    """firmware.hex bytes + its sha256 — built on the spot (glue_build.make_alone, the SAME `make` rung the glue
    record's own build used) when the project dir has none yet; refuses (never silently accepts) a mismatch against
    the glue record's own hex_sha256."""
    from cmod.custom import glue_build as GLB
    hex_path = os.path.join(d, 'firmware.hex')
    hexb = open(hex_path, 'rb').read() if os.path.isfile(hex_path) else None
    if hexb is None:
        mk = GLB.make_alone(d)
        if not mk.get('ok'):
            raise ExportRefused('install-bundle: `make` did not produce firmware.hex for %s (%s)'
                                % (solution, (mk.get('stdout', '') or '')[-300:]))
        hexb = mk['hex']
        if makefile_sha and mk['hex_sha256'] != makefile_sha:
            raise ExportRefused('install-bundle: the freshly built hex (sha256 %s…) does not match the glue record\'s '
                                '(%s…) for %s — rebuild (`pol firmware build %s`) first'
                                % (mk['hex_sha256'][:16], makefile_sha[:16], solution, solution))
        makefile_sha = makefile_sha or mk['hex_sha256']
    hex_sha = _sha(hexb)
    if makefile_sha and hex_sha != makefile_sha:
        raise ExportRefused('install-bundle: firmware.hex on disk (sha256 %s…) does not match the glue record\'s '
                            '(%s…) for %s — rebuild (`pol firmware build %s`) first'
                            % (hex_sha[:16], makefile_sha[:16], solution, solution))
    return hexb, hex_sha


def _install_readme(solution, board, hex_sha, argv_text, proof):
    return '''# %(sol)s — install bundle

Everything a person needs to FLASH `%(sol)s` onto a real **%(board)s** — nothing else. No sources are in this bundle
(the board-agnostic C + build files are the `solution` / `source-dir` export forms).

## 1. Compare the sha first (the gate)

Never flash a `firmware.hex` that does not match `hex_sha256` in `polari-install.json`:

```
sha256sum firmware.hex
# must read: %(sha)s
```

## 2. Flash

With the board on USB (%(programmer)s, %(baud)d baud) and `<port>` replaced by its serial port (e.g. `/dev/ttyACM0`):

```
%(argv)s
```

`-D` skips the chip-erase (Optiboot has none to skip); `-U flash:w:firmware.hex:i` WRITES and THEN READS BACK the
flash, comparing every byte — the write is verified by avrdude itself, never assumed.

## 3. Is this firmware advised for a real board?

**%(advice)s** — %(why)s
''' % {'sol': solution, 'board': board.get('name', ''), 'sha': hex_sha, 'programmer': board.get('programmer') or '?',
       'baud': BAUD, 'argv': argv_text, 'advice': proof.get('advice', ''), 'why': proof.get('proof_why', '')}


def _export_install_bundle(path, name, solution, board, record, makefile_sha, proof, d, target, graph):
    from board.custom import flash as FL
    hexb, hex_sha = _install_bundle_hex(d, makefile_sha, solution)
    argv = FL.argv_for(board['name'], '<port>', 'firmware.hex')
    argv_text = ' '.join(argv)
    manifest = {'schema': 'polari-install/1', 'solution': solution, 'board': board['name'], 'form': 'install-bundle',
               'generated_at': _stamp(), 'mcu': MCU, 'baud': BAUD, 'usb_ids': board.get('usb_ids'),
               'programmer': board.get('programmer'), 'hex_sha256': hex_sha, 'argv': argv, 'argv_text': argv_text,
               'proof': proof,
               'gate': 'compare hex_sha256 against firmware.hex\'s own sha256 before flashing — never flash a file that differs'}
    out = {'firmware.hex': hexb, 'polari-install.json': (json.dumps(manifest, indent=1, ensure_ascii=False) + '\n').encode(),
          'INSTALL.md': _install_readme(solution, board, hex_sha, argv_text, proof).encode()}
    for f, b in out.items():
        open(os.path.join(path, f), 'wb').write(b)
    files = [{'file': f, 'sha256': _sha(b), 'bytes': len(b)} for f, b in sorted(out.items())]
    tar_path = path + '.tar.gz'
    with tarfile.open(tar_path, 'w:gz') as tar:
        tar.add(path, arcname=name)
    tar_sha = _sha(open(tar_path, 'rb').read())
    return {'name': name, 'solution': solution, 'graph': graph, 'board': board['name'], 'form': 'install-bundle',
           'target': target, 'mode': 'online', 'path': path, 'tar_path': tar_path, 'tar_sha256': tar_sha,
           'files_json': json.dumps(files), 'makefile_sha256': hex_sha, 'cmake_sha256': '', 'parity': 'not-run',
           'verify_log': '', 'download_url': '/api/firmware/exports/%s/download' % name,
           'created_at': datetime.datetime.now().isoformat(timespec='seconds'), 'status': 'created', 'why': '',
           'notes': '%s · %s' % (proof.get('proof_status', ''), proof.get('advice', ''))}


# ---------------------------------------------------------------- form: solution (board-agnostic, ucd-frames+bundle)

#: project files that belong to a BOARD BINDING, never the board-agnostic solution
_BOUND_ONLY = {'pin_config.c', 'pin_config.h', 'board_config.h', 'Makefile', 'polari-firmware.json'}


def _solution_readme(solution, fsd, graph, reqs, purposes, proof):
    lines = ['# %s — board-agnostic solution' % (fsd.get('title') or solution), '',
             fsd.get('purpose') or ('A Polari Firmware Solution exported board-agnostically: the C tasks graph `%s` '
                                    'schedules, never bound to a board.' % graph), '',
             'This folder **builds nothing by itself** — there is no `board_config.h`, no `pin_config.*`, no `Makefile`. '
             'It is the SOLUTION: the atoms\' own C + its requirements + its Purposes, so a person (or Polari) can check '
             'whether a board is a valid target before binding it.', '',
             '## Requirements a board must meet (`requirements.json`)', '',
             '| node | kind | role | required | resource_kind | constraints |', '|---|---|---|---|---|---|']
    for r in reqs:
        lines.append('| %s | %s | %s | %s | %s | %s |' % (r.get('node', ''), r.get('kind', ''), r.get('role', ''),
                                                            r.get('required'), r.get('resource_kind', ''), r.get('constraints', '')))
    lines += ['', '## Purposes (`purposes.json`)', '', '| name | goal | acceptance scenario |', '|---|---|---|']
    for p in purposes:
        lines.append('| %s | %s | %s |' % (p['name'], p['goal'], p['acceptance_scenario']))
    lines += ['', '## Binding this solution to a board', '', '```', 'pol firmware bind %s --board <b>' % solution, '```', '',
             'Binding checks `requirements.json` against the board\'s own pins/peripherals and produces a BOUND firmware '
             '(the `source-dir` / `install-bundle` export forms) — never the other way around.', '',
             '## Proof so far', '', '**%s** — %s' % (proof.get('advice', ''), proof.get('proof_why', '')), '',
             '## Files', '',
             '- `hal.c` / `hal.h` — the board-independent hardware abstraction the atoms call',
             '- `polari_graph.c` / `polari_graph.h` — the generated app: the schedule over the atoms, from the graph',
             '- `*_packets.h` — the wire headers (board-agnostic: generated from the class contract, not the board)',
             '- `graph.json` — the CGraph + its nodes/edges, as rows',
             '- `requirements.json`, `purposes.json`, `polari-solution.json` — this solution as data', '']
    return '\n'.join(lines)


def _export_solution(path, name, solution, fsd, graph, proof, d):
    from cmod.custom import graph_seed as GS
    from cmod.custom import targets as TG
    from cmod.custom import capabilities as CAP
    rows = GS.seed_graph(graph)
    project = {f: open(os.path.join(d, f), 'rb').read() for f in sorted(os.listdir(d))
               if os.path.isfile(os.path.join(d, f)) and f not in _BOUND_ONLY and not f.startswith('firmware.')}
    out = dict(project)
    out['graph.json'] = (json.dumps({'graph': rows['graph'], 'nodes': rows['nodes'], 'edges': rows['edges']},
                                    indent=1, ensure_ascii=False) + '\n').encode()
    reqs = [{k: v for k, v in r.items() if k not in ('lives_on', 'board')} for r in TG.derive(graph)]
    out['requirements.json'] = (json.dumps(reqs, indent=1, ensure_ascii=False) + '\n').encode()
    purposes = [{'name': c['name'], 'title': c.get('title', ''), 'goal': c.get('goal', ''),
                'acceptance_scenario': c.get('acceptance_scenario', '')} for c in CAP.purposes_for_graph(graph)]
    out['purposes.json'] = (json.dumps(purposes, indent=1, ensure_ascii=False) + '\n').encode()
    out['README.md'] = _solution_readme(solution, fsd, graph, reqs, purposes, proof).encode()
    files = [{'file': f, 'sha256': _sha(b), 'bytes': len(b)} for f, b in sorted(out.items())]
    manifest = {'schema': 'polari-solution/1', 'solution': solution, 'graph': graph, 'form': 'solution',
               'generated_at': _stamp(), 'files': files, 'requirements': len(reqs), 'purposes': [p['name'] for p in purposes],
               'notes': 'board-agnostic: builds nothing by itself — bind it with `pol firmware bind %s --board <b>`' % solution}
    out['polari-solution.json'] = (json.dumps(manifest, indent=1, ensure_ascii=False) + '\n').encode()
    files = [{'file': f, 'sha256': _sha(b), 'bytes': len(b)} for f, b in sorted(out.items())]
    for f, b in out.items():
        open(os.path.join(path, f), 'wb').write(b)
    tar_path = path + '.tar.gz'
    with tarfile.open(tar_path, 'w:gz') as tar:
        tar.add(path, arcname=name)
    tar_sha = _sha(open(tar_path, 'rb').read())
    return {'name': name, 'solution': solution, 'graph': graph, 'board': '', 'form': 'solution', 'target': 'none',
           'mode': 'online', 'path': path, 'tar_path': tar_path, 'tar_sha256': tar_sha, 'files_json': json.dumps(files),
           'makefile_sha256': '', 'cmake_sha256': '', 'parity': 'not-run', 'verify_log': '',
           'download_url': '/api/firmware/exports/%s/download' % name,
           'created_at': datetime.datetime.now().isoformat(timespec='seconds'), 'status': 'created', 'why': '',
           'notes': 'board-agnostic solution export (%d requirement(s), %d purpose(s))' % (len(reqs), len(purposes))}


def verify(path, makefile_sha=''):
    """Run the exported one-command CMake build on the engines rung (cmod_engines 'cmake' beside avr-gcc) and compare the
    hex sha with the Makefile build's. -> {cmake_sha256, parity, verify_log, status}. A refusal is returned, never raised."""
    from cmod.custom import cmod_engines as CE
    files = {f: open(os.path.join(path, f), 'rb').read() for f in sorted(os.listdir(path)) if os.path.isfile(os.path.join(path, f))}
    try:
        r = CE.run('cmake', ['-P', 'polari-build.cmake'], files, timeout=600)
    except Exception as e:  # noqa: BLE001 — the rung refused: said, not raised
        return {'cmake_sha256': '', 'parity': 'not-run', 'verify_log': 'refused: %s' % e, 'status': 'created'}
    hexb = (r.get('files') or {}).get('firmware.hex')
    log = ((r.get('stdout') or '') + '\n' + (r.get('stderr') or ''))[-1500:]
    if not (r.get('ok') and hexb):
        return {'cmake_sha256': '', 'parity': 'not-run', 'verify_log': 'cmake failed (%s): %s' % (r.get('how', '?'), log), 'status': 'refused',
                'why': 'the exported CMake build failed on %s' % r.get('how', '?')}
    s = _sha(hexb)
    parity = 'identical' if (makefile_sha and s == makefile_sha) else ('differs' if makefile_sha else 'not-run')
    open(os.path.join(path, 'firmware.hex'), 'wb').write(hexb)
    return {'cmake_sha256': s, 'parity': parity, 'verify_log': '%s via %s; sizes in log\n%s' % ('cmake ok', r.get('how', '?'), log), 'status': 'verified'}


def tarball(row):
    """The export's tar.gz bytes (rebuilt from the directory if the tar is gone)."""
    if os.path.isfile(row['tar_path']):
        return open(row['tar_path'], 'rb').read()
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode='w:gz') as tar:
        tar.add(row['path'], arcname=row['name'])
    return buf.getvalue()
