"""
@module cmod.custom.pin_config_gen

GENERATED `pin_config_init()` (ucd-0b, UNO_CORE_DEMO_PLAN.md §5f/§5g): the init-vs-runtime split's INIT half, written
in the FIXED ORDER his correction requires — DDR, PORT, EICRA, EIFR (clear pending, writing ones), EIMSK, PCMSKx,
PCICR, in that order; `sei()` stays in `main()` after every init, never here.

`render(solution_name, graph, manager=None)` reads `cmod.custom.claims.register_settings()` (the solution's own
RegisterSetting / RegisterFieldSetting rows — the PinClaims already turned into bits, §5g A) and writes TWO ordinary
avr-libc files, no Polari needed to build them:

  pin_config.h   one #define per claimed pin's register/bit fact the .c actually uses (derived from the SocPin +
                 RegisterField rows ucd-0a cited — never a bare bit number written into the .c) + the prototype.
  pin_config.c   `pin_config_init()`: for a register whose fields are all `rw`, a masked read-modify-write (bits
                 outside `write_mask` are left at the chip's reset value — said in a comment); for a register whose
                 fields are all `w1c` (EIFR/PCIFR), a PLAIN WRITE of the mask (a read-modify-write would clear every
                 OTHER pending flag too). A field whose access is anything else (`w-strobe`, `rw-toggle`, `r`) never
                 belongs in init — `GenRefused`, named. Every register write is preceded by a comment citing the
                 RegisterSetting (value/mask in binary) and, per field, the RegisterFieldSetting's value + meaning +
                 the PinClaim/PeripheralClaim + task + derivation rule that produced it — the line a novice reads to
                 see WHY.

Deterministic: no wall-clock timestamp in the file bytes (a render's `rendered_at` lives in the glue record only,
cmod.custom.glue — embedding it here would make every re-render "changed" and defeat `pol cmod conform`'s idempotence).
"""
import json

from cmod.custom import claims as C

GENERATOR = 'cmod.custom.pin_config_gen'

#: the fixed init order his correction requires (UNO_CORE_DEMO_PLAN.md §5f): DDR before PORT before EICRA before
#: EIFR (clear pending) before EIMSK before PCMSKx before PCICR. A register outside this list is not generated here
#: (claims.register_settings() only ever produces these — timers/USART/ADC stay in the hand-written HAL, named in
#: claims.py's own docstring).
_CATEGORY_ORDER = ('DDR', 'PORT', 'EICRA', 'EIFR', 'EIMSK', 'PCMSK', 'PCICR')
_ALLOWED_ACCESS = ('rw', 'w1c')


class GenRefused(ValueError):
    pass


def _category(regname):
    for i, cat in enumerate(_CATEGORY_ORDER):
        if regname.startswith(cat):
            return i
    raise GenRefused('pin_config_gen: register %s is outside the fixed init order (%s known) — claims.register_settings '
                      'should never produce it this slice' % (regname, ', '.join(_CATEGORY_ORDER)))


def _graph_board(graph, manager=None):
    """The graph's board, for the header comment only (never used to derive bits)."""
    if manager is not None:
        for r in (manager.objectTables or {}).get('CGraph', {}).values():
            if getattr(r, 'name', '') == graph:
                return getattr(r, 'board', '')
    from cmod.custom.graph_seed import seed_graph
    rows = seed_graph(graph)
    return (rows or {}).get('graph', {}).get('board', '')


def _macro_names(canon, regname):
    """(register_macro, bit_macro, width_macro) for one claimed pin's one register fact. DDR/PORT share one BIT
    macro per pin (the data-direction bit and the data bit are always the SAME bit n on AVR — `PIN_CONFIG_D13_BIT`);
    every other register (EICRA/EIFR/EIMSK/PCMSKk/PCICR) gets its OWN bit macro (its bit position is independent of
    the pin's DDR/PORT bit — e.g. D2 is DDRD/PORTD bit 2 but EICRA.ISC0 bit 0)."""
    for cat in ('DDR', 'PORT'):
        if regname.startswith(cat):
            reg_macro = 'PIN_CONFIG_%s_%s' % (canon, cat)
            bit_macro = 'PIN_CONFIG_%s_BIT' % canon
            return reg_macro, bit_macro, bit_macro + '_UNUSED_WIDTH'
    reg_macro = 'PIN_CONFIG_%s_%s' % (canon, regname)
    bit_macro = '%s_BIT' % reg_macro
    return reg_macro, bit_macro, '%s_WIDTH' % reg_macro


def _canon(field_setting):
    ref = field_setting.get('pin_claim') or field_setting.get('peripheral_claim') or ''
    return ref.split(':', 1)[1] if ':' in ref else (ref or 'X')


def _comment(what, solution_name, graph, board):
    return ('/*\n'
            ' * %s\n'
            ' *\n'
            ' * GENERATED by Polari (%s) from Firmware Solution %s, graph %s, board %s, at render time (the exact\n'
            ' * timestamp lives in the glue record, cmod/custom/glue_builds/%s.json — never in this file, so a\n'
            ' * re-render with nothing changed produces byte-identical output). EDIT THE MODEL (the pin claims /\n'
            ' * register settings), never this file. No Polari is needed to build it: pin_config_init() is ordinary\n'
            ' * avr-libc C, called once from main() before the hand-written HAL inits (POLARI_PIN_CONFIG=1 then\n'
            ' * disables those same DDR/PORT/EICRA/EIFR/EIMSK writes in hal.c so the two never race).\n'
            ' */\n' % (what, GENERATOR, solution_name, graph, board, graph))


def _plan(solution_name, graph, manager=None, overrides=None):
    """-> (ordered [ (RegisterSetting, [ (RegisterFieldSetting, RegisterField), ... ] ), ... ], defines[(macro, value,
    comment)]) — the fixed-order register writes and the header's #defines, BEFORE any text is rendered (so the
    selftest can drive this same plan directly for a synthetic settings list)."""
    gen = C.register_settings(solution_name, graph, manager=manager, overrides=overrides)
    return plan_from_rows(gen['RegisterSetting'], gen['RegisterFieldSetting'], manager=manager)


def plan_from_rows(register_settings, field_settings, manager=None):
    """The same plan, over an explicit {RegisterSetting, RegisterFieldSetting} rows list (what the live `claims`
    derivation produces, OR a synthetic list a test builds directly) — never re-derives claims itself."""
    tables = C._chain_tables(manager)
    fields = C._index(tables, 'RegisterField')
    by_rs = {}
    for fs in field_settings:
        by_rs.setdefault(fs['register_setting'], []).append(fs)

    def regname_of(rs):
        return rs['register'].rsplit(':', 1)[-1]

    init_rs = sorted((rs for rs in register_settings if rs.get('phase', 'init') == 'init'),
                      key=lambda rs: (_category(regname_of(rs)), regname_of(rs)))
    defines, seen = [], set()
    plan = []
    for rs in init_rs:
        regname = regname_of(rs)
        fs_rows = by_rs.get(rs['name'], [])
        if not fs_rows:
            raise GenRefused('%s has no RegisterFieldSetting rows behind it (internal — claims.register_settings is '
                              'inconsistent)' % rs['name'])
        entry = []
        total_value = total_mask = 0

        def by_bit(fs):
            fr = fields.get(fs['register_field'])
            if fr is None:
                raise GenRefused('%s: no RegisterField row %s (ucd-0a citation missing)' % (rs['name'], fs['register_field']))
            return fr['bit_lo']
        for fs in sorted(fs_rows, key=by_bit):
            fr = fields.get(fs['register_field'])
            access = fr['access']
            if access not in _ALLOWED_ACCESS:
                raise GenRefused('%s: field %s has access %r — pin_config_init only ever writes rw or w1c fields '
                                  '(w-strobe/rw-toggle/r never belong in init)' % (rs['name'], fs['register_field'], access))
            canon = _canon(fs)
            reg_macro, bit_macro, width_macro = _macro_names(canon, regname)
            width = fr['width']
            value_int = int(fs['value'], 2)
            width_mask = (1 << width) - 1
            if reg_macro not in seen:
                defines.append((reg_macro, regname, 'the %s register pin claim %s touches' % (regname, fs.get('pin_claim') or fs.get('peripheral_claim'))))
                seen.add(reg_macro)
            if bit_macro not in seen:
                defines.append((bit_macro, str(fr['bit_lo']), "%s.%s's low bit (from the SocPin/RegisterField rows, never a bare number)" % (regname, fr['field'])))
                seen.add(bit_macro)
            if width > 1 and width_macro not in seen:
                defines.append((width_macro, str(width), "%s.%s's bit width" % (regname, fr['field'])))
                seen.add(width_macro)
            total_value |= value_int << fr['bit_lo']
            total_mask |= width_mask << fr['bit_lo']
            entry.append({'field': fr['field'], 'value': fs['value'], 'meaning': fs.get('meaning') or '(no meaning cited)',
                          'pin_claim': fs.get('pin_claim') or '', 'peripheral_claim': fs.get('peripheral_claim') or '',
                          'task': fs.get('task') or '', 'rule': fs.get('rule') or '', 'access': access,
                          'reg_macro': reg_macro, 'bit_macro': bit_macro, 'width_macro': width_macro if width > 1 else None,
                          'value_int': value_int, 'width_mask': width_mask})
        rs_value = int(rs['value'], 16)
        rs_mask = int(rs['write_mask'], 16)
        if total_value != rs_value or total_mask != rs_mask:
            raise GenRefused('%s: the fields (value 0x%02X mask 0x%02X) do not reassemble the RegisterSetting\'s own '
                              '(value %s mask %s) — internal inconsistency, never silently papered over' % (rs['name'], total_value, total_mask, rs['value'], rs['write_mask']))
        plan.append({'register_setting': rs, 'regname': regname, 'fields': entry})
    return plan, defines


def _render_h(plan, defines, solution_name, graph, board):
    out = [_comment('pin_config.h — the pin claims\' register/bit facts, as #defines pin_config.c uses.', solution_name, graph, board),
           '#ifndef POLARI_PIN_CONFIG_H', '#define POLARI_PIN_CONFIG_H', '']
    if defines:
        out.append('/* one #define per claimed pin\'s register/bit fact pin_config.c uses — derived from the SocPin + ')
        out.append(' * RegisterField rows (board.custom.hardware_chain), never a bare bit number written below. */')
        for macro, value, why in defines:
            out.append('#define %-32s %-8s /* %s */' % (macro, value, why))
        out.append('')
    out += ['void pin_config_init(void);', '', '#endif /* POLARI_PIN_CONFIG_H */', '']
    return ('\n'.join(out) + '\n').encode()


def _render_c(plan, solution_name, graph, board):
    out = [_comment('pin_config.c — pin_config_init(): the fixed init order (DDR, PORT, EICRA, EIFR, EIMSK, PCMSKx, '
                     'PCICR); sei() stays in main(), after every init, never here.', solution_name, graph, board),
           '#include <avr/io.h>', '#include <stdint.h>', '', '#include "pin_config.h"', '',
           'void pin_config_init(void)', '{']
    if not plan:
        out.append('    /* this solution\'s claims produced no GPIO / external-interrupt / pin-change settings */')
    for item in plan:
        rs, regname, fields = item['register_setting'], item['regname'], item['fields']
        out.append('    /* %s = %s (write_mask %s)' % (rs['name'], rs['value_bits'], rs['write_mask']))
        for f in fields:
            claim = f['pin_claim'] or f['peripheral_claim']
            out.append('     *   %-8s = %-5s %s' % (f['field'], f['value'], '— %s · claim %s · task %s · rule %s'
                        % (f['meaning'], claim, f['task'], f['rule'])))
        out.append('     */')
        access_set = {f['access'] for f in fields}
        value_terms = ['((uint8_t)0x%02X << %s)' % (f['value_int'], f['bit_macro']) for f in fields]
        mask_terms = ['((uint8_t)0x%02X << %s)' % (f['width_mask'], f['bit_macro']) for f in fields]
        value_expr = ' | '.join(value_terms)
        mask_expr = ' | '.join(mask_terms)
        lhs = fields[0]['reg_macro']
        if access_set == {'w1c'}:
            out.append('    %s = (uint8_t)(%s);   /* plain write (access w1c): writing a one CLEARS that pending flag; a' % (lhs, value_expr))
            out.append('                                    read-modify-write would also clear every OTHER pending flag */')
        elif 'w1c' not in access_set:
            out.append('    %s = (uint8_t)((%s & (uint8_t)~(%s)) | (%s));   /* bits outside write_mask %s keep the chip\'s' % (lhs, lhs, mask_expr, value_expr, rs['write_mask']))
            out.append('                                    reset value */')
        else:
            raise GenRefused('%s mixes w1c with rw fields in one register — not generated this slice' % rs['name'])
        out.append('')
    if out[-1] == '':
        out.pop()
    out += ['}', '']
    return ('\n'.join(out) + '\n').encode()


def render(solution_name, graph, manager=None, overrides=None):
    """{'pin_config.h': bytes, 'pin_config.c': bytes} for one FirmwareSolution's claims over one graph."""
    plan, defines = _plan(solution_name, graph, manager=manager, overrides=overrides)
    board = _graph_board(graph, manager)
    return {'pin_config.h': _render_h(plan, defines, solution_name, graph, board),
            'pin_config.c': _render_c(plan, solution_name, graph, board)}
