"""
@cross-cutting
@module islemesh.islemesh_mock

The MOCK isle network (Dustin 2026-08-07): realistic payloads for
every ingest endpoint, ALWAYS declaring `mock_network: true` — the
flag real isle data never carries, which the summary turns into the
large top-of-page banner.

The mock mirrors the REAL target topology (pol-core / isle-core /
econ-core + a guest device, the apps the arc will actually
converge) so the visualization pre-figures reality: when real
ingests replace these rows, the picture should look the same —
minus the banner.

Fragments are REAL nginx text run through the REAL parser
(islemesh_parse) — the mock exercises the exact pipeline live data
will use. Stdlib-only.

@consumers
  - islemesh.islemesh_api (POST /api/islemesh/mock)
  - islemesh.selftest_islemesh (parser fixtures)
"""

_FRAGMENT_POLARI = """
# generated by isle-agent (mock) — polari.conf
upstream polari_backend {
    server prf-proxy:443;
}
server {
    listen 80;
    server_name polari.isle api.polari.isle;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;
    server_name polari.isle;
    ssl_certificate /etc/nginx/ssl/certs/polari.isle.crt;
    ssl_certificate_key /etc/nginx/ssl/keys/polari.isle.key;
    location / {
        proxy_pass https://polari_backend;
    }
}
server {
    listen 443 ssl http2;
    server_name api.polari.isle;
    ssl_certificate /etc/nginx/ssl/certs/polari.isle.crt;
    ssl_certificate_key /etc/nginx/ssl/keys/polari.isle.key;
    location / {
        proxy_pass https://polari_backend;
    }
}
"""

_FRAGMENT_SAMPLE = """
# generated by isle-agent (mock) — sample-app.conf
upstream sample-app_backend {
    server isle-sample-app:8080;
}
server {
    listen 443 ssl http2;
    server_name sample-app.isle;
    ssl_certificate /etc/nginx/ssl/certs/sample-app.isle.crt;
    ssl_certificate_key /etc/nginx/ssl/keys/sample-app.isle.key;
    ssl_verify_client on;
    location / {
        proxy_pass http://sample-app_backend;
    }
}
"""

_FRAGMENT_MANAGER = """
# generated by isle-agent (mock) — isle-manager.conf
server {
    listen 80;
    server_name manager.isle;
    location / {
        proxy_pass http://127.0.0.1:7300;
    }
}
"""


def mock_ingests():
    """Ordered (endpoint_suffix, payload) pairs — every payload
    carries mock_network=True. Post them in order and the page
    fills in: devices → registries → fragments."""
    device = [
        ('device', {
            'device': 'pol-core', 'mock_network': True,
            'facts': {'isle_name': 'pol-core.isle',
                      'machine_name': 'pol-core',
                      'agent_mode': 'remote',
                      'agent_present': True,
                      'connectivity_mode': 'dual-home',
                      'notes': 'mock: swarm manager, joins by '
                               'cable (eno1)'},
            'uplinks': [{'interface': 'eno1', 'kind': 'ethernet',
                         'link_up': True, 'latency_ms': 0.9,
                         'jitter_ms': 0.1, 'loss_pct': 0.0,
                         'measured_at': 'mock'}]}),
        ('device', {
            'device': 'isle-core', 'mock_network': True,
            'facts': {'isle_name': 'isle-core.isle',
                      'machine_name': 'isle-core',
                      'agent_mode': 'core',
                      'agent_present': True,
                      'hosts_router': True,
                      'router_running': True,
                      'connectivity_mode': 'dual-home',
                      'notes': 'mock: network authority, router '
                               'VM host'},
            'uplinks': [{'interface': 'enp1s0',
                         'kind': 'ethernet', 'link_up': True,
                         'latency_ms': 0.8, 'jitter_ms': 0.1,
                         'loss_pct': 0.0, 'measured_at': 'mock'}]}),
        ('device', {
            'device': 'econ-core', 'mock_network': True,
            'facts': {'isle_name': 'econ-core.isle',
                      'machine_name': 'econ-core',
                      'agent_mode': 'remote',
                      'agent_present': True,
                      'connectivity_mode': 'dual-home',
                      'notes': 'mock: first wifi-uplink member'},
            'uplinks': [{'interface': 'wlan-isle', 'kind': 'wifi',
                         'link_up': True, 'latency_ms': 4.2,
                         'jitter_ms': 1.8, 'loss_pct': 0.3,
                         'measured_at': 'mock'}]}),
        ('device', {
            'device': 'guest-laptop', 'mock_network': True,
            'facts': {'isle_name': 'guest-laptop.isle',
                      'agent_mode': 'remote',
                      'agent_present': True,
                      'connectivity_mode': 'sole-isle',
                      'notes': 'mock: sole-isle device — .isle '
                               'only, no internet by design'},
            'uplinks': [{'interface': 'wlan0', 'kind': 'usb-wifi',
                         'link_up': True, 'latency_ms': 6.1,
                         'jitter_ms': 2.4, 'loss_pct': 0.8,
                         'measured_at': 'mock'}]}),
    ]
    registry = [
        ('registry', {
            'device': 'isle-core', 'mock_network': True,
            'registry': {'apps': {
                'polari': {
                    'domain': 'polari.isle',
                    'availability_mode': 'always-available',
                    'status': 'up',
                    'updated_at': 'mock',
                    'modes': ['isle'],
                    'services': [
                        {'name': 'backend', 'subdomain': 'api',
                         'container': 'polari-node_backend',
                         'port': 8443, 'protocol': 'https'},
                        {'name': 'frontend', 'subdomain': '',
                         'container': 'polari-node_frontend',
                         'port': 443, 'protocol': 'https'}]},
                'sample-app': {
                    'domain': 'sample-app.isle',
                    'availability_mode': 'on-demand',
                    'status': 'down',
                    'updated_at': 'mock',
                    'modes': ['isle'],
                    'services': [
                        {'name': 'sample', 'subdomain': '',
                         'container': 'isle-sample-app',
                         'port': 8080, 'protocol': 'http'}]},
                'isle-manager': {
                    'domain': 'manager.isle',
                    'availability_mode': 'always-available',
                    'status': 'up',
                    'updated_at': 'mock',
                    'modes': ['local', 'isle'],
                    'services': [
                        {'name': 'ui', 'subdomain': '',
                         'container': 'isle-manager',
                         'port': 7300, 'protocol': 'http'}]},
            }}}),
    ]
    fragments = [
        ('fragments', {
            'device': 'isle-core', 'mock_network': True,
            'fragments': {'polari.conf': _FRAGMENT_POLARI,
                          'sample-app.conf': _FRAGMENT_SAMPLE,
                          'isle-manager.conf': _FRAGMENT_MANAGER}}),
        ('fragments', {
            'device': 'pol-core', 'mock_network': True,
            'fragments': {'polari.conf': _FRAGMENT_POLARI}}),
    ]
    return device + registry + fragments


def mock_realizations():
    """MeshAppRealization row dicts (model-owned — no ingest
    endpoint writes these; the mock endpoint seeds them so the
    one-app-many-deliveries idea is visible on day one)."""
    return [
        {'name': 'polari@website', 'app_name': 'polari',
         'kind': 'website', 'url': 'https://polari.isle',
         'status': 'up', 'is_mock': True},
        {'name': 'polari@shell', 'app_name': 'polari',
         'kind': 'shell', 'url': 'https://polari.isle',
         'package_kind': 'app-deb', 'status': 'installed',
         'is_mock': True},
        {'name': 'sample-app@website', 'app_name': 'sample-app',
         'kind': 'website', 'url': 'https://sample-app.isle',
         'status': 'down', 'is_mock': True},
        {'name': 'isle-manager@local-stub',
         'app_name': 'isle-manager', 'kind': 'local-stub',
         'url': 'http://manager.isle',
         'package_kind': 'app-deb', 'status': 'installed',
         'is_mock': True},
        {'name': 'hw-bridge@kvm', 'app_name': 'hw-bridge',
         'kind': 'kvm', 'url': 'https://hw-bridge.isle',
         'hardware_pin_device': 'isle-core',
         'status': 'planned',
         'notes': 'mock: USB device pinned to isle-core — the '
                  'mover must refuse to move this one',
         'is_mock': True},
    ]
