"""
@module islemesh.islemesh_catalog

Catalog seed + install-plan logic for the general isle app store
(handoff §20.1/§20.3). The catalog is BROWSABLE ROWS; installation
runs on the host (`isle store install`), so this module only
produces the PLAN — the ordered host commands an install would run
— never executes docker itself (the mover-on-host discipline).

Entries model the two PROVEN variants: mesh-apps (the
`isle app deploy` pipeline) and polari-apps (the shared-shell
launcher .deb). One kind → one install-plan builder.

@consumers
  - islemesh.islemesh_api (/api/islemesh/catalog*)
  - polari-cli / isle store (reads the plan, runs it on the host)
  - islemesh.selftest_islemesh
"""

#: Seed listings — the apps the arc has actually stood up, so the
#: store shows a real catalog from day one (never seeded is_mock).
SEED_CATALOG = [
    {
        'name': 'polari', 'title': 'Polari',
        'description': 'The Polari research OS, as a native-feeling '
                       'shell over its .isle web UI.',
        'kind': 'polari-app', 'source_ref': 'https://polari.isle',
        'provides_engine': '', 'category': 'platform',
        'source': 'official',
    },
    {
        'name': 'whoami', 'title': 'whoami (demo)',
        'description': 'A tiny HTTP echo — the arbitrary-compose '
                       'app that proves any container becomes an '
                       '.isle app.',
        'kind': 'mesh-app', 'source_ref': 'traefik/whoami:latest',
        'service': 'whoami', 'port': 80, 'category': 'demo',
        'source': 'official',
    },
    {
        'name': 'odoo', 'title': 'Odoo (business ops)',
        'description': 'Odoo ERP deployed to the isle and wired as '
                       'a Polari business-ops ENGINE automatically.',
        'kind': 'mesh-app', 'source_ref': 'odoo:16',
        'service': 'odoo', 'port': 8069,
        'provides_engine': 'business-ops', 'category': 'engine',
        'source': 'official',
    },
]


def install_plan(entry):
    """Build the ordered host commands to install one entry (a dict
    of its fields). Returns {'ok', 'steps': [cmd,...], 'note'} — the
    isle CLI runs `steps` on the host. No side effects here."""
    kind = entry.get('kind', '')
    name = entry.get('name', '')
    ref = entry.get('source_ref', '')
    if kind == 'mesh-app':
        # arbitrary compose/image → the deploy pipeline
        args = ['isle app deploy %s' % name]
        # a bare image ref gets a one-service compose generated by
        # the CLI; a path/url is passed through --compose
        if '/' in ref and not ref.endswith(('.yml', '.yaml')) \
                and '://' not in ref:
            args.append('--image %s' % ref)   # CLI synthesizes compose
        else:
            args.append('--compose %s' % ref)
        if entry.get('service'):
            args.append('--service %s' % entry['service'])
        if entry.get('port'):
            args.append('--port %d' % entry['port'])
        if entry.get('domain'):
            args.append('--domain %s' % entry['domain'])
        if entry.get('provides_engine'):
            args.append('--engine %s' % entry['provides_engine'])
        return {'ok': True, 'steps': [' '.join(args)],
                'note': 'deploys %s as an .isle app%s' % (
                    name, ' (+ engine %s)' % entry['provides_engine']
                    if entry.get('provides_engine') else '')}
    if kind == 'polari-app':
        # shared-shell launcher .deb over the app's .isle URL
        return {'ok': True, 'steps': [
            'isle shell launcher --name %s --url %s '
            '--ca /etc/isle-mesh/ca/isle-root.crt' % (name, ref),
            'sudo apt install ./%s-app-%s_*.deb' % ('isle', name),
        ], 'note': 'installs a native launcher (shares '
                   'polari-shell-core) for %s' % ref}
    if kind == 'polari-module':
        return {'ok': True, 'steps': [
            'sudo apt install polari-module-%s' % (ref or name),
        ], 'note': 'installs the %s module into the local instance'
                   % (ref or name)}
    return {'ok': False, 'steps': [],
            'note': 'unknown catalog kind %r' % kind}
