"""
@module nutrition.today_seed

N2 — the TODAY page (`mealplan/today?object=<person>`) as data:

  TableDefinitions   the day list (CalendarEvent), the work ledger
                     (WorkLedger), the durations (DurationObservation)
  DisplayDefinition  headline reading over /api/mealplanning/today/
                     {person} (next up + counts + the day's lines), the
                     mealplan-week calendar in its day-list view for the
                     person, the "Mark done" FORM, the ledger + durations
                     tables — every item a configured display, no JSON.
  AnalysisDefinitions today-person-day / today-mark-done
  SolutionDefinitions today-mark-done-form (FormSubscription → the
                     proposal → WorkLedger row → DurationObservation row
                     (only with actual minutes) → ModifyEvent status done
                     → refreshDisplay) and today-done-to-ledger (the
                     trigger's: proposal → WorkLedger row, deduped)
  EventTrigger       today-done-to-ledger — ANY CalendarEvent reaching
                     status == done (CRUD dialog included) credits the
                     ledger once.

Wired by the orchestrator (mealplan_pages_seed upsert + polariServer).
"""

import json

from polariApiServer.mealplan_pages_seed import (
    _ecal, _etable, _form, _sapi, _table_def,
)
from polariApiServer.module_pages_seed import _page, _row
from polariNoCode import graph_builder as gb
from nutrition.calendar_seed import message_call, refresh_with_message

_MP = '/api/mealplanning'
_PROV = 'n2-today'

SEED_TODAY_TABLES = [
    _table_def('today-day-list', 'CalendarEvent',
               'Today\'s events', 'One person\'s day: eating, prep, packing, '
               'cleanup, purchases — edit status here or use Mark done.',
               [('span', 'When (start/end)', 'str', 240),
                ('title', 'Event', 'str', 240),
                ('category', 'Category', 'str', 110),
                ('status', 'Status', 'str', 90),
                ('person_name', 'Person', 'str', 120),
                ('linked_name', 'Linked to', 'str', 170),
                ('generated_by', 'Generated by', 'str', 170)],
               defaults=False),
    _table_def('today-ledger', 'WorkLedger',
               'Work ledger', 'What actually happened: minutes of work by '
               'person and type (planned minutes are labelled priors until '
               'an actual number is given).',
               [('date', 'Date', 'str', 110),
                ('person_name', 'Person', 'str', 120),
                ('workload_type', 'Work', 'str', 120),
                ('minutes', 'Minutes', 'float', 90),
                ('event_name', 'Event', 'str', 220),
                ('source', 'Source', 'str', 110),
                ('notes', 'Label', 'str', 240)],
               defaults=False),
    _table_def('today-durations', 'DurationObservation',
               'How long things took', 'Answered "how long did it take" rows — '
               'the refinement loop\'s facts (speed factors are proposed from '
               'these, never below the safety floor).',
               [('date', 'Date', 'str', 110),
                ('person_name', 'Person', 'str', 120),
                ('kind', 'Kind', 'str', 110),
                ('method_name', 'Method', 'str', 150),
                ('observed_min', 'Observed min', 'float', 110),
                ('entry_name', 'Meal entry', 'str', 200),
                ('source', 'Source', 'str', 100)],
               defaults=False),
]

SEED_TODAY_GRAPHS = []


def _mark_done_form(item_id, index, segments):
    return _form(
        item_id, index, segments,
        'Mark done — the event goes to done, the ledger gets the minutes '
        '(planned unless you say how long it took), and an answered '
        'duration becomes an observation',
        'today-mark-done-form', [
            ('event', 'Event name', 'string', '',
             'the CalendarEvent name (see the day list: e.g. mealprep-…)', True),
            ('person', 'Person', 'string', '{object}', 'who did it', True),
            ('minutes_actual', 'How long did it take? (minutes, optional)', 'number', '',
             'blank = the planned minutes are credited, labelled as a prior', False),
        ], submit_label='Mark done')


SEED_TODAY_PAGE_DISPLAYS = [
    _page(
        'mealplan-today', 'mealplan/today',
        'N2: ONE person\'s day — open with ?object=<person>. What is next, '
        'how much is done, the day\'s eating / prep / packing / cleanup / '
        'purchase lines in time order with a safety note wherever a step '
        'method carries a hazard tag, the day-list calendar, the Mark done '
        'form (done → WorkLedger; an answered duration → DurationObservation), '
        'and the ledger + durations tables.',
        'PersonProfile',
        [
            _row(0, [
                _sapi('td-headline', 0, 12,
                      'Today — {object} (next up, done / planned, the day in order)',
                      f'{_MP}/today/{{object}}', hide='ledger'),
            ]),
            _row(1, [
                _ecal('td-day-cal', 0, 12, 'Your day — {object} (mealplan-week, day list)',
                      'mealplan-week', person='{object}', view='listDay'),
            ], min_height=420),
            _row(2, [
                _mark_done_form('td-mark-done', 0, 6),
                _etable('td-day-list', 1, 6, 'Today\'s events — {object}',
                        'today-day-list', 'CalendarEvent', 'person_name', '{object}'),
            ]),
            _row(3, [
                _etable('td-ledger', 0, 6, 'Work ledger — {object}',
                        'today-ledger', 'WorkLedger', 'person_name', '{object}'),
                _etable('td-durations', 1, 6, 'How long things took — {object}',
                        'today-durations', 'DurationObservation', 'person_name', '{object}'),
            ]),
        ]),
]

SEED_TODAY_ANALYSES = [
    {'name': 'today-person-day', 'domain': 'nutrition',
     'callable_ref': 'nutrition.today_analysis:person_day',
     'description': 'One person\'s day: CalendarEvent lines in time order (safety notes '
                    'from hazard tags), next up, done/planned counts, the ledger so far.',
     'params_json': json.dumps({'person': 'PersonProfile.name', 'day': 'ISO date (default today)'}),
     'enabled': True, 'is_prior': True, 'provenance_id': _PROV},
    {'name': 'today-mark-done', 'domain': 'nutrition',
     'callable_ref': 'nutrition.today_analysis:mark_done_proposal',
     'description': 'Mark an event done: status → done, ONE WorkLedger row (planned minutes '
                    'labelled unless actual minutes given), a DurationObservation only with '
                    'actual minutes; deduped by ledger-<event>.',
     'params_json': json.dumps({'event_name': 'CalendarEvent.name', 'person': 'PersonProfile.name',
                                'minutes_actual': 'minutes (optional)'}),
     'enabled': True, 'is_prior': True, 'provenance_id': _PROV},
]


def _solution(name, definition, description):
    return {'name': name, 'function_name': name.replace('-', '_'),
            'target_runtime': 'python_backend',
            'definition': json.dumps(definition),
            'contract_json': json.dumps({'description': description,
                                         'executionRights': 'definer'})}


#: the FORM path: writes FIRST (ledger with the given minutes, the
#: observation only when minutes were given), THEN status → done — so
#: the object trigger that fires on the status change finds the ledger
#: row already there and dedupes instead of overwriting the actual
#: minutes with the planned prior.
_MARK_DONE_PARAMS = {'event_name': gb.var_src('event'), 'person': gb.var_src('person'),
                     'minutes_actual': gb.var_src('minutes_actual')}

#: the three picks (ledger rows, observation rows, the message) are all
#: taken BEFORE any write, so the message judges "already had N min —
#: kept" against the rows as they stood on submit.
MARK_DONE_FORM_SOLUTION = _solution(
    'today-mark-done-form',
    gb.solution(
        'today-mark-done-form',
        gb.node('Start', 'FormSubscription', {}, outs=[['ProposeLedger']]),
        gb.node('ProposeLedger', 'AnalysisCall',
                {'analysis': 'today-mark-done', 'params': _MARK_DONE_PARAMS,
                 'pick': 'ledgerProposals', 'resultVariable': 'ledgerProposals'},
                outs=[['ProposeObservation']]),
        gb.node('ProposeObservation', 'AnalysisCall',
                {'analysis': 'today-mark-done', 'params': _MARK_DONE_PARAMS,
                 'pick': 'observationProposals', 'resultVariable': 'observationProposals'},
                outs=[['Message']]),
        message_call('Message', 'today-mark-done', _MARK_DONE_PARAMS, 'WriteLedger'),
        gb.node('WriteLedger', 'GenerateEvent',
                {'targetClassName': 'WorkLedger', 'eventsFrom': gb.var_src('ledgerProposals'),
                 'dedupeBy': 'name', 'fields': {}, 'resultVariable': 'ledgerRow'},
                outs=[['WriteObservation']]),
        gb.node('WriteObservation', 'GenerateEvent',
                {'targetClassName': 'DurationObservation',
                 'eventsFrom': gb.var_src('observationProposals'),
                 'dedupeBy': 'name', 'fields': {}, 'resultVariable': 'observationRow'},
                outs=[['MarkDone']]),
        gb.node('MarkDone', 'ModifyEvent',
                {'targetClassName': 'CalendarEvent', 'instanceRef': gb.var_src('event'),
                 'fields': {'status': 'done'}}, outs=[['Refresh']]),
        refresh_with_message({'event': gb.var_src('event'),
                              'ledger': gb.var_src('ledgerRowBatch'),
                              'observations': gb.var_src('observationRowBatch')}),
    ),
    'Mark an event done: ledger row (actual or planned minutes, labelled), duration '
    'observation only with actual minutes, then status → done; refresh the page and '
    'say what happened ("Marked … done; N min to the ledger").')

#: the TRIGGER path: any CalendarEvent that reaches status == done (the
#: CRUD dialog, a drag, another solution) credits the ledger ONCE with
#: the planned minutes (labelled prior) — dedupeBy name.
DONE_TO_LEDGER_SOLUTION = _solution(
    'today-done-to-ledger',
    gb.solution(
        'today-done-to-ledger',
        gb.entry('Start', nxt='Propose'),
        gb.node('Propose', 'AnalysisCall',
                {'analysis': 'today-mark-done',
                 'params': {'event_name': gb.var_src('instanceName'),
                            'person': gb.var_src('instance.person_name')},
                 'pick': 'ledgerProposals', 'resultVariable': 'ledgerProposals'},
                outs=[['WriteLedger']]),
        gb.node('WriteLedger', 'GenerateEvent',
                {'targetClassName': 'WorkLedger', 'eventsFrom': gb.var_src('ledgerProposals'),
                 'dedupeBy': 'name', 'fields': {}, 'resultVariable': 'ledgerRow'},
                outs=[['Emit']]),
        gb.node('Emit', 'EmitEvent',
                {'eventName': 'work-ledger-written',
                 'payload': {'event': gb.var_src('instanceName'),
                             'ledger': gb.var_src('ledgerRowBatch')}}),
    ),
    'When a CalendarEvent is marked done by ANY path: one WorkLedger row with the '
    'planned minutes (labelled prior), deduped by ledger-<event>.')

SEED_TODAY_SOLUTIONS = [MARK_DONE_FORM_SOLUTION, DONE_TO_LEDGER_SOLUTION]

SEED_TODAY_TRIGGERS = [
    {'name': 'today-done-to-ledger',
     'description': 'A CalendarEvent reaching status == done (edit dialog, drag, a solution) '
                    'credits the WorkLedger once — the auto-write TESTING_OWED §6 owed.',
     'enabled': True, 'source_kind': 'object',
     'source_json': json.dumps({'class': 'CalendarEvent', 'operations': ['create', 'update'],
                                'fieldFilter': {'status': 'done'}}),
     'solution_name': 'today-done-to-ledger',
     # deliberately EMPTY: inputs_json wins over the payload, and the
     # payload's instanceName / instance.person_name ARE the inputs.
     'inputs_json': json.dumps({}),
     'cooldown_s': 0.0, 'max_depth': 8, 'run_as': 'definer',
     'is_prior': True, 'provenance_id': _PROV},
]
