"""
@module materials_science.materials_science_basis

The INDEX of materials-science rows (design §7): every class lives in its
own file under objects/ (the hand-written taxonomy); this file re-exports
them so `from materials_science.materials_science_basis import X` and the
manifest's class list have one place to look. Nothing is defined here.
"""
from materials_science.objects.material import Material  # noqa: F401
from materials_science.objects.materialProperty import MaterialProperty  # noqa: F401
from materials_science.objects.materialPurpose import MaterialPurpose  # noqa: F401
from materials_science.objects.materialRelatedDevice import MaterialRelatedDevice  # noqa: F401
from materials_science.objects.materialResolution import MaterialResolution  # noqa: F401
from materials_science.objects.dataProvenance.dataProvenance import DataProvenance  # noqa: F401
from materials_science.objects.dataProvenance.dataSource import DataSource  # noqa: F401
from materials_science.objects.resolutions.resolutionCategory import ResolutionCategory  # noqa: F401
from materials_science.objects.resolutions.quantum.densityFunctionalMaterial import DensityFunctionalMaterial  # noqa: F401
from materials_science.objects.resolutions.quantum.quantumResolution import QuantumResolution  # noqa: F401
from materials_science.objects.resolutions.mesoscale.coarsegrainedMolecularDynamicsMaterial import CoarsegrainedMolecularDynamicsMaterial  # noqa: F401
from materials_science.objects.resolutions.mesoscale.mesoscaleResolution import MesoscaleResolution  # noqa: F401
from materials_science.objects.resolutions.continuum.chosenMaterial import ChosenMaterial  # noqa: F401
from materials_science.objects.resolutions.continuum.consistentFiniteElementMaterial import ConsistentFiniteElementMaterial  # noqa: F401
from materials_science.objects.resolutions.continuum.continuumResolution import ContinuumResolution  # noqa: F401
from materials_science.objects.resolutions.continuum.rangeMaterial import RangeMaterial  # noqa: F401
from materials_science.objects.resolutions.continuum.stochasticFiniteElementMaterial import StochasticFiniteElementMaterial  # noqa: F401
from materials_science.objects.resolutions.experimental.experimentalResolution import ExperimentalResolution  # noqa: F401
from materials_science.objects.resolutions.experimental.rawExperimentalMaterial import RawExperimentalMaterial  # noqa: F401
from materials_science.objects.resolutions.experimental.rulesOfMixturesExperimentalMaterial import RulesOfMixturesExperimentalMaterial  # noqa: F401
from materials_science.objects.resolutions.atomistic.atomisticResolution import AtomisticResolution  # noqa: F401
from materials_science.objects.resolutions.atomistic.molecularDynamicsMaterial import MolecularDynamicsMaterial  # noqa: F401
from materials_science.objects.materialSourcing.commercialSourcing import CommercialSourcing  # noqa: F401
from materials_science.objects.materialSourcing.materialSourcing import MaterialSourcing  # noqa: F401
from materials_science.objects.materialSourcing.naturalSourcing import NaturalSourcing  # noqa: F401
from materials_science.objects.materialSourcing.openSourceLocalSourcing import OpenSourceLocalSourcing  # noqa: F401
from materials_science.objects.referenceMaterials.propertyValueSource import PropertyValueSource  # noqa: F401
from materials_science.objects.referenceMaterials.referenceMaterial import ReferenceMaterial  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.abs import ABS  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.nylon import Nylon  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.petg import PETG  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.pha import PHA  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.pla import PLA  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.printableReferenceMaterial import PrintableReferenceMaterial  # noqa: F401
from materials_science.objects.referenceMaterials.threeDimensionalPrintable.tpu import TPU  # noqa: F401
from materials_science.objects.materialAdditives.additiveCompatibility import AdditiveCompatibility  # noqa: F401
from materials_science.objects.materialAdditives.compatibilizer import Compatibilizer  # noqa: F401
from materials_science.objects.materialAdditives.materialAdditive import MaterialAdditive  # noqa: F401
from materials_science.objects.materialAdditives.propertyEffect import PropertyEffect  # noqa: F401
from materials_science.objects.formulation.formulation import Formulation  # noqa: F401
from materials_science.objects.formulation.formulationComponent import FormulationComponent  # noqa: F401
from materials_science.objects.formulation.formulationIntent import FormulationIntent  # noqa: F401
from materials_science.objects.properties.propertyCategory import PropertyCategory  # noqa: F401
from materials_science.objects.properties.thermal.thermalProperty import ThermalProperty  # noqa: F401
from materials_science.objects.properties.thermal.glassTransition.dmaGlassTransitionMeasurement import DMAGlassTransitionMeasurement  # noqa: F401
from materials_science.objects.properties.thermal.glassTransition.glassTransition import GlassTransition  # noqa: F401
from materials_science.objects.properties.thermal.glassTransition.glassTransitionTemp import GlassTransitionTemp  # noqa: F401
from materials_science.objects.properties.thermal.meltingPoint.dscMeltingMeasurement import DSCMeltingMeasurement  # noqa: F401
from materials_science.objects.properties.thermal.meltingPoint.meltingPoint import MeltingPoint  # noqa: F401
from materials_science.objects.properties.thermal.meltingPoint.meltingPointValue import MeltingPointValue  # noqa: F401
from materials_science.objects.properties.thermal.smokingPoint.smokingPoint import SmokingPoint  # noqa: F401
from materials_science.objects.properties.thermal.smokingPoint.smokingPointMeasurement import SmokingPointMeasurement  # noqa: F401
from materials_science.objects.properties.thermal.smokingPoint.smokingPointValue import SmokingPointValue  # noqa: F401
from materials_science.objects.properties.thermal.thermalExpansion.coefficientOfThermalExpansion import CoefficientOfThermalExpansion  # noqa: F401
from materials_science.objects.properties.thermal.thermalExpansion.thermalExpansion import ThermalExpansion  # noqa: F401
from materials_science.objects.properties.thermal.thermalExpansion.tmaMeasurement import TMAMeasurement  # noqa: F401
from materials_science.objects.properties.surface.surfaceProperty import SurfaceProperty  # noqa: F401
from materials_science.objects.properties.surface.liquidSurfaceTension.liquidSurfaceTension import LiquidSurfaceTension  # noqa: F401
from materials_science.objects.properties.surface.liquidSurfaceTension.surfaceTensionValue import SurfaceTensionValue  # noqa: F401
from materials_science.objects.properties.surface.liquidSurfaceTension.wilhelmyMeasurement import WilhelmyMeasurement  # noqa: F401
from materials_science.objects.properties.surface.solidSurfaceEnergy.contactAngleMeasurement import ContactAngleMeasurement  # noqa: F401
from materials_science.objects.properties.surface.solidSurfaceEnergy.criticalSurfaceTension import CriticalSurfaceTension  # noqa: F401
from materials_science.objects.properties.surface.solidSurfaceEnergy.solidSurfaceEnergy import SolidSurfaceEnergy  # noqa: F401
from materials_science.objects.properties.physical.specificGravity.densityMeterMeasurement import DensityMeterMeasurement  # noqa: F401
from materials_science.objects.properties.physical.specificGravity.hydrometerMeasurement import HydrometerMeasurement  # noqa: F401
from materials_science.objects.properties.physical.specificGravity.pycnometerMeasurement import PycnometerMeasurement  # noqa: F401
from materials_science.objects.properties.physical.specificGravity.referentialSpecificGravity import ReferentialSpecificGravity  # noqa: F401
from materials_science.objects.properties.physical.specificGravity.specificGravity import SpecificGravity  # noqa: F401
from materials_science.objects.properties.rheological.rheologicalProperty import RheologicalProperty  # noqa: F401
from materials_science.objects.properties.rheological.elasticity.dmaMeasurement import DMAMeasurement  # noqa: F401
from materials_science.objects.properties.rheological.elasticity.elasticity import Elasticity  # noqa: F401
from materials_science.objects.properties.rheological.elasticity.rheometerMeasurement import RheometerMeasurement  # noqa: F401
from materials_science.objects.properties.rheological.elasticity.storageModulus import StorageModulus  # noqa: F401
from materials_science.objects.properties.rheological.meltFlowIndex.meltFlowIndex import MeltFlowIndex  # noqa: F401
from materials_science.objects.properties.rheological.meltFlowIndex.mfiMeasurement import MFIMeasurement  # noqa: F401
from materials_science.objects.properties.rheological.meltFlowIndex.mfiValue import MFIValue  # noqa: F401
from materials_science.objects.properties.rheological.viscosity.krebsViscosity import KrebsViscosity  # noqa: F401
from materials_science.objects.properties.rheological.viscosity.stormerViscosity import StormerViscosity  # noqa: F401
from materials_science.objects.properties.rheological.viscosity.viscosity import Viscosity  # noqa: F401
from materials_science.objects.properties.mechanical.mechanicalProperty import MechanicalProperty  # noqa: F401
from materials_science.objects.properties.mechanical.hardness.hardness import Hardness  # noqa: F401
from materials_science.objects.properties.mechanical.hardness.hardnessScale import HardnessScale  # noqa: F401
from materials_science.objects.properties.mechanical.hardness.shoreMeasurement import ShoreMeasurement  # noqa: F401
from materials_science.objects.properties.mechanical.tensileStrength.tensileMeasurement import TensileMeasurement  # noqa: F401
from materials_science.objects.properties.mechanical.tensileStrength.tensileStrength import TensileStrength  # noqa: F401
from materials_science.objects.properties.mechanical.tensileStrength.ultimateTensileStrength import UltimateTensileStrength  # noqa: F401
from materials_science.objects.targetProfiles.propertyTarget import PropertyTarget  # noqa: F401
from materials_science.objects.targetProfiles.targetMaterialProfile import TargetMaterialProfile  # noqa: F401
from materials_science.objects.rawMaterials.rawMaterial import RawMaterial  # noqa: F401
from materials_science.objects.purposes.purposeCategory import PurposeCategory  # noqa: F401
from materials_science.objects.purposes.cncMachinable.cncMachinable import CNCMachinable  # noqa: F401
from materials_science.objects.purposes.threeDimensionalPrintable.threeDimensionalPrintable import ThreeDimensionalPrintable  # noqa: F401
from materials_science.objects.purposes.moldFabrication.moldFabricationPurpose import MoldFabricationPurpose  # noqa: F401
from materials_science.objects.purposes.moldFabrication.threeDimensionalPrintedMold.fdmPrintedMoldMaterial import FDMPrintedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.threeDimensionalPrintedMold.slaPrintedMoldMaterial import SLAPrintedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.threeDimensionalPrintedMold.slsPrintedMoldMaterial import SLSPrintedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.threeDimensionalPrintedMold.threeDimensionalPrintedMoldMaterial import ThreeDimensionalPrintedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.cncMachinedMold.cncMachinedMoldMaterial import CNCMachinedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.cncMachinedMold.milledMoldMaterial import MilledMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.cncMachinedMold.turnedMoldMaterial import TurnedMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.geopolymerConcreteMold.geopolymerConcreteMoldMaterial import GeopolymerConcreteMoldMaterial  # noqa: F401
from materials_science.objects.purposes.moldFabrication.geopolymerConcreteMold.geopolymerThermalResistantConcreteMoldMaterial import GeopolymerThermalResistantConcreteMoldMaterial  # noqa: F401
from materials_science.objects.devices.deviceCategory import DeviceCategory  # noqa: F401
from materials_science.objects.devices.cncLathes.cncLathe import CNCLathe  # noqa: F401
from materials_science.objects.devices.materialTestingDevices.hardnessTester import HardnessTester  # noqa: F401
from materials_science.objects.devices.materialTestingDevices.materialTestingDevice import MaterialTestingDevice  # noqa: F401
from materials_science.objects.devices.materialTestingDevices.tensileTestingMachine import TensileTestingMachine  # noqa: F401
from materials_science.objects.devices.materialTestingDevices.thermalAnalyzer import ThermalAnalyzer  # noqa: F401
from materials_science.objects.devices.materialTestingDevices.viscometer import Viscometer  # noqa: F401
from materials_science.objects.devices.threeDimensionalPrintingDevices.fdmPrinter import FDMPrinter  # noqa: F401
from materials_science.objects.devices.threeDimensionalPrintingDevices.slaPrinter import SLAPrinter  # noqa: F401
from materials_science.objects.devices.threeDimensionalPrintingDevices.slsPrinter import SLSPrinter  # noqa: F401
from materials_science.objects.devices.threeDimensionalPrintingDevices.threeDimensionalPrintingDevice import ThreeDimensionalPrintingDevice  # noqa: F401
from materials_science.objects.devices.cncMills.cncMill import CNCMill  # noqa: F401
from materials_science.objects.devices.cncMills.fiveAxisMill import FiveAxisMill  # noqa: F401
from materials_science.objects.devices.cncMills.threeAxisMill import ThreeAxisMill  # noqa: F401

__all__ = ['Material', 'MaterialProperty', 'MaterialPurpose', 'MaterialRelatedDevice', 'MaterialResolution', 'DataProvenance', 'DataSource', 'ResolutionCategory', 'DensityFunctionalMaterial', 'QuantumResolution', 'CoarsegrainedMolecularDynamicsMaterial', 'MesoscaleResolution', 'ChosenMaterial', 'ConsistentFiniteElementMaterial', 'ContinuumResolution', 'RangeMaterial', 'StochasticFiniteElementMaterial', 'ExperimentalResolution', 'RawExperimentalMaterial', 'RulesOfMixturesExperimentalMaterial', 'AtomisticResolution', 'MolecularDynamicsMaterial', 'CommercialSourcing', 'MaterialSourcing', 'NaturalSourcing', 'OpenSourceLocalSourcing', 'PropertyValueSource', 'ReferenceMaterial', 'ABS', 'Nylon', 'PETG', 'PHA', 'PLA', 'PrintableReferenceMaterial', 'TPU', 'AdditiveCompatibility', 'Compatibilizer', 'MaterialAdditive', 'PropertyEffect', 'Formulation', 'FormulationComponent', 'FormulationIntent', 'PropertyCategory', 'ThermalProperty', 'DMAGlassTransitionMeasurement', 'GlassTransition', 'GlassTransitionTemp', 'DSCMeltingMeasurement', 'MeltingPoint', 'MeltingPointValue', 'SmokingPoint', 'SmokingPointMeasurement', 'SmokingPointValue', 'CoefficientOfThermalExpansion', 'ThermalExpansion', 'TMAMeasurement', 'SurfaceProperty', 'LiquidSurfaceTension', 'SurfaceTensionValue', 'WilhelmyMeasurement', 'ContactAngleMeasurement', 'CriticalSurfaceTension', 'SolidSurfaceEnergy', 'DensityMeterMeasurement', 'HydrometerMeasurement', 'PycnometerMeasurement', 'ReferentialSpecificGravity', 'SpecificGravity', 'RheologicalProperty', 'DMAMeasurement', 'Elasticity', 'RheometerMeasurement', 'StorageModulus', 'MeltFlowIndex', 'MFIMeasurement', 'MFIValue', 'KrebsViscosity', 'StormerViscosity', 'Viscosity', 'MechanicalProperty', 'Hardness', 'HardnessScale', 'ShoreMeasurement', 'TensileMeasurement', 'TensileStrength', 'UltimateTensileStrength', 'PropertyTarget', 'TargetMaterialProfile', 'RawMaterial', 'PurposeCategory', 'CNCMachinable', 'ThreeDimensionalPrintable', 'MoldFabricationPurpose', 'FDMPrintedMoldMaterial', 'SLAPrintedMoldMaterial', 'SLSPrintedMoldMaterial', 'ThreeDimensionalPrintedMoldMaterial', 'CNCMachinedMoldMaterial', 'MilledMoldMaterial', 'TurnedMoldMaterial', 'GeopolymerConcreteMoldMaterial', 'GeopolymerThermalResistantConcreteMoldMaterial', 'DeviceCategory', 'CNCLathe', 'HardnessTester', 'MaterialTestingDevice', 'TensileTestingMachine', 'ThermalAnalyzer', 'Viscometer', 'FDMPrinter', 'SLAPrinter', 'SLSPrinter', 'ThreeDimensionalPrintingDevice', 'CNCMill', 'FiveAxisMill', 'ThreeAxisMill']
