"""
@module cmod.cmod_api

GET /api/cmod                           the summary: projects with their counts, the parser, where the cost engines WOULD run
GET /api/cmod/projects                  every CProject row
GET /api/cmod/atoms?project=&kind=      the CFunctionAtom rows (filter by project / kind function|isr|entry)
GET /api/cmod/atoms/{atom}              one atom + its ports (`uno:hal.hal_millis`, or `hal_millis` when it is unique)
GET /api/cmod/ports?atom=               the CPort rows
GET /api/cmod/engines                   avr-gcc / avr-nm / make placement through the board engines seam (nothing is run)
GET /api/cmod/projects/{project}/drift  parse the project NOW (no engine, nothing written) and compare with its committed
                                        manifest: atoms added / removed / changed — a stale manifest is reported, never fixed here
Writing a manifest is `pol cmod conform <project>` (it measures with the engines and writes a file in the project).
cmod-1 (graphs over atoms → generated glue):
GET /api/cmod/graphs                    every CGraph row
GET /api/cmod/graphs/{graph}            the graph + its nodes, edges and glue builds
GET /api/cmod/graphs/{graph}/render     render NOW into memory (nothing written): the checked model's verdict, what the glue
                                        owns, the cost before building, each file's sha + its text — or the refusal (422)
GET /api/cmod/graphs/{graph}/diff       the committed project vs a fresh render (the graph changed / hand edits / stale files)
Writing the project is `pol cmod render <graph>` (CLI only — it writes files on the host). The canvas's render/build/prove
buttons (demo-4) use:
POST /api/cmod/graphs/{graph}/build     `cmod.custom.glue_build.build` — make ALONE in the already-rendered project (board
                                        engines); refuses 422 if the graph was never rendered on this host
POST /api/cmod/graphs/{graph}/prove     `cmod.custom.glue_build.prove` — the twin equivalence proof against the hand-written
                                        app it replaces; refuses 422 the same way
demo-4 (targets + capabilities, DEMONSTRABLES_PLAN.md §3): what a graph's ports actually control, derived from the atoms'
annotations/resources + the graph's board (never typed in — cmod.custom.targets):
GET /api/cmod/graphs/{graph}/targets    the TargetDefinition rows derived for this graph (badges on the canvas + a table)
GET /api/cmod/capabilities              every CapabilityDefinition row, with its CapabilityInstance rows inline
GET /api/cmod/capabilities/{cap}        one capability + its instances
The reverse link (demo-4 "both ways"): GET /api/cmod/graphs/{graph} now also returns `used_by` — every HardwareSolution
row whose `cgraph` names this graph (a derived query over the generic row store, no import of hwnocode needed — the same
`_rows(cls)` pattern every other generic lookup here uses).

ucd-iso-0 (the C-atom's CODE INTERFACE and C-ISOTOPES, his ruling 2026-10-10):
GET /api/cmod/atoms/{atom}/code[?binding=<solution>[@<board>]]   the atom's own C, verbatim, with one autogenerated
                                        comment per datasheet-sourced identifier (cmod.custom.code_interface.render)
GET /api/cmod/atoms/{atom}/isotopes    every CIsotope of this atom (one per HardwareBinding with >= 1 datasheet-bound
                                        identifier), materialized into the manager's own table (the PinClaim idiom)

fs-2d (his ask, verbatim: "our tasks to be linked to their no-code solutions that compose them"): every node in
GET /api/cmod/graphs/{graph}'s `nodes` now also carries `firmware` — [{solution, lane, order, registered_pin}, ...],
every FirmwareSolution task that IS this node (`_node_firmware`). The reverse half (a firmware task row's own
`composed_by`, pointing back at this graph/node) is GET /api/firmware/solutions/{name} (cmod_firmware_api.FirmwareAPI).
"""
import inspect
import json

from objectTreeDecorators import treeObject, treeObjectInit


class CModAPI(treeObject):
    @treeObjectInit
    def __init__(self, polServer=None, manager=None):
        self.polServer = polServer
        self.manager = manager
        if polServer is not None and getattr(polServer, 'falconServer', None) is not None:
            add = polServer.falconServer.add_route
            add('/api/cmod', self, suffix='summary')
            add('/api/cmod/projects', self, suffix='projects')
            add('/api/cmod/atoms', self, suffix='atoms')
            add('/api/cmod/atoms/{atom}', self, suffix='atom_one')
            add('/api/cmod/atoms/{atom}/code', self, suffix='atom_code')   # ucd-iso-0
            add('/api/cmod/atoms/{atom}/isotopes', self, suffix='atom_isotopes')   # ucd-iso-0
            add('/api/cmod/ports', self, suffix='ports')
            add('/api/cmod/engines', self, suffix='engines')
            add('/api/cmod/projects/{project}/drift', self, suffix='drift')
            add('/api/cmod/graphs', self, suffix='graphs')
            add('/api/cmod/graphs/{graph}', self, suffix='graph_one')
            add('/api/cmod/graphs/{graph}/render', self, suffix='graph_render')
            add('/api/cmod/graphs/{graph}/diff', self, suffix='graph_diff')
            add('/api/cmod/graphs/{graph}/targets', self, suffix='graph_targets')
            add('/api/cmod/graphs/{graph}/build', self, suffix='graph_build')
            add('/api/cmod/graphs/{graph}/prove', self, suffix='graph_prove')
            add('/api/cmod/capabilities', self, suffix='capabilities')
            add('/api/cmod/capabilities/{capability}', self, suffix='capability_one')

    def _rows(self, cls):
        return list(((self.manager.objectTables or {}).get(cls, {}) or {}).values()) if self.manager is not None else []

    @staticmethod
    def _d(row):
        keys = [k for k in inspect.signature(type(row).__init__).parameters if k not in ('self', 'manager')]
        return {k: getattr(row, k, None) for k in keys}

    def on_get_summary(self, request, response):
        import pycparser
        projects = sorted(self._rows('CProject'), key=lambda r: r.name)
        response.media = {'ok': True, 'parser': {'engine': 'pycparser', 'version': pycparser.__version__, 'runs': 'in this process'},
                          'projects': [{k: getattr(p, k, '') for k in ('name', 'kind', 'root', 'atoms', 'annotated', 'isr_atoms', 'pure_atoms',
                                                                         'not_isr_safe', 'configurations', 'conformed_at')} for p in projects],
                          'atoms': len(self._rows('CFunctionAtom')), 'ports': len(self._rows('CPort')), 'graphs': len(self._rows('CGraph'))}

    def on_get_projects(self, request, response):
        response.media = {'ok': True, 'projects': [self._d(r) for r in sorted(self._rows('CProject'), key=lambda r: r.name)]}

    def on_get_atoms(self, request, response):
        proj, kind = request.get_param('project') or '', request.get_param('kind') or ''
        rows = [r for r in self._rows('CFunctionAtom') if (not proj or r.project == proj) and (not kind or r.kind == kind)]
        response.media = {'ok': True, 'atoms': [self._d(r) for r in sorted(rows, key=lambda r: r.name)]}

    def _find(self, name):
        rows = self._rows('CFunctionAtom')
        exact = [r for r in rows if r.name == name]
        if exact:
            return exact, []
        hits = [r for r in rows if r.function == name or r.name.split(':', 1)[-1] == name]
        return (hits, []) if len(hits) == 1 else ([], sorted(r.name for r in hits))

    def on_get_atom_one(self, request, response, atom):
        import falcon
        hits, many = self._find(atom)
        if not hits:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': ('%r names several atoms: %s — use the full name' % (atom, ', '.join(many))) if many
                              else 'no atom named %r (GET /api/cmod/atoms lists them)' % atom}
            return
        a = hits[0]
        ports = sorted((p for p in self._rows('CPort') if p.atom == a.name), key=lambda p: p.position)
        # ucd-iso-0: isotopes_refs_json filled at SERVE time (never at seed/parse time — an isotope is derived per
        # binding, on demand, same posture as PinClaim/PeripheralClaim's own materialize idiom)
        iso_refs = sorted('CIsotope:%s' % r.name for r in self._rows('CIsotope') if getattr(r, 'parent', '') == a.name)
        if self.manager is not None:
            setattr(a, 'isotopes_refs_json', json.dumps(iso_refs))
        response.media = {'ok': True, 'atom': dict(self._d(a), isotopes_refs_json=json.dumps(iso_refs)), 'ports': [self._d(p) for p in ports]}

    def on_get_atom_code(self, request, response, atom):
        import falcon
        from cmod.custom import code_interface as CI
        binding = request.get_param('binding') or None
        try:
            r = CI.render(atom, binding=binding, manager=self.manager)
        except CI.CodeInterfaceRefused as e:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': str(e)}
            return
        response.media = r

    def on_get_atom_isotopes(self, request, response, atom):
        import falcon
        from cmod.custom import code_interface as CI
        try:
            CI.find_atom(atom)
        except CI.CodeInterfaceRefused as e:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': str(e)}
            return
        rows = CI.isotopes_for_atom(atom, manager=self.manager)
        if self.manager is not None:
            from cmod.cmod_basis import CIsotope
            self._upsert('CIsotope', CIsotope, rows)
        response.media = {'ok': True, 'atom': atom, 'rows': rows}

    def _upsert(self, cls_name, cls, rows):
        """Same idiom as cmod_firmware_api.FirmwareAPI._upsert — upsert `rows` (dicts) by `name` into the manager's
        own table (update an existing row's fields in place, construct+register a new one)."""
        table = (self.manager.objectTables or {}).setdefault(cls_name, {})
        by_name = {getattr(r, 'name', ''): r for r in table.values()}
        for row in rows:
            existing = by_name.get(row['name'])
            if existing is not None:
                for k, v in row.items():
                    setattr(existing, k, v)
            else:
                cls(manager=self.manager, **row)

    def on_get_ports(self, request, response):
        atom = request.get_param('atom') or ''
        rows = [r for r in self._rows('CPort') if not atom or r.atom == atom]
        response.media = {'ok': True, 'ports': [self._d(r) for r in sorted(rows, key=lambda r: (r.atom, r.position))]}

    def on_get_engines(self, request, response):
        from cmod.custom import cmod_engines
        response.media = {'ok': True, 'engines': cmod_engines.placement(),
                          'note': 'parsing needs no engine (pycparser in this process); only the cost and the make-alone proof do'}

    def on_get_drift(self, request, response, project):
        import falcon
        from cmod.custom import manifest as MF
        from cmod.custom import projects as P
        if project not in P.TEMPLATES:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': 'no template project %r here (known: %s); a plain directory is checked with '
                                                    '`pol cmod conform <dir>`' % (project, ', '.join(sorted(P.TEMPLATES)))}
            return
        try:
            r = MF.conform(project, measure=False, write=False)
        except Exception as e:   # a malformed annotation or an unparsable file: the refusal, in plain words
            response.status = falcon.HTTP_422
            response.media = {'ok': False, 'error': str(e)}
            return
        response.media = {'ok': True, 'project': project, 'stale': r['changed'], 'added': r['added'], 'removed': r['removed'],
                          'edited': r['edited'], 'atoms': r['manifest']['counts']['atoms'],
                          'how': 'parsed now with pycparser, compared with the committed manifest (cost blocks kept: nothing was measured)'}

    # ------------------------------------------------------------------ cmod-1
    def on_get_graphs(self, request, response):
        response.media = {'ok': True, 'graphs': [self._d(r) for r in sorted(self._rows('CGraph'), key=lambda r: r.name)]}

    def _graph(self, graph, response):
        import falcon
        g = [r for r in self._rows('CGraph') if r.name == graph]
        if not g:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': 'no graph %r (GET /api/cmod/graphs lists them)' % graph}
        return g[0] if g else None

    def _node_firmware(self, instance):
        """fs-2d (his ask: tasks linked to "their no-code solutions that compose them", both ways): the FORWARD half
        — every FirmwareSolution task (RegisterAssignment.task / ScheduleSlot.task, cmod.custom.firmware) that IS
        this CGraphNode's own `instance` name, as {solution, lane, order, registered_pin}. The reverse half (a task
        row knowing its own node/canvas route) is GET /api/firmware/solutions/{name}'s `composed_by`
        (cmod_firmware_api.FirmwareAPI._composed_by) — same rows, read from the other side."""
        asg = {getattr(r, 'solution', ''): r for r in self._rows('RegisterAssignment') if getattr(r, 'task', '') == instance}
        sched = {getattr(r, 'solution', ''): r for r in self._rows('ScheduleSlot') if getattr(r, 'task', '') == instance}
        out = []
        for sol in sorted(set(asg) | set(sched)):
            a, sc = asg.get(sol), sched.get(sol)
            lives_on = getattr(a, 'lives_on', '') if a is not None else ''
            out.append({'solution': sol, 'lane': getattr(sc, 'lane', '') if sc is not None else '',
                       'order': getattr(sc, 'order', None) if sc is not None else None,
                       'registered_pin': lives_on if lives_on and lives_on != 'unbound' else ''})
        return out

    def on_get_graph_one(self, request, response, graph):
        g = self._graph(graph, response)
        if g is None:
            return
        pick = lambda cls, key: [self._d(r) for r in sorted(self._rows(cls), key=key) if r.graph == graph]  # noqa: E731
        used_by = [self._d(r) for r in sorted(self._rows('HardwareSolution'), key=lambda r: r.name) if getattr(r, 'cgraph', '') == graph]
        nodes = pick('CGraphNode', lambda r: (r.order, r.instance))
        for n in nodes:
            n['firmware'] = self._node_firmware(n['instance'])
        response.media = {'ok': True, 'graph': self._d(g), 'nodes': nodes,
                          'edges': pick('CGraphEdge', lambda r: (r.order, r.name)), 'glue_builds': pick('CGlueBuild', lambda r: r.name),
                          'targets': pick('TargetDefinition', lambda r: (r.kind, r.port_ref)),
                          'used_by': used_by,
                          'used_by_how': 'every HardwareSolution row whose cgraph names this graph (hn-split: the board half IS this CGraph)'}

    def on_get_graph_render(self, request, response, graph):
        import falcon
        from cmod.custom import glue as GL
        from cmod.custom.graph import GraphRefused
        if self._graph(graph, response) is None:
            return
        try:
            r = GL.render(graph, manager=self.manager, write=False)
        except (GL.GlueRefused, GraphRefused) as e:
            response.status = falcon.HTTP_422
            response.media = {'ok': False, 'refused': str(e)}
            return
        response.media = {'ok': True, 'graph': graph, 'graph_sha256': r['sha'], 'files_sha256': r['files_sha256'], 'unchanged': r['unchanged'],
                          'glue_contains': r['glue_contains'], 'advice': r['advice'],
                          'cost_before_building': {'total_bytes': r['cost']['total_bytes'], 'why': r['cost']['why'],
                                                   'parts': [{'atom': a, 'bytes': b, 'as': w} for a, b, w in r['cost']['parts']]},
                          'files': [{'file': f, 'sha256': r['files'][f], 'bytes': len(r['texts'][f])} for f in sorted(r['files'])],
                          'how': 'rendered in this process from the graph rows + the atoms\' committed manifest; nothing written'}

    def on_get_graph_diff(self, request, response, graph):
        import falcon
        from cmod.custom import glue as GL
        from cmod.custom.graph import GraphRefused
        if self._graph(graph, response) is None:
            return
        try:
            d = GL.diff(graph, manager=self.manager)
        except (GL.GlueRefused, GraphRefused) as e:
            response.status = falcon.HTTP_422
            response.media = {'ok': False, 'refused': str(e)}
            return
        response.media = dict({k: v for k, v in d.items() if k != 'dir'}, ok=True)

    # ------------------------------------------------------------------ demo-4: targets, build/prove buttons, capabilities
    def on_get_graph_targets(self, request, response, graph):
        if self._graph(graph, response) is None:
            return
        from cmod.custom import targets as T
        from cmod.custom.overrides import apply_overrides
        rows = [r for r in self._rows('TargetDefinition') if r.graph == graph]
        derived = rows if rows else T.derive(graph, manager=self.manager)
        out = [self._d(r) for r in rows] if rows else derived
        out = apply_overrides(out, 'TargetDefinition', manager=self.manager)
        response.media = {'ok': True, 'graph': graph, 'targets': sorted(out, key=lambda r: (r.get('kind', ''), r.get('port_ref', ''))),
                          'how': 'derived from each c-atom\'s resources (registers/declared macros) matched against the graph\'s board\'s '
                                 'BoardPin rows, plus one per \'field\' CGraphEdge — never typed in (cmod.custom.targets)'}

    def on_post_graph_build(self, request, response, graph):
        import falcon
        from cmod.custom import glue_build as GB
        from cmod.custom.glue import GlueRefused
        if self._graph(graph, response) is None:
            return
        try:
            rec = GB.build(graph, manager=self.manager)
        except GlueRefused as e:
            response.status = falcon.HTTP_422
            response.media = {'ok': False, 'refused': str(e)}
            return
        b = rec['build']
        response.media = {'ok': True, 'graph': graph, 'built_by': b['built_by'], 'hex_sha256': b['hex_sha256'],
                          'size_text': b['size_text'], 'size_data': b['size_data'], 'size_bss': b['size_bss'],
                          'cost_why': b['cost_why']}

    def on_post_graph_prove(self, request, response, graph):
        import falcon
        from cmod.custom import glue_build as GB
        from cmod.custom.glue import GlueRefused
        if self._graph(graph, response) is None:
            return
        try:
            p = GB.prove(graph, manager=self.manager)
        except GlueRefused as e:
            response.status = falcon.HTTP_422
            response.media = {'ok': False, 'refused': str(e)}
            return
        response.media = {'ok': True, 'graph': graph, 'equivalent': p['equivalent'], 'frames_compared': p['frames_compared'],
                          'hex_identical': p.get('hex_identical'), 'n_differences': p.get('n_differences', 0),
                          'differences': p.get('differences', [])}

    def on_get_capabilities(self, request, response):
        caps = sorted(self._rows('CapabilityDefinition'), key=lambda r: r.name)
        insts = self._rows('CapabilityInstance')
        response.media = {'ok': True, 'capabilities': [dict(self._d(c), instances=[self._d(i) for i in sorted(insts, key=lambda r: r.index)
                                                                                   if i.capability == c.name]) for c in caps]}

    def on_get_capability_one(self, request, response, capability):
        import falcon
        caps = [r for r in self._rows('CapabilityDefinition') if r.name == capability]
        if not caps:
            response.status = falcon.HTTP_404
            response.media = {'ok': False, 'error': 'no capability %r (GET /api/cmod/capabilities lists them)' % capability}
            return
        c = caps[0]
        insts = sorted((r for r in self._rows('CapabilityInstance') if r.capability == capability), key=lambda r: r.index)
        response.media = {'ok': True, 'capability': self._d(c), 'instances': [self._d(i) for i in insts]}
