// Generated by Polari hwfpga.fpga_verilog from register map
// "hardware-runtime" — do not edit; edit the RegisterDefinition rows
// (the knobs) and regenerate. Synthesizable 32-bit AXI4-Lite slave.
module polari_regblock (
    input  wire        clk,
    // ACTIVE-LOW reset (Renode IntegrationLibrary convention: its
    // AxiLite driver pulses rst=0 at attach and leaves rst=1 to run).
    input  wire        rst,
    input  wire [31:0] awaddr,
    input  wire        awvalid,
    output reg         awready,
    input  wire [31:0] wdata,
    input  wire [3:0]  wstrb,
    input  wire        wvalid,
    output reg         wready,
    output reg  [1:0]  bresp,
    output reg         bvalid,
    input  wire        bready,
    input  wire [31:0] araddr,
    input  wire        arvalid,
    output reg         arready,
    output reg  [31:0] rdata,
    output reg  [1:0]  rresp,
    output reg         rvalid,
    input  wire        rready,
    // The mode MUX's source-1 input: real pins on silicon, a stub
    // pattern in simulation.
    input  wire [7:0]  hw_pin_in,
    // LED_MATRIX low 16 bits drive pins (pins_out knob on the row)
    output wire [15:0] led_matrix_pins
);
    reg  [31:0] r_commands;  // 0x0010 Command word from the MCU / Polari.
    reg  [31:0] r_config;  // 0x0020 Configuration word.
    reg  [31:0] r_mode_mux;  // 0x0024 Input-source select (a real multiplexer): bit0 0=sim counter, 1=hardware input pins.
    reg  [31:0] r_led_matrix;  // 0x0030 4x4 LED matrix: bit(row*4+col) lights LED (row, col); the low 16 bits drive pins.
    assign led_matrix_pins = r_led_matrix[15:0];

    // Fixed logic: liveness heartbeat + the two MUX input sources.
    reg  [15:0] heartbeat;
    reg  [7:0]  sim_counter;
    // THE MUX (select bits = the MODE_MUX knob's bit0):
    wire [7:0]  mux_in = r_mode_mux[0] ? hw_pin_in : sim_counter;
    wire [31:0] v_status = {8'h00, mux_in, heartbeat};
    wire [31:0] v_faults = 32'h0;

    wire in_reset = ~rst;

    always @(posedge clk) begin
        if (in_reset) begin
            heartbeat   <= 16'h0;
            sim_counter <= 8'h0;
        end else begin
            heartbeat   <= heartbeat + 16'h1;
            sim_counter <= sim_counter + 8'h1;
        end
    end

    // Write: independent AW / W handshakes (the IntegrationLibrary
    // driver raises them sequentially), commit when both latched.
    reg        aw_got, w_got;
    reg [7:0]  waddr_l;
    reg [31:0] wdata_l;
    always @(posedge clk) begin
        if (in_reset) begin
            awready <= 1'b0; wready <= 1'b0; bvalid <= 1'b0;
            bresp <= 2'b00; aw_got <= 1'b0; w_got <= 1'b0;
            waddr_l <= 8'h0; wdata_l <= 32'h0;
            r_commands <= 32'h00000000;
            r_config <= 32'h00000000;
            r_mode_mux <= 32'h00000000;
            r_led_matrix <= 32'h00000000;
        end else begin
            if (awvalid && !aw_got && !awready) begin
                awready <= 1'b1;
                waddr_l <= awaddr[7:0];
                aw_got  <= 1'b1;
            end else begin
                awready <= 1'b0;
            end
            if (wvalid && !w_got && !wready) begin
                wready  <= 1'b1;
                wdata_l <= wdata;
                w_got   <= 1'b1;
            end else begin
                wready <= 1'b0;
            end
            if (aw_got && w_got && !bvalid) begin
                case (waddr_l)
                8'h10: r_commands <= wdata;
                8'h20: r_config <= wdata;
                8'h24: r_mode_mux <= wdata;
                8'h30: r_led_matrix <= wdata;
                    default: ;  // ro/const/unmapped: write ignored
                endcase
                bvalid <= 1'b1;
                bresp  <= 2'b00;
                aw_got <= 1'b0;
                w_got  <= 1'b0;
            end else if (bvalid && bready) begin
                bvalid <= 1'b0;
            end
        end
    end

    // Read: latch on the AR handshake cycle, hold rvalid until rready.
    always @(posedge clk) begin
        if (in_reset) begin
            arready <= 1'b0; rvalid <= 1'b0;
            rdata <= 32'h0; rresp <= 2'b00;
        end else begin
            if (arvalid && !rvalid && !arready) begin
                arready <= 1'b1;
            end else begin
                arready <= 1'b0;
            end
            if (arready && arvalid && !rvalid) begin
                rvalid <= 1'b1;
                rresp  <= 2'b00;
                case (araddr[7:0])
                8'h00: rdata <= 32'h504C0001;  // DEVICE_ID (hardwired)
                8'h04: rdata <= 32'h00010000;  // VERSION (hardwired)
                8'h08: rdata <= v_status;
                8'h0C: rdata <= v_faults;
                8'h10: rdata <= r_commands;
                8'h20: rdata <= r_config;
                8'h24: rdata <= r_mode_mux;
                8'h30: rdata <= r_led_matrix;
                    default: rdata <= 32'h00000000;
                endcase
            end else if (rvalid && rready) begin
                rvalid <= 1'b0;
            end
        end
    end
endmodule
