// Generated by Polari hwfpga.fpga_verilog — Renode co-sim harness.
#include <cstdio>
#include <cstdlib>
#include "Vtop.h"
#include "verilated.h"
#include "src/renode_bus.h"
#include "src/buses/axilite.h"

static Vtop *top;
static RenodeAgent *agent;

static void evaluateModel()
{
    top->eval();
}

RenodeAgent* Init()
{
    top = new Vtop;
    AxiLite* bus = new AxiLite();
    bus->clk = &top->clk;
    bus->rst = &top->rst;
    bus->awaddr = (uint64_t *)&top->awaddr;
    bus->awvalid = &top->awvalid;
    bus->awready = &top->awready;
    bus->awprot = &top->awprot;
    bus->wdata = (uint64_t *)&top->wdata;
    bus->wstrb = &top->wstrb;
    bus->wvalid = &top->wvalid;
    bus->wready = &top->wready;
    bus->bresp = &top->bresp;
    bus->bvalid = &top->bvalid;
    bus->bready = &top->bready;
    bus->araddr = (uint64_t *)&top->araddr;
    bus->arvalid = &top->arvalid;
    bus->arready = &top->arready;
    bus->arprot = &top->arprot;
    bus->rdata = (uint64_t *)&top->rdata;
    bus->rresp = &top->rresp;
    bus->rvalid = &top->rvalid;
    bus->rready = &top->rready;
    bus->evaluateModel = evaluateModel;

    agent = new RenodeAgent();
    agent->addBus(bus);
    // Library mode (Renode dlopens the .so and calls
    // initialize_native -> Init): the native channel must exist
    // BEFORE the first bus access or the response send derefs NULL.
    // Socket mode's main() replaces it via connect() afterwards.
    agent->connectNative();
    return agent;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr,
                "usage: %s {receiverPort} {senderPort} [address]\n",
                argv[0]);
        return 1;
    }
    const char *address = (argc < 4) ? "127.0.0.1" : argv[3];
    Verilated::commandArgs(argc, argv);
    Init();
    agent->connect(atoi(argv[1]), atoi(argv[2]), address);
    agent->simulate();
    delete top;
    return 0;
}
