"""
@module foodstate.export_initial_data

The AUTOMATED half of the module-data convention for foodstate
(Dustin 2026-09-02: "go the route of automating — go with the
optional improvement as well"): the hand-curated, citation-bearing
tables are exported to `initialData/*.json` BY THIS SCRIPT, never
typed twice — the seed builders in code stay the single source of
truth, the JSON is the interchange artifact (served by
GET /modules/foodstate/initial-data for API installs, seeded at
boot through the same idempotent upsert).

Exported (the curated, non-regenerable-in-spirit data):
  FoodMaterial.json    the 49-ingredient FDC identity mapping
  PropertyClaim.json   the literature pH ranges + organic-acid
                       values (hand-transcribed citations) — NOT
                       the 949 FDC-derived composition claims,
                       which regenerate from the nutrition
                       module's vendored CSV (foodstate requires
                       nutrition; duplicating them here would be
                       two sources of truth).

Regenerate after editing any seed builder:
    cd polari-framework/modules
    PYTHONPATH=..:../polariApiServer python3 -m foodstate.export_initial_data
A drift guard (selftest_initial_data) fails the suite when the
files and the builders disagree.

@consumers
  - moduleService.json_seeds (boot pass + /modules API)
  - foodstate.selftest_initial_data (drift guard)
"""

import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(_HERE, 'initialData')

SCHEMA = 'module-initial-data/1'
_SOURCE = ('generated by foodstate.export_initial_data from the '
           'in-code seed builders (the single source of truth) — '
           'regenerate via python3 -m foodstate.export_initial_data; '
           'drift fails selftest_initial_data')


def build_payloads():
    """{filename: payload} — deterministic (sorted rows/keys)."""
    from foodstate.food_acid_seed import SEED_FOOD_ACID_CLAIMS
    from foodstate.food_composition import vendor_food_index
    from foodstate.food_materials import build_food_material_seeds
    from foodstate.food_ph_seed import SEED_FOOD_PH_CLAIMS

    materials = sorted(build_food_material_seeds(vendor_food_index()),
                       key=lambda r: r['name'])
    curated_claims = sorted(
        list(SEED_FOOD_PH_CLAIMS) + list(SEED_FOOD_ACID_CLAIMS),
        key=lambda r: r['name'])
    return {
        'FoodMaterial.json': {
            'schema': SCHEMA, 'class': 'FoodMaterial',
            'source': _SOURCE + '; identity resolved FROM the '
                      'sha-pinned FDC vendor subset '
                      '(nutrition/vendor, CC0)',
            'count': len(materials), 'rows': materials,
        },
        'PropertyClaim.json': {
            'schema': SCHEMA, 'class': 'PropertyClaim',
            'source': _SOURCE + '; ONLY the curated literature '
                      'pH + organic-acid claims — the FDC-derived '
                      'composition claims regenerate from the '
                      'nutrition module\'s vendored CSV and are '
                      'deliberately NOT duplicated here',
            'count': len(curated_claims), 'rows': curated_claims,
        },
    }


def render(payload):
    return json.dumps(payload, indent=1, sort_keys=True,
                      ensure_ascii=False) + '\n'


def export(write=True):
    payloads = build_payloads()
    written = []
    if write:
        os.makedirs(DATA_DIR, exist_ok=True)
    for filename, payload in sorted(payloads.items()):
        path = os.path.join(DATA_DIR, filename)
        if write:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(render(payload))
        written.append((filename, payload['count']))
    return written


if __name__ == '__main__':
    for filename, count in export(write=True):
        print(f'wrote initialData/{filename} ({count} rows)')
