"""
@module computelod.custom.lod3_drc

DRC + LVS OF THE ROUTED ADDER (lod-3f, 2026-09-26; plan §H.6 slice 2). lod-3e's router reports zero design-rule violations by
its OWN check, and every CELL passed magic's full-rule deck alone in lod-3c — but magic's full deck was never run on the merged
adder layout, and no layout-versus-schematic of the routed design existed. This flow runs both, through the engines ladder:

    DRC    magic reads OpenROAD's merged GDS (the PDK's cells + our placement and routing), runs the sky130A full deck on the
           WHOLE design — taps and wells are in the rows now, so no context rule is excused: a clean result means clean, and
           any rule the router does not know (antenna, density, …) is REPORTED as such, never tuned away
    LVS    magic extracts the layout hierarchically (cells as subcircuits) and netgen compares it to the routed Verilog
           netlist (6_final.v, the cells as black boxes on both sides — the cells themselves were LVS-matched to their
           schematics in lod-3c, so this checks the WIRING: every instance, every net, every pin)

Cost (his rule, stated before running): magic + netgen from the profiled eda-tools image (prf-eda-engines); the GDS is
~0.3 MB, the design 292 cells — the cheapest of the lod flows; the ORFS image is needed only when the GDS must be regenerated
(lod3_pnr run). The GDS/ODB never enter git (they merge the PDK's cell layouts): the flow reads them from lod3_pnr's work dir
and keeps only the verdicts, the rule names, the extracted-netlist sha256 and a reproduction block with cost.

    python3 -m computelod.custom.lod3_drc run [--variants as-flow,cells-kept] [--work DIR]
"""
import hashlib
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(HERE)
OUT = os.path.join(MOD, 'initialData', 'lod3', 'pnr')
FLOWS = os.path.normpath(os.path.join(MOD, '..', '..', '..', 'polari-eda-tools', 'flows'))
DESIGN, PLATFORM = 'rv32_add', 'sky130hd'


def _sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def _pnr_results(variant, work):
    base = os.path.join(work or os.path.join(os.environ.get('TMPDIR', '/tmp'), 'polari-lod3e'), variant, 'work', 'results', PLATFORM, DESIGN, 'base')
    return base if os.path.exists(os.path.join(base, '6_1_merged.gds')) else ''


def run(variants=None, work=None, pnr_work=None):
    from computelod.custom.repro import start_meter, stop_meter, record, file_entry
    start_meter('computelod.custom.lod3_drc')
    from computelod.custom.eda_engines import resolve, run as eng, PDK_ROOT as _PDK_LOCAL
    for e in ('magic', 'netgen'):
        r = resolve(e)
        if r['how'] == 'refused':
            raise SystemExit(r['why'])
    work = work or os.path.join(os.environ.get('TMPDIR', '/tmp'), 'polari-lod3f'); os.makedirs(work, exist_ok=True)
    rep = {'engines': {e: resolve(e) for e in ('magic', 'netgen')}, 'variants': {}, 'source': 'lod3_pnr work dir (6_1_merged.gds, 6_final.v) — regenerated by `python3 -m computelod.custom.lod3_pnr run` when absent',
           'pdk_tech_sha256': _sha(os.path.join(_PDK_LOCAL, 'sky130A', 'libs.tech', 'magic', 'sky130A.tech')) if os.path.exists(os.path.join(_PDK_LOCAL, 'sky130A', 'libs.tech', 'magic', 'sky130A.tech')) else 'remote worker\'s PDK'}
    for var in (variants or ['as-flow', 'cells-kept']):
        res = _pnr_results(var, pnr_work)
        if not res:
            rep['variants'][var] = {'refused': 'no merged GDS for this variant in lod3_pnr\'s work dir — run `python3 -m computelod.custom.lod3_pnr run` first (the GDS is never committed: it merges the PDK\'s cell layouts)'}
            continue
        vw = os.path.join(work, var); shutil.rmtree(vw, ignore_errors=True); os.makedirs(vw)
        shutil.copy(os.path.join(res, '6_1_merged.gds'), os.path.join(vw, 'merged.gds')); shutil.copy(os.path.join(res, '6_final.v'), vw); shutil.copy(os.path.join(FLOWS, 'design_check.tcl'), vw)
        # ---- DRC + hierarchical extraction
        r = eng('magic', vw, ['-dnull', '-noconsole', '-rcfile', '/pdk/sky130A/libs.tech/magic/sky130A.magicrc', 'design_check.tcl'], env={'GDS': 'merged.gds', 'TOP': DESIGN}, pdk=True, timeout=1800, stdout_to='magic.log')
        out = r['stdout'] + r['stderr']
        m = re.search(r'POLARI_DRC_COUNT (\d+)', out)
        rules = sorted({x.strip() for x in re.findall(r'POLARI_DRC_WHY (.+)', out) if not x.strip().startswith('{')})
        drc = {'ran': m is not None, 'count': int(m.group(1)) if m else None, 'rules': rules, 'clean': m is not None and int(m.group(1)) == 0,
               'note': 'the full sky130A deck on the merged design; NO context rule is excused here (taps and wells are in the rows) — every reported rule is real for this layout'}
        lvs_net = os.path.join(vw, '%s_lvs.spice' % DESIGN)
        entry = {'gds_sha256': _sha(os.path.join(res, '6_1_merged.gds')), 'gds_bytes': os.path.getsize(os.path.join(res, '6_1_merged.gds')), 'netlist_sha256': _sha(os.path.join(res, '6_final.v')), 'drc': drc,
                 'extracted': {'ran': os.path.exists(lvs_net), 'sha256': _sha(lvs_net) if os.path.exists(lvs_net) else None,
                               'subckts': len(re.findall(r'^\.subckt ', open(lvs_net, errors='replace').read(), re.M)) if os.path.exists(lvs_net) else 0}, 'lvs': {'ran': False}}
        # ---- LVS: the extracted layout (cells as subcircuits, VPWR/VGND ports) vs the routed netlist WITH its power connections.
        # 6_final.v has no power pins (ORFS writes it that way) while every extracted cell does — compared as-is, netgen invents one
        # dummy net per unconnected power pin (966 on as-flow, found 2026-09-26) and nothing matches. OpenROAD itself writes the
        # power-connected netlist from the routed ODB (write_verilog -include_pwr_gnd); fill / tap / decap cells the netlist never
        # names are ignored on both sides BY NAME (design_lvs.tcl), stated here.
        if os.path.exists(lvs_net):
            pwr_v = ''
            if os.path.exists(os.path.join(res, '6_final.odb')):
                shutil.copy(os.path.join(res, '6_final.odb'), vw)
                open(os.path.join(vw, 'pwr.tcl'), 'w').write('read_db 6_final.odb\nwrite_verilog -include_pwr_gnd 6_final_pwr.v\nexit\n')
                r1 = eng('openroad', vw, ['-exit', '-no_init', '-no_splash', 'pwr.tcl'], timeout=600, stdout_to='openroad_pwr.log')
                if os.path.exists(os.path.join(vw, '6_final_pwr.v')):
                    pwr_v = '6_final_pwr.v'
                entry['power_netlist'] = {'written_by': 'openroad write_verilog -include_pwr_gnd from 6_final.odb', 'ok': bool(pwr_v), 'returncode': r1['returncode'], 'tail': '' if pwr_v else (r1['stdout'] + r1['stderr'])[-400:]}
            if not pwr_v:
                entry['lvs'] = {'ran': False, 'why': 'no power-connected netlist (openroad write_verilog -include_pwr_gnd did not produce one) — comparing 6_final.v without power pins cannot match (966 dummy nets, seen); not run rather than reported as a mismatch'}
            else:
                shutil.copy(os.path.join(FLOWS, 'design_lvs.tcl'), vw)
                r2 = eng('netgen', vw, ['-batch', 'source', 'design_lvs.tcl'], env={'TOP': DESIGN, 'LAYOUT': '%s_lvs.spice' % DESIGN, 'SCHEMATIC': pwr_v, 'OUT': 'lvs.out'}, pdk=True, timeout=1800, stdout_to='lvs.log')
                verdict_src = r2['stdout'] + r2['stderr'] + (open(os.path.join(vw, 'lvs.out'), errors='replace').read() if os.path.exists(os.path.join(vw, 'lvs.out')) else '')
                lines = sorted({l.strip() for l in verdict_src.splitlines() if re.search(r'match|Result|Netlists|Mismatch|uniquely|Number of', l)})
                entry['lvs'] = {'ran': True, 'match': 'Circuits match uniquely' in verdict_src, 'verdict': lines[:10], 'returncode': r2['returncode'],
                                'ignored_classes': sorted(set(re.findall(r'POLARI_LVS_IGNORED (\S+)', r2['stdout'] + r2['stderr']))),
                                'mode': 'netgen -blackbox on the extracted layout vs OpenROAD\'s power-connected netlist: the standard cells are black boxes both sides (their transistor-level LVS is lod-3c\'s); fill/tap/decap ignored by name; this checks instances, nets and pins of the routed wiring INCLUDING power'}
        rep['variants'][var] = entry
        os.makedirs(os.path.join(OUT, var), exist_ok=True)
        for f in ('magic.log', 'lvs.out', 'lvs.log'):
            if os.path.exists(os.path.join(vw, f)):
                shutil.copy(os.path.join(vw, f), os.path.join(OUT, var, 'drc_lvs_' + f))
    done = {v: e for v, e in rep['variants'].items() if 'drc' in e}
    rep['summary'] = {'variants': sorted(done), 'drc_clean': {v: e['drc']['clean'] for v, e in done.items()}, 'drc_counts': {v: e['drc']['count'] for v, e in done.items()},
                      'lvs_match': {v: e['lvs'].get('match') for v, e in done.items()},
                      'reading': 'an INDEPENDENT checker on the routed adder: magic\'s full deck (not the router\'s own count) and netgen against the routed netlist; a rule reported here that the router did not know is a finding, not noise'}
    rep['reproduction'] = record('computelod.custom.lod3_drc', cost=stop_meter('computelod.custom.lod3_drc'),
                                 inputs=[{'label': '%s 6_1_merged.gds (PDK cells merged — never committed)' % v, 'sha256': e['gds_sha256']} for v, e in done.items()] + [{'label': '%s 6_final.v (committed in lod3/pnr/%s)' % (v, v), 'sha256': e['netlist_sha256']} for v, e in done.items()]
                                        + [file_entry(os.path.join(FLOWS, 'design_check.tcl'), 'magic flow (polari-eda-tools/flows)'), {'label': 'sky130A.tech', 'sha256': rep['pdk_tech_sha256']}],
                                 engines=['magic', 'netgen'], knobs={'lvs_mode': 'netgen -blackbox (cells black-boxed both sides)', 'drc_style': 'drc(full), euclidean'}, conditions={'design': DESIGN, 'platform': PLATFORM},
                                 deterministic='magic DRC/extraction and netgen on fixed inputs (a clean work dir per run) — no random element')
    os.makedirs(OUT, exist_ok=True)
    json.dump(rep, open(os.path.join(OUT, 'drc_lvs_report.json'), 'w'), indent=1)
    return rep


def report():
    p = os.path.join(OUT, 'drc_lvs_report.json')
    return json.load(open(p)) if os.path.exists(p) else None


def rows(rep):
    """Characterizations UP from the routed layout: the independent DRC count and the LVS verdict per variant (measured: the tools' own output)."""
    if not rep:
        return [], []
    C = lambda **k: dict({'description': '', 'notes': ''}, **k)
    chars = []
    ev = 'lod3/pnr/drc_lvs_report.json — magic (sky130A full deck) + netgen -blackbox on OpenROAD\'s merged GDS and 6_final.v via the engines ladder (%s)' % ', '.join('%s: %s' % (e, v['how']) for e, v in rep.get('engines', {}).items())
    for var, e in rep['variants'].items():
        if 'drc' not in e:
            continue
        lay_ref = 'sky130hd rv32_add routed (%s) — merged GDS sha256 %s' % (var, e['gds_sha256'][:12])
        chars.append(C(name='lod3f: rv32_add full-deck DRC violations (%s)' % var, source_rung='layout', source_ref=lay_ref, target_rung='standard-cells', target_ref='sky130_fd_sc_hd rv32_add (%s)' % var,
                       characteristic='drc_violations', method='magic drc(full) on the merged GDS (independent of the router)', conditions_json=json.dumps({'variant': var, 'rules': e['drc']['rules'], 'router_reported': 0, 'deck': 'sky130A full, euclidean'}),
                       result=float(e['drc']['count'] if e['drc']['count'] is not None else -1), units='violations', mapping_status='validated' if e['drc']['clean'] else 'implemented', evidence_level='measured', evidence_ref=ev,
                       notes=('magic finds %d violation(s) the router did not report: %s — a finding on the routed layout, stated' % (e['drc']['count'], '; '.join(e['drc']['rules'][:6]))) if not e['drc']['clean'] else 'magic\'s full deck agrees with the router: 0 violations on the whole design (no context rule excused)'))
        chars.append(C(name='lod3f: rv32_add layout-vs-schematic (%s)' % var, source_rung='layout', source_ref=lay_ref, target_rung='logic-netlist', target_ref='lod3/pnr/%s/6_final.v' % var,
                       characteristic='lvs_match', method='netgen -blackbox: extracted layout vs the routed Verilog', conditions_json=json.dumps({'variant': var, 'verdict': e['lvs'].get('verdict', []), 'mode': e['lvs'].get('mode', '')}),
                       result=1.0 if e['lvs'].get('match') else 0.0, units='match', mapping_status='validated' if e['lvs'].get('match') else 'implemented', evidence_level='measured', evidence_ref=ev,
                       notes='the routed wiring IS the routed netlist (instances, nets, pins)' if e['lvs'].get('match') else 'netgen did NOT match the layout to the netlist: %s' % '; '.join(e['lvs'].get('verdict', [])[:4])))
    return [], chars


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'run':
        vs = sys.argv[sys.argv.index('--variants') + 1].split(',') if '--variants' in sys.argv else None
        wk = sys.argv[sys.argv.index('--work') + 1] if '--work' in sys.argv else None
        print(json.dumps(run(vs, wk)['summary'], indent=1))
    else:
        r = report()
        print(json.dumps(r['summary'], indent=1) if r else 'no report yet: python3 -m computelod.custom.lod3_drc run')
