/*
 * pin_config.c — pin_config_init(): the fixed init order (DDR, PORT, EICRA, EIFR, EIMSK, PCMSKx, PCICR); sei() stays in main(), after every init, never here.
 *
 * GENERATED by Polari (cmod.custom.pin_config_gen) from Firmware Solution uno-sim-rig, graph uno-sim-rig-graph, board arduino-uno-r3, at render time (the exact
 * timestamp lives in the glue record, cmod/custom/glue_builds/uno-sim-rig-graph.json — never in this file, so a
 * re-render with nothing changed produces byte-identical output). EDIT THE MODEL (the pin claims /
 * register settings), never this file. No Polari is needed to build it: pin_config_init() is ordinary
 * avr-libc C, called once from main() before the hand-written HAL inits (POLARI_PIN_CONFIG=1 then
 * disables those same DDR/PORT/EICRA/EIFR/EIMSK writes in hal.c so the two never race).
 */

#include <avr/io.h>
#include <stdint.h>

#include "pin_config.h"

void pin_config_init(void)
{
    /* uno-sim-rig:DDRB:init = 00100000 (write_mask 0x20)
     *   DDB5     = 1     — the pin is configured as an output pin · claim uno-sim-rig:D13 · task led · rule ddr-from-digital-out
     */
    PIN_CONFIG_D13_DDR = (uint8_t)((PIN_CONFIG_D13_DDR & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D13_BIT))) | (((uint8_t)0x01 << PIN_CONFIG_D13_BIT)));   /* bits outside write_mask 0x20 keep the chip's
                                    reset value */

    /* uno-sim-rig:DDRD:init = 01000000 (write_mask 0x40)
     *   DDD6     = 1     — the pin is configured as an output pin · claim uno-sim-rig:D6 · task pwm_init · rule ddr-from-pwm-out
     */
    PIN_CONFIG_D6_DDR = (uint8_t)((PIN_CONFIG_D6_DDR & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D6_BIT))) | (((uint8_t)0x01 << PIN_CONFIG_D6_BIT)));   /* bits outside write_mask 0x40 keep the chip's
                                    reset value */
}

