/*
 * pin_config.h — the pin claims' register/bit facts, as #defines pin_config.c uses.
 *
 * GENERATED by Polari (cmod.custom.pin_config_gen) from Firmware Solution uno-sim-rig, graph uno-sim-rig-graph, board arduino-uno-r3, at render time (the exact
 * timestamp lives in the glue record, cmod/custom/glue_builds/uno-sim-rig-graph.json — never in this file, so a
 * re-render with nothing changed produces byte-identical output). EDIT THE MODEL (the pin claims /
 * register settings), never this file. No Polari is needed to build it: pin_config_init() is ordinary
 * avr-libc C, called once from main() before the hand-written HAL inits (POLARI_PIN_CONFIG=1 then
 * disables those same DDR/PORT/EICRA/EIFR/EIMSK writes in hal.c so the two never race).
 */

#ifndef POLARI_PIN_CONFIG_H
#define POLARI_PIN_CONFIG_H

/* one #define per claimed pin's register/bit fact pin_config.c uses — derived from the SocPin + 
 * RegisterField rows (board.custom.hardware_chain), never a bare bit number written below. */
#define PIN_CONFIG_D13_DDR               DDRB     /* the DDRB register pin claim uno-sim-rig:D13 touches */
#define PIN_CONFIG_D13_BIT               5        /* DDRB.DDB5's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D6_DDR                DDRD     /* the DDRD register pin claim uno-sim-rig:D6 touches */
#define PIN_CONFIG_D6_BIT                6        /* DDRD.DDD6's low bit (from the SocPin/RegisterField rows, never a bare number) */

void pin_config_init(void);

#endif /* POLARI_PIN_CONFIG_H */

