/*
 * polari_graph.h: the graph's identity, the frame masks, where every file came from — GENERATED by cmod.custom.glue 1 from the no-code graph uno-sim-rig-graph (sha256 e5ea718e89a45da51a08875efccced559a04f2e1640d8aad53cf77aa186b89b4).
 * Regenerate with `pol cmod render uno-sim-rig-graph`. Editing by hand is allowed: `pol cmod diff uno-sim-rig-graph` shows it, and a render
 * never overwrites a hand edit silently. Plain C on avr-libc (RULE 2); no Python at run time.
 */
#ifndef POLARI_GRAPH_H
#define POLARI_GRAPH_H

#include "simrigstate_packets.h"

#define POLARI_GRAPH_NAME   "uno-sim-rig-graph"
#define POLARI_GRAPH_SHA256 "e5ea718e89a45da51a08875efccced559a04f2e1640d8aad53cf77aa186b89b4"

/* frame node frame: the fields its telemetry carries */
#define FRAME_MASK ((SimRigState_mask_t)(SIMRIGSTATE_F_UPTIME_MS | SIMRIGSTATE_F_STATUS | SIMRIGSTATE_F_TEMP_C | SIMRIGSTATE_F_LED_ON | SIMRIGSTATE_F_PWM_DUTY | SIMRIGSTATE_F_NAME))

/* the files of this project (sha256 of the bytes written):
 *   hal.c                    978c2492405808c9  copied verbatim from board/custom/firmware/uno/hal.c
 *   hal.h                    58cfacfb3cad8403  copied verbatim from board/custom/firmware/uno/hal.h
 *   board_config.h           7501b89751a370e9  board gen: the uno-sim-rig knobs
 *   simrigstate_packets.h    6b748742dd2ca30a  c_twin target=avr, contract v2 2bcc9d1a2774ef33 (pinned board/custom/contracts/SimRigState.v2.json)
 *   pin_config.h             524fb5d0e230b9bb  GENERATED (cmod.custom.pin_config_gen) from uno-sim-rig's pin claims
 *   pin_config.c             ----------------  GENERATED (cmod.custom.pin_config_gen) from uno-sim-rig's pin claims
 *   polari_graph.c           ----------------  GENERATED (+ apps/sim_rig.sensor_value, apps/sim_rig.apply_command copied verbatim)
 */

#endif /* POLARI_GRAPH_H */
