/* Generated by Polari grpcbridge.custom.c_twin (grpc-j3) + c_twin_v2 (grpc-j4) — do not edit.
 * class: SimRigState   contract v2   hash 2bcc9d1a2774ef33   target avr
 * wire v2   hash2 aaac4dffda57c4cb   single instance: nothing to tell apart (presence bits only)   prelude 1 byte(s)
 * The struct carries FIELDS ONLY; the hardware-interface identity lives in the gRPC message and the binding row.
 * Regenerate when the contract, an enum mapping or the bindings change. */
#ifndef SIMRIGSTATE_PACKETS_H
#define SIMRIGSTATE_PACKETS_H

#ifndef POLARI_RX_PAYLOAD_MAX
#define POLARI_RX_PAYLOAD_MAX 93u
#endif

#ifndef POLARI_PACKET_V2_COMMON_H
#define POLARI_PACKET_V2_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#define POLARI_MAGIC       0x504CU  /* wire bytes: 0x4C 0x50 */
#define POLARI_VERSION     2U       /* wire v2: payload = prelude (packed index + presence) + present fields */
#define POLARI_VERSION_MIN 1U       /* v1 frames still parse (an old firmware / bridge) */
#define POLARI_VERSION_MAX 4U       /* v3: an explicit index byte; v4: an explicit 16-bit index (grpc-j4) */
#define POLARI_HEADER_LEN  12U

/* CRC32 (IEEE reflected, poly 0xEDB88320) — identical to
 * java.util.zip.CRC32 and Python zlib.crc32. Bitwise (no table):
 * cycles are cheap at telemetry rates, flash is not. */
static uint32_t polari_crc32(const uint8_t *d, size_t n)
{
    uint32_t c = 0xFFFFFFFFu;
    size_t i;
    int k;
    for (i = 0; i < n; i++) {
        c ^= d[i];
        for (k = 0; k < 8; k++)
            c = (c >> 1) ^ (0xEDB88320u
                            & (uint32_t)(-(int32_t)(c & 1u)));
    }
    return ~c;
}

static void polari_put_u16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
}

static void polari_put_u32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v;         p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static uint16_t polari_get_u16(const uint8_t *p)
{
    return (uint16_t)(p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t polari_get_u32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

/* Frame a payload into `out` (must hold POLARI_HEADER_LEN+len+4) with the given version byte. Returns the wire
 * length. A class header's <C>_frame() passes its own <C>_WIRE_VERSION. */
static size_t polari_packet_encode_v(uint8_t *out, uint8_t version, uint8_t msg_type,
                                     uint16_t device_id, uint32_t seq,
                                     const uint8_t *payload,
                                     uint16_t len)
{
    polari_put_u16(out, POLARI_MAGIC);
    out[2] = version;
    out[3] = msg_type;
    polari_put_u16(out + 4, device_id);
    polari_put_u32(out + 6, seq);
    polari_put_u16(out + 10, len);
    memcpy(out + POLARI_HEADER_LEN, payload, len);
    polari_put_u32(out + POLARI_HEADER_LEN + len,
                   polari_crc32(out, POLARI_HEADER_LEN + len));
    return POLARI_HEADER_LEN + (size_t)len + 4u;
}

typedef struct {
    uint8_t buf[POLARI_HEADER_LEN + POLARI_RX_PAYLOAD_MAX + 4u];
    size_t have;
    uint16_t need_payload;
    uint8_t version;
    uint8_t msg_type;
    uint16_t device_id;
    uint32_t sequence;
    const uint8_t *payload;
    uint16_t payload_len;
} polari_rx_t;

/* 1 = buf holds a complete CRC-valid frame, 0 = need more bytes, -1 = the candidate at buf[0] is no frame. */
static int polari_rx_check(polari_rx_t *rx)
{
    size_t total;
    if (rx->have >= 1u && rx->buf[0] != (uint8_t)(POLARI_MAGIC & 0xFFu)) return -1;
    if (rx->have >= 2u && rx->buf[1] != (uint8_t)(POLARI_MAGIC >> 8)) return -1;
    if (rx->have < POLARI_HEADER_LEN) return 0;
    if (rx->buf[2] < POLARI_VERSION_MIN || rx->buf[2] > POLARI_VERSION_MAX) return -1;
    rx->need_payload = polari_get_u16(rx->buf + 10);
    if (rx->need_payload > POLARI_RX_PAYLOAD_MAX) return -1;
    total = POLARI_HEADER_LEN + (size_t)rx->need_payload + 4u;
    if (rx->have < total) return 0;
    if (polari_get_u32(rx->buf + total - 4u) != polari_crc32(rx->buf, total - 4u)) return -1;
    return 1;
}

/* Feed one byte; returns 1 when rx holds a complete CRC-valid frame (version / msg_type / payload populated, valid
 * until the next feed). A rejected candidate is NOT thrown away: the parser slides to the next 0x4C among the bytes it
 * already holds and re-examines them, so a frame that starts inside garbage or inside a corrupted frame is kept. */
static int polari_rx_feed(polari_rx_t *rx, uint8_t b)
{
    size_t i;
    int r;
    rx->buf[rx->have++] = b;
    for (;;) {
        r = polari_rx_check(rx);
        if (r == 0) return 0;
        if (r == 1) {
            rx->version = rx->buf[2];
            rx->msg_type = rx->buf[3];
            rx->device_id = polari_get_u16(rx->buf + 4);
            rx->sequence = polari_get_u32(rx->buf + 6);
            rx->payload = rx->buf + POLARI_HEADER_LEN;
            rx->payload_len = rx->need_payload;
            rx->have = 0u;
            return 1;
        }
        for (i = 1u; i < rx->have && rx->buf[i] != (uint8_t)(POLARI_MAGIC & 0xFFu); i++) { }
        memmove(rx->buf, rx->buf + i, rx->have - i);
        rx->have -= i;
    }
}

#endif /* POLARI_PACKET_V2_COMMON_H */

#ifndef POLARI_AVR_DOUBLE_H
#define POLARI_AVR_DOUBLE_H

/* target=avr: avr-gcc's double is 4 bytes (binary32); the wire's double
 * is 8 (binary64). Converted here in software; the WIRE is unchanged. */
#ifdef POLARI_AVR_DOUBLE_TEST
typedef float polari_avr_double_t;   /* host-test shim: a 4-byte double */
#else
typedef double polari_avr_double_t;  /* avr-gcc default: double == float */
#endif
/* refuses to compile where double is not 4 bytes (-mdouble=64, a host) */
typedef char polari_avr_double_is_4_bytes[
    (sizeof(polari_avr_double_t) == 4u) ? 1 : -1];

/* binary32 -> binary64 bits; exact (every binary32 is a binary64). */
static void polari_f32_to_f64(polari_avr_double_t v, uint32_t *lo,
                              uint32_t *hi)
{
    uint32_t b, sign, man;
    int32_t exp;
    memcpy(&b, &v, 4);
    sign = b & 0x80000000UL;
    exp = (int32_t)((b >> 23) & 0xFFUL);
    man = b & 0x007FFFFFUL;
    if (exp == 0xFF) {                 /* inf / nan: payload kept */
        exp = 0x7FF;
    } else if (exp == 0) {
        if (man == 0UL) { *hi = sign; *lo = 0UL; return; }  /* +-0 */
        exp = 1 - 127;                 /* subnormal: normalise */
        while ((man & 0x00800000UL) == 0UL) { man <<= 1; exp--; }
        man &= 0x007FFFFFUL;
        exp += 1023;
    } else {
        exp += 1023 - 127;
    }
    *hi = sign | ((uint32_t)exp << 20) | (man >> 3);
    *lo = man << 29;
}

/* binary64 bits -> binary32: round to nearest, ties to even; overflow
 * -> inf, underflow -> subnormal or signed zero; nan stays quiet nan. */
static polari_avr_double_t polari_f64_to_f32(uint32_t lo, uint32_t hi)
{
    uint32_t sign = hi & 0x80000000UL, man, rest, out;
    int32_t exp = (int32_t)((hi >> 20) & 0x7FFUL);
    polari_avr_double_t v;
    man = ((hi & 0x000FFFFFUL) << 3) | (lo >> 29);  /* top 23 bits */
    rest = lo & 0x1FFFFFFFUL;                        /* the 29 below */
    if (exp == 0x7FF) {
        out = sign | 0x7F800000UL
            | ((man | rest) ? (0x00400000UL | man) : 0UL);
    } else if (exp == 0) {
        out = sign;                    /* binary64 subnormals: far below */
    } else {
        exp = exp - 1023 + 127;
        if (exp >= 0xFF) {
            out = sign | 0x7F800000UL;
        } else if (exp <= 0) {         /* a binary32 subnormal */
            uint32_t sig = man | 0x00800000UL;
            uint32_t shift = (uint32_t)(1 - exp), q, r, half;
            if (shift > 24UL) {
                out = sign;
            } else {
                q = sig >> shift;
                r = sig & (((uint32_t)1 << shift) - 1UL);
                half = (uint32_t)1 << (shift - 1UL);
                if (r > half || (r == half && (rest != 0UL || (q & 1UL))))
                    q++;               /* a carry to the smallest normal is correct */
                out = sign | q;
            }
        } else {
            out = sign | ((uint32_t)exp << 23) | man;
            if (rest > 0x10000000UL
                || (rest == 0x10000000UL && (man & 1UL)))
                out++;                 /* a carry into exp is correct; 0xFF = inf */
        }
    }
    memcpy(&v, &out, 4);
    return v;
}

#endif /* POLARI_AVR_DOUBLE_H */

#define SIMRIGSTATE_MSG_TYPE 1u
#define SIMRIGSTATE_PAYLOAD_MAX 93u
#define SIMRIGSTATE_WIRE_VERSION 2u
#define SIMRIGSTATE_PRELUDE_BYTES 1u
#define SIMRIGSTATE_HASH_V2 "aaac4dffda57c4cb"

typedef uint8_t SimRigState_mask_t;
#define SIMRIGSTATE_F_NAME ((SimRigState_mask_t)1u << 0)  /* name (string) */
#define SIMRIGSTATE_F_PWM_DUTY ((SimRigState_mask_t)1u << 1)  /* pwm_duty (int64) */
#define SIMRIGSTATE_F_STATUS ((SimRigState_mask_t)1u << 2)  /* status (string) */
#define SIMRIGSTATE_F_TEMP_C ((SimRigState_mask_t)1u << 3)  /* temp_c (double) */
#define SIMRIGSTATE_F_UPTIME_MS ((SimRigState_mask_t)1u << 4)  /* uptime_ms (int64) */
#define SIMRIGSTATE_F_LED_ON ((SimRigState_mask_t)1u << 5)  /* led_on (bool) */
#define SIMRIGSTATE_F_ALL ((SimRigState_mask_t)0x3fu)

/* enum mapping SimRigState.status (EnumMapping row): 1 byte on the wire */
enum {
    SIMRIGSTATE_STATUS_UNKNOWN = 0,
    SIMRIGSTATE_STATUS_BOOT = 1,
    SIMRIGSTATE_STATUS_OK = 2,
    SIMRIGSTATE_STATUS_COMMANDED = 3,
    SIMRIGSTATE_STATUS_ECHOED = 4,
    SIMRIGSTATE_STATUS_FAULT = 5
};
static inline const char *SimRigState_status_name(uint8_t v)
{
    switch (v) {
    case 1: return "boot";
    case 2: return "ok";
    case 3: return "commanded";
    case 4: return "echoed";
    case 5: return "fault";
    default: return "unknown";
    }
}

typedef struct {
    char name[64];
    int64_t pwm_duty;
    uint8_t status;  /* enum: SIMRIGSTATE_STATUS_* (0 = unknown) */
    polari_avr_double_t temp_c;
    int64_t uptime_ms;
    uint8_t led_on;
} SimRigState_t;

/* struct -> payload: the prelude (presence bits) + ONLY the fields set in `present`. */
static uint16_t SimRigState_encode(const SimRigState_t *s, uint8_t *p,
                                    SimRigState_mask_t present)
{
    uint8_t *start = p;
    uint8_t pre;
    uint16_t n;
    uint32_t lo, hi;
    (void)n;
    present &= SIMRIGSTATE_F_ALL;
    pre = (uint8_t)present;
    p[0] = (uint8_t)pre;
    p += 1;
    if (present & SIMRIGSTATE_F_NAME) {
        n = (uint16_t)strlen(s->name);
        polari_put_u16(p, n); p += 2;
        memcpy(p, s->name, n); p += n;
    }
    if (present & SIMRIGSTATE_F_PWM_DUTY) {
        polari_put_u32(p, (uint32_t)s->pwm_duty);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->pwm_duty >> 32)); p += 8;
    }
    if (present & SIMRIGSTATE_F_STATUS) { *p++ = s->status; }
    if (present & SIMRIGSTATE_F_TEMP_C) {
        polari_f32_to_f64(s->temp_c, &lo, &hi);
        polari_put_u32(p, lo); polari_put_u32(p + 4, hi); p += 8;  /* binary32 -> binary64 (target avr) */
    }
    if (present & SIMRIGSTATE_F_UPTIME_MS) {
        polari_put_u32(p, (uint32_t)s->uptime_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->uptime_ms >> 32)); p += 8;
    }
    if (present & SIMRIGSTATE_F_LED_ON) { *p++ = s->led_on ? 1u : 0u; }
    return (uint16_t)(p - start);
}

/* payload -> struct: ONLY the present fields are written (a partial command leaves the rest alone).
 * Returns 0, or -1 on truncated input. present may be NULL. */
static int SimRigState_decode(const uint8_t *p, uint16_t len, SimRigState_t *s,
                               SimRigState_mask_t *present)
{
    const uint8_t *end = p + len;
    uint8_t pre;
    SimRigState_mask_t m;
    uint16_t n, cp;
    (void)n; (void)cp;
    if (len < SIMRIGSTATE_PRELUDE_BYTES) return -1;
    pre = (uint8_t)((uint8_t)p[0]);
    p += 1;
    m = (SimRigState_mask_t)(pre >> 0) & SIMRIGSTATE_F_ALL;
    if (present) *present = m;
    if (m & SIMRIGSTATE_F_NAME) {
        if (end - p < 2) return -1;
        n = polari_get_u16(p); p += 2;
        if ((uint16_t)(end - p) < n) return -1;
        cp = n < 63u ? n : 63u;
        memcpy(s->name, p, cp); s->name[cp] = 0; p += n;
    }
    if (m & SIMRIGSTATE_F_PWM_DUTY) {
        if (end - p < 8) return -1;
        s->pwm_duty = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & SIMRIGSTATE_F_STATUS) {
        if (end - p < 1) return -1;
        s->status = *p++;
    }
    if (m & SIMRIGSTATE_F_TEMP_C) {
        if (end - p < 8) return -1;
        s->temp_c = polari_f64_to_f32(polari_get_u32(p), polari_get_u32(p + 4)); p += 8;
    }
    if (m & SIMRIGSTATE_F_UPTIME_MS) {
        if (end - p < 8) return -1;
        s->uptime_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & SIMRIGSTATE_F_LED_ON) {
        if (end - p < 1) return -1;
        s->led_on = (*p++ != 0u);
    }
    return 0;
}

/* decode a parsed frame: -2 for any other version (a v1 frame from an old bridge, another index representation):
 * refused, never misread */
static int SimRigState_decode_rx(const polari_rx_t *rx, SimRigState_t *s,
                                  SimRigState_mask_t *present)
{
    if (rx->version != SIMRIGSTATE_WIRE_VERSION) return -2;
    return SimRigState_decode(rx->payload, rx->payload_len, s, present);
}

/* frame a payload with this class's version byte and msg_type */
static size_t SimRigState_frame(uint8_t *out, uint16_t device_id, uint32_t seq,
                                 const uint8_t *payload, uint16_t len)
{
    return polari_packet_encode_v(out, SIMRIGSTATE_WIRE_VERSION, SIMRIGSTATE_MSG_TYPE, device_id, seq, payload, len);
}

#endif /* SIMRIGSTATE_PACKETS_H */
