/* Generated by Polari hwfpga.fpga_verilog from register map "hardware-runtime" — do not edit; edit the rows. */
#ifndef HARDWARE_RUNTIME_REGS_H
#define HARDWARE_RUNTIME_REGS_H

#define FPGA_BASE 0x70000000u
#define FPGA_REG(off) (*(volatile unsigned int *)(FPGA_BASE + (off)))

#define FPGA_DEVICE_ID_OFFSET 0x0000u  /* const: Identity ('PL' + board 1) — hardwired. */
#define FPGA_DEVICE_ID_VALUE 0x504C0001u
#define FPGA_VERSION_OFFSET 0x0004u  /* const: Register-map version 1.0 — hardwired. */
#define FPGA_VERSION_VALUE 0x00010000u
#define FPGA_STATUS_OFFSET 0x0008u  /* ro: Live status: [15:0] heartbeat counter (liveness), [23:16] the MUX-selected input byte. */
#define FPGA_FAULTS_OFFSET 0x000Cu  /* ro: Fault flags (none modeled yet — honest zero). */
#define FPGA_COMMANDS_OFFSET 0x0010u  /* rw: Command word from the MCU / Polari. */
#define FPGA_CONFIG_OFFSET 0x0020u  /* rw: Configuration word. */
#define FPGA_MODE_MUX_OFFSET 0x0024u  /* rw: Input-source select (a real multiplexer): bit0 0=sim counter, 1=hardware input pins. */
#define FPGA_LED_MATRIX_OFFSET 0x0030u  /* rw: 4x4 LED matrix: bit(row*4+col) lights LED (row, col); the low 16 bits drive pins. */

#endif
