// Generated by Polari hwfpga.fpga_verilog — SIMULATION-ONLY
// wrapper: Renode's IntegrationLibrary AxiLite driver binds 64-bit
// channel signals; the real-FPGA artifact is polari_regblock.v.
module top (
    input  wire        clk,
    input  wire        rst,
    input  wire [63:0] awaddr,
    input  wire        awvalid,
    output wire        awready,
    input  wire [2:0]  awprot,
    input  wire [63:0] wdata,
    input  wire [3:0]  wstrb,
    input  wire        wvalid,
    output wire        wready,
    output wire [1:0]  bresp,
    output wire        bvalid,
    input  wire        bready,
    input  wire [63:0] araddr,
    input  wire        arvalid,
    output wire        arready,
    input  wire [2:0]  arprot,
    output wire [63:0] rdata,
    output wire [1:0]  rresp,
    output wire        rvalid,
    input  wire        rready
);
    wire [31:0] rdata32;
    assign rdata = {32'h0, rdata32};
    wire [15:0] led_matrix_pins_obs;

    polari_regblock dut (
        .clk(clk), .rst(rst),
        .awaddr(awaddr[31:0]), .awvalid(awvalid), .awready(awready),
        .wdata(wdata[31:0]), .wstrb(wstrb), .wvalid(wvalid),
        .wready(wready),
        .bresp(bresp), .bvalid(bvalid), .bready(bready),
        .araddr(araddr[31:0]), .arvalid(arvalid), .arready(arready),
        .rdata(rdata32), .rresp(rresp), .rvalid(rvalid),
        .rready(rready),
        // the "hardware pins" in simulation: a fixed stub pattern
        .hw_pin_in(8'hB7),
        .led_matrix_pins(led_matrix_pins_obs)
    );
endmodule
