"""
@module appstore.shell_project

The generated-download path (plan A5). The instance cannot
cross-compile, and the grpcbridge text-only tarball cannot carry a
binary gradle-wrapper.jar — so the honest design is OVERLAY, not
generation: the shell repo's `./gradlew srcDistTar` archive (built
out-of-band, uploaded to MinIO via /api/appstore/artifacts) is
fetched and the per-download files — config/polari-shell.json (the
S1 registration document) + README.md — are overlaid into it
deterministically (sorted entries, mtime=0, fixed owners — the
grpcbridge tarball discipline, bytes-safe).

overlay_tar_gz is pure (bytes in, bytes out) so determinism is
selftestable without MinIO.
"""

import hashlib
import io
import json
import tarfile

from appstore.appstore_minio import get_bytes, store_status
from appstore.appstore_tokens import now_iso


def _readme(shell_row, doc):
    inst = (doc.get('instances') or [{}])[0]
    enrolled = 'baked in (single-use — redeemed on first launch)' \
        if doc.get('enrollment') else \
        'not baked in — register via polari:// deep link or the ' \
        'first-run wizard'
    return f"""# {getattr(shell_row, 'title', 'Polari')} — app shell

Generated by the Polari App Store on {now_iso()}.

- Instance: {inst.get('id', '')} ({inst.get('webUrl', '')})
- Scope: {doc.get('app', {}).get('scope', '')}
- Enrollment: {enrolled}

Build and run (Linux x64, any JDK >= 17 — the Gradle toolchain
fetches the right compiler):

    ./gradlew :desktop:run

The registration document is `config/polari-shell.json`; the build
bakes it onto the classpath. The same shell also accepts a sidecar
`polari-shell.json` next to the launcher, a polari:// deep link, or
manual entry — first hit wins, later sources only ADD instances.
"""


def overlay_tar_gz(archive_bytes, extra_files):
    """Overlay {relpath: text} onto a .tar.gz, deterministically.

    Entries are re-emitted sorted with mtime=0/uid=gid=0 (so the
    SAME archive + SAME extras -> byte-identical output no matter
    when it runs); extras are placed under the archive's single root
    directory, replacing any same-named entry."""
    src = tarfile.open(fileobj=io.BytesIO(archive_bytes), mode='r:gz')
    try:
        members = [(m, src.extractfile(m).read() if m.isfile() else b'')
                   for m in src.getmembers()]
    finally:
        src.close()
    if not members:
        return {'ok': False, 'error': 'source archive is empty'}
    root = members[0][0].name.split('/', 1)[0]
    entries = {}
    for member, data in members:
        entries[member.name] = (member, data)
    for relpath in extra_files:
        name = f'{root}/{relpath}'
        info = tarfile.TarInfo(name=name)
        data = extra_files[relpath].encode('utf-8')
        info.size = len(data)
        info.mode = 0o644
        entries[name] = (info, data)
    buf = io.BytesIO()
    # mtime=0 on the GzipFile too — gzip stamps a header timestamp
    # that would break byte-determinism even with fixed tar mtimes.
    import gzip
    with gzip.GzipFile(fileobj=buf, mode='wb', mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode='w') as tar:
            for name in sorted(entries):
                info, data = entries[name]
                info.mtime = 0
                info.uid = info.gid = 0
                info.uname = info.gname = ''
                if info.isfile():
                    tar.addfile(info, io.BytesIO(data))
                else:
                    tar.addfile(info)
    return {'ok': True, 'data': buf.getvalue(), 'root': root}


def overlay_manifest(extra_files):
    """path -> sha256 of what this download overlaid (the stamp)."""
    return {path: hashlib.sha256(text.encode('utf-8')).hexdigest()
            for path, text in extra_files.items()}


def build_download(manager, shell_row, artifact_row, doc):
    """Fetch the stored source archive and overlay the registration.
    -> {'ok', data, filename, manifest} | honest refusal."""
    if artifact_row is None:
        status = store_status(manager)
        return {'ok': False,
                'error': 'no source archive uploaded for this shell',
                'storeConnected': status.get('connected', False),
                'suggestion': {
                    'knob': 'POST /api/appstore/artifacts',
                    'action': 'build `./gradlew srcDistTar` in '
                              'polari-app-shell, then presign-put + '
                              'commit the archive for platform '
                              'gradle-project'}}
    fetched = get_bytes(manager, getattr(artifact_row, 'object_key', ''),
                        getattr(artifact_row, 'bucket', '') or
                        'shell-artifacts')
    if not fetched.get('ok'):
        return fetched
    extras = {
        'config/polari-shell.json': json.dumps(
            {k: v for k, v in doc.items() if k != 'ok'},
            indent=2, sort_keys=True),
        'README.md': _readme(shell_row, doc),
    }
    result = overlay_tar_gz(fetched['data'], extras)
    if not result.get('ok'):
        return result
    shell = getattr(shell_row, 'name', 'polari-shell')
    return {'ok': True, 'data': result['data'],
            'filename': f'{shell}-gradle-project.tar.gz',
            'manifest': overlay_manifest(extras)}


def stamp_generation(manager, artifact_row, manifest):
    """Record what was overlaid on the artifact row (grpcbridge
    idiom: the manifest persists, the artifact is rebuilt)."""
    artifact_row.manifest_json = json.dumps(manifest, sort_keys=True)
    artifact_row.last_generated_at = now_iso()
    try:
        manager.db.saveInstanceInDB(artifact_row)
    except Exception:
        pass
