"""board_button_clock_selftest — ucd-0e1 (UNO_CORE_DEMO_PLAN.md §1/§5g): THE WIRE CONTRACT of the button-clock demo.
Proves the two new wire classes (ButtonClockState: telemetry + SET_TIME/SET_LED/SNAPSHOT commands; ButtonClockEvent:
telemetry only) exist, are registered the way UnoAnalogState is, and that the SAME generator (board.custom.gen /
grpcbridge.custom.c_twin_v2) renders their C headers from the pinned contract snapshot — no hand-written header.
ucd-0e2 (`apps/button_clock.c`, variant uno-button-clock) is proven separately in
board.board_button_clock_twin_selftest — this file's own checks (the wire contract itself) are unchanged by it; only
`_no_app_checks` below was updated to match 0e2's new reality (the pairing it used to prove absent now exists).

    PYTHONPATH=.:modules python3 -m board.board_button_clock_selftest      # from polari-framework/ (standalone)
    (called by board.board_selftest as run_button_clock(check))
"""
import json
import re


def _construct():
    from board.board_basis import ButtonClockState, ButtonClockEvent
    s = ButtonClockState(name='uno-clock', seq=5, boot_session=9, uptime_ms=12345, epoch_s=1760000000, ms=250,
                        clock_synced=True, sync_generation=2, sync_uncertainty_ms=50, drift_ms=-120,
                        button_presses=3, led_on=True, led_changed_at=1760000001, sense_rises=2, sense_falls=1,
                        last_edge_at=1760000002, last_edge_ms=10, dropped_events=0, status='synced',
                        set_epoch_s=0, set_ms=0, set_sync_generation=0, set_led=False, snapshot=False)
    e = ButtonClockEvent(name='uno-clock-7', seq=7, boot_session=9, kind='press', uptime_ms=12300, epoch_s=1759999999,
                        ms=900)
    return s, e


def run_button_clock(check):
    from board.board_basis import BOARD_CLASSES, ButtonClockState, ButtonClockEvent
    from board.board_seed import BOARD_SEED_PAIRS
    from board.custom import gen, compat

    s, e = _construct()
    check('ucd-0e1: ButtonClockState constructs with every telemetry + command field, no stray field',
          s.name == 'uno-clock' and s.seq == 5 and s.boot_session == 9 and s.clock_synced is True
          and s.sync_generation == 2 and s.sync_uncertainty_ms == 50 and s.drift_ms == -120 and s.led_on is True
          and s.status == 'synced' and s.set_led is False and s.snapshot is False)
    check('ucd-0e1: ButtonClockEvent constructs telemetry-only (no command field exists on the class)',
          e.kind == 'press' and e.boot_session == 9 and not hasattr(e, 'set_led') and not hasattr(e, 'snapshot'))
    check('ucd-0e1: boot_session is a field on BOTH new classes (the bridge\'s reboot-vs-reconnect rule reads it '
          'from either stream)', hasattr(s, 'boot_session') and hasattr(e, 'boot_session'))
    check('ucd-0e1: both classes registered in BOARD_CLASSES (the third and fourth wire classes)',
          ButtonClockState in BOARD_CLASSES and ButtonClockEvent in BOARD_CLASSES)
    check('ucd-0e1: both classes are OBSERVED, never seeded (empty rows, like UnoAnalogState)',
          all(not rows for n, _, rows in BOARD_SEED_PAIRS if n in ('ButtonClockState', 'ButtonClockEvent')))

    # --- the pinned contract snapshot (the same idiom as UnoAnalogState.v1.json: a throwaway in-process server, one
    # seeded row, stabilize, enable -> v1, tags alphabetical) ---------------------------------------------------
    cs, path_s = gen.pinned_contract('ButtonClockState')
    ce, path_e = gen.pinned_contract('ButtonClockEvent')
    check('ucd-0e1: ButtonClockState pinned contract v1 — 24 fields, tags assigned ALPHABETICALLY (the framework\'s '
          'own rule, proto_gen.merge_field_map), boot_session first',
          cs['contract_version'] == 1 and len(cs['field_map']['fields']) == 24
          and compat.tag_order(cs['field_map']) == sorted(cs['field_map']['fields'])
          and compat.tag_order(cs['field_map'])[0] == 'boot_session')
    check('ucd-0e1: ButtonClockEvent pinned contract v1 — 7 fields, tags alphabetical',
          ce['contract_version'] == 1 and len(ce['field_map']['fields']) == 7
          and compat.tag_order(ce['field_map']) == sorted(ce['field_map']['fields']))
    check('ucd-0e1: the command fields are ordinary presence-masked fields on the contract (SimRigState\'s '
          'led_on/pwm_duty idiom) — set_epoch_s/set_ms/set_sync_generation/set_led/snapshot are all present, typed '
          'int64 except the two bools',
          all(f in cs['field_map']['fields'] for f in
              ('set_epoch_s', 'set_ms', 'set_sync_generation', 'set_led', 'snapshot'))
          and cs['field_map']['fields']['set_epoch_s']['proto_type'] == 'int64'
          and cs['field_map']['fields']['set_led']['proto_type'] == 'bool'
          and cs['field_map']['fields']['snapshot']['proto_type'] == 'bool')

    # --- the C header: generated by board.custom.gen / grpcbridge.custom.c_twin_v2 — the SAME generator
    # SimRigState/UnoAnalogState go through; rendered OFFLINE from the pinned contract (no manager, no --api), so
    # nothing here is hand-written. No apps/button_clock.c exists yet (0e2's job) — proven directly, not via
    # `pol board gen uno --class ...` (which needs that app). -----------------------------------------------------
    text_s, prov_s = gen.header('ButtonClockState', msg_type=1)
    text_e, prov_e = gen.header('ButtonClockEvent', msg_type=2)
    check('ucd-0e1: ButtonClockState header comes from the pinned snapshot, target avr, msg_type 1',
          prov_s['source'] == 'pinned' and 'target avr' in text_s and 'BUTTONCLOCKSTATE_MSG_TYPE 1u' in text_s)
    check('ucd-0e1: ButtonClockEvent header comes from the pinned snapshot, target avr, msg_type 2',
          prov_e['source'] == 'pinned' and 'target avr' in text_e and 'BUTTONCLOCKEVENT_MSG_TYPE 2u' in text_e)

    m = re.search(r'typedef struct \{(.*?)\} ButtonClockState_t;', text_s, re.S)
    struct_s = m.group(1)
    check('ucd-0e1: ButtonClockState_t declares every field with the C type the generator\'s type table gives '
          'ints (int64_t — the framework\'s ONE integer wire width today; see the report\'s named gap), bools as '
          'uint8_t, strings as a fixed char buffer, status as the enum byte',
          'int64_t boot_session;' in struct_s and 'int64_t seq;' in struct_s and 'int64_t uptime_ms;' in struct_s
          and 'int64_t epoch_s;' in struct_s and 'int64_t ms;' in struct_s and 'uint8_t clock_synced;' in struct_s
          and 'int64_t sync_generation;' in struct_s and 'int64_t sync_uncertainty_ms;' in struct_s
          and 'int64_t drift_ms;' in struct_s and 'int64_t button_presses;' in struct_s
          and 'uint8_t led_on;' in struct_s and 'int64_t led_changed_at;' in struct_s
          and 'int64_t sense_rises;' in struct_s and 'int64_t sense_falls;' in struct_s
          and 'int64_t last_edge_at;' in struct_s and 'int64_t last_edge_ms;' in struct_s
          and 'int64_t dropped_events;' in struct_s and 'uint8_t status;' in struct_s
          and 'char name[64];' in struct_s)
    check('ucd-0e1: ButtonClockState_t carries the three command fields of SET_TIME + the SET_LED/SNAPSHOT bools',
          'int64_t set_epoch_s;' in struct_s and 'int64_t set_ms;' in struct_s
          and 'int64_t set_sync_generation;' in struct_s and 'uint8_t set_led;' in struct_s
          and 'uint8_t snapshot;' in struct_s)
    check('ucd-0e1: the command decode is the SAME presence-masked mechanism as any telemetry field — one '
          '"if (m & BUTTONCLOCKSTATE_F_SET_LED)" branch per command field, no second message kind',
          all('if (m & BUTTONCLOCKSTATE_F_%s)' % f.upper() in text_s
              for f in ('set_epoch_s', 'set_ms', 'set_sync_generation', 'set_led', 'snapshot')))
    check('ucd-0e1: ButtonClockState.status is the enum (idle|commanded|synced|snapshot), 1 wire byte',
          'BUTTONCLOCKSTATE_STATUS_IDLE = 1' in text_s and 'BUTTONCLOCKSTATE_STATUS_COMMANDED = 2' in text_s
          and 'BUTTONCLOCKSTATE_STATUS_SYNCED = 3' in text_s and 'BUTTONCLOCKSTATE_STATUS_SNAPSHOT = 4' in text_s)

    m2 = re.search(r'typedef struct \{(.*?)\} ButtonClockEvent_t;', text_e, re.S)
    struct_e = m2.group(1)
    check('ucd-0e1: ButtonClockEvent_t — telemetry only, no command field, boot_session present',
          'int64_t boot_session;' in struct_e and 'int64_t seq;' in struct_e and 'uint8_t kind;' in struct_e
          and 'int64_t uptime_ms;' in struct_e and 'int64_t epoch_s;' in struct_e and 'int64_t ms;' in struct_e
          and 'set_' not in struct_e and 'snapshot' not in struct_e)
    check('ucd-0e1: ButtonClockEvent.kind is the enum (press|led_on|led_off|sense_rise|sense_fall|sync)',
          'BUTTONCLOCKEVENT_KIND_PRESS = 1' in text_e and 'BUTTONCLOCKEVENT_KIND_LED_ON = 2' in text_e
          and 'BUTTONCLOCKEVENT_KIND_LED_OFF = 3' in text_e and 'BUTTONCLOCKEVENT_KIND_SENSE_RISE = 4' in text_e
          and 'BUTTONCLOCKEVENT_KIND_SENSE_FALL = 5' in text_e and 'BUTTONCLOCKEVENT_KIND_SYNC = 6' in text_e)

    # --- compat: this server's OWN pinned header is compatible with itself (no manager => the pinned snapshot
    # stands in on both sides, exactly the brd-fi idiom UnoAnalogState proves) -------------------------------------
    build = {'classes_json': json.dumps([
        {'class': 'ButtonClockState', 'msg_type': 1, 'target': 'avr', 'header_sha256': gen.sha256(text_s),
         'wire': 2, 'bridge': '', 'hash_v2': prov_s['hash_v2'], 'contract_hash': prov_s['contract_hash']},
        {'class': 'ButtonClockEvent', 'msg_type': 2, 'target': 'avr', 'header_sha256': gen.sha256(text_e),
         'wire': 2, 'bridge': '', 'hash_v2': prov_e['hash_v2'], 'contract_hash': prov_e['contract_hash']},
    ]), 'tag_order_json': json.dumps({'ButtonClockState': prov_s['tag_order'], 'ButtonClockEvent': prov_e['tag_order']})}
    rep = compat.check(build)
    check('ucd-0e1: compat.check over a build of both classes verdicts compatible (byte-identical to what this '
          'server generates now)', rep['verdict'] == 'compatible', rep['plain'])

    _no_app_checks(check)


def _no_app_checks(check):
    """ucd-0e2 BUILT the app (apps/button_clock.c, variant uno-button-clock): the pairing `pol board gen uno --class
    ButtonClockState --class ButtonClockEvent` (0e1 left refused, named "0e2's job") now succeeds for the PAIR the
    app is written for, through a fresh generate — the standalone board.board_button_clock_twin_selftest proves the
    built firmware on the twin. A single class alone (neither app pairing) still refuses, named — the rule that
    protected this slice ("a generated header alone is not firmware") still holds for a request that is not this
    app's exact class list."""
    import tempfile
    from board.custom import gen, variants as V
    work = tempfile.mkdtemp(prefix='ucd-0e2-no-app-check-')
    row = gen.gen('uno', ['ButtonClockState', 'ButtonClockEvent'], work)
    check('ucd-0e2: `pol board gen uno --class ButtonClockState --class ButtonClockEvent` now SUCCEEDS (variant %s, '
          'app button_clock) — the pairing ucd-0e1 left for this slice' % row.get('variant'),
          row.get('state') == 'generated' and row.get('variant') == 'uno-button-clock')
    try:
        gen.gen('uno', ['ButtonClockState'])
        ok = False
        why = '(no refusal — unexpected: a single class alone should still need its own app)'
    except gen.GenRefused as exc:
        ok = 'needs its own template app' in str(exc)
        why = str(exc)
    check('ucd-0e2: ButtonClockState ALONE (not the pair button_clock is written for) still REFUSES, named', ok, why)
    check('ucd-0e2: APP_CLASSES now pairs button_clock with EXACTLY (ButtonClockState, ButtonClockEvent)',
          V.APP_CLASSES.get('button_clock') == ('ButtonClockState', 'ButtonClockEvent'))


if __name__ == '__main__':
    passed = total = 0

    def check(label, cond, extra=''):
        global passed, total
        total += 1
        passed += bool(cond)
        print('  [%s] %s %s' % ('PASS' if cond else 'FAIL', label, extra if not cond else ''))

    run_button_clock(check)
    print('\n%d/%d checks passed' % (passed, total))
    raise SystemExit(0 if passed == total else 1)
