"""
@module hwfpga.fpga_verilog

Generators for hwsim-3: every artifact derives from the
RegisterMapDefinition + RegisterDefinition ROWS (the knobs) —
editing a register row reprograms the component at every layer:

  render_core      -> polari_regblock.v  (synthesizable 32-bit
                      AXI4-Lite slave — the real-FPGA artifact)
  render_sim_top   -> top.v              (sim-only wrapper with the
                      64-bit channel ports Renode's
                      IntegrationLibrary AxiLite driver binds)
  render_sim_main  -> sim_main.cpp       (the co-simulation harness:
                      Init/connect/simulate against Renode)
  render_c_defines -> <map>_regs.h       (firmware offsets twin)
  render_testbench -> tb.sv              (self-checking bench for
                      verilator --binary: consts, rw readback,
                      heartbeat liveness, the mode-MUX select)

The block's fixed logic: STATUS[15:0] = heartbeat (liveness),
STATUS[23:16] = the MUX-selected input byte — MODE_MUX bit0 selects
source 0 (free-running sim counter) or 1 (hardware input pins), a
real multiplexer whose select bits are a Polari knob.

@consumers
  - hwfpga.fpga_api (download endpoints)
  - hwfpga.selftest_fpga
  - grpcbridge/renode_twin/fpga (build script fetches these)
"""


def map_registers(manager, map_name):
    """This map's registers in offset order (rows = the knobs)."""
    tables = getattr(manager, 'objectTables', None) or {}
    rows = [r for r in (tables.get('RegisterDefinition') or {}).values()
            if getattr(r, 'map_name', '') == map_name]
    rows.sort(key=lambda r: int(getattr(r, 'offset', 0)))
    return rows


def get_map(manager, map_name):
    tables = getattr(manager, 'objectTables', None) or {}
    for row in (tables.get('RegisterMapDefinition') or {}).values():
        if getattr(row, 'name', '') == map_name:
            return row
    return None


def _reg_specs(registers):
    return [(getattr(r, 'register', ''), int(getattr(r, 'offset', 0)),
             getattr(r, 'access', 'rw'),
             int(getattr(r, 'reset_value', 0)) & 0xFFFFFFFF,
             getattr(r, 'description', ''),
             int(getattr(r, 'pins_out', 0) or 0)) for r in registers]


def render_core(map_row, registers):
    """The synthesizable 32-bit AXI4-Lite register block."""
    specs = _reg_specs(registers)
    decls, resets, wcases, rcases = [], [], [], []
    pin_ports, pin_assigns = [], []
    for name, offset, access, reset, desc, pins in specs:
        lname = name.lower()
        if access == 'rw':
            decls.append(f'    reg  [31:0] r_{lname};'
                         f'  // 0x{offset:04X} {desc}')
            resets.append(f"            r_{lname} <= 32'h{reset:08X};")
            wcases.append(f"                8'h{offset & 0xFF:02X}: "
                          f'r_{lname} <= wdata;')
            rcases.append(f"                8'h{offset & 0xFF:02X}: "
                          f'rdata <= r_{lname};')
        elif access == 'const':
            rcases.append(f"                8'h{offset & 0xFF:02X}: "
                          f"rdata <= 32'h{reset:08X};"
                          f'  // {name} (hardwired)')
        else:  # ro — logic-driven
            rcases.append(f"                8'h{offset & 0xFF:02X}: "
                          f'rdata <= v_{lname};')
        if pins > 0 and access == 'rw':
            pin_ports.append(
                f',\n    // {name} low {pins} bits drive pins '
                f'(pins_out knob on the row)\n'
                f'    output wire [{pins - 1}:0] {lname}_pins')
            pin_assigns.append(
                f'    assign {lname}_pins = r_{lname}[{pins - 1}:0];')
    nl = '\n'
    return f'''// Generated by Polari hwfpga.fpga_verilog from register map
// "{map_row.name}" — do not edit; edit the RegisterDefinition rows
// (the knobs) and regenerate. Synthesizable 32-bit AXI4-Lite slave.
module polari_regblock (
    input  wire        clk,
    // ACTIVE-LOW reset (Renode IntegrationLibrary convention: its
    // AxiLite driver pulses rst=0 at attach and leaves rst=1 to run).
    input  wire        rst,
    input  wire [31:0] awaddr,
    input  wire        awvalid,
    output reg         awready,
    input  wire [31:0] wdata,
    input  wire [3:0]  wstrb,
    input  wire        wvalid,
    output reg         wready,
    output reg  [1:0]  bresp,
    output reg         bvalid,
    input  wire        bready,
    input  wire [31:0] araddr,
    input  wire        arvalid,
    output reg         arready,
    output reg  [31:0] rdata,
    output reg  [1:0]  rresp,
    output reg         rvalid,
    input  wire        rready,
    // The mode MUX's source-1 input: real pins on silicon, a stub
    // pattern in simulation.
    input  wire [7:0]  hw_pin_in{''.join(pin_ports)}
);
{nl.join(decls)}
{nl.join(pin_assigns)}

    // Fixed logic: liveness heartbeat + the two MUX input sources.
    reg  [15:0] heartbeat;
    reg  [7:0]  sim_counter;
    // THE MUX (select bits = the MODE_MUX knob's bit0):
    wire [7:0]  mux_in = r_mode_mux[0] ? hw_pin_in : sim_counter;
    wire [31:0] v_status = {{8'h00, mux_in, heartbeat}};
    wire [31:0] v_faults = 32'h0;

    wire in_reset = ~rst;

    always @(posedge clk) begin
        if (in_reset) begin
            heartbeat   <= 16'h0;
            sim_counter <= 8'h0;
        end else begin
            heartbeat   <= heartbeat + 16'h1;
            sim_counter <= sim_counter + 8'h1;
        end
    end

    // Write: independent AW / W handshakes (the IntegrationLibrary
    // driver raises them sequentially), commit when both latched.
    reg        aw_got, w_got;
    reg [7:0]  waddr_l;
    reg [31:0] wdata_l;
    always @(posedge clk) begin
        if (in_reset) begin
            awready <= 1'b0; wready <= 1'b0; bvalid <= 1'b0;
            bresp <= 2'b00; aw_got <= 1'b0; w_got <= 1'b0;
            waddr_l <= 8'h0; wdata_l <= 32'h0;
{nl.join(resets)}
        end else begin
            if (awvalid && !aw_got && !awready) begin
                awready <= 1'b1;
                waddr_l <= awaddr[7:0];
                aw_got  <= 1'b1;
            end else begin
                awready <= 1'b0;
            end
            if (wvalid && !w_got && !wready) begin
                wready  <= 1'b1;
                wdata_l <= wdata;
                w_got   <= 1'b1;
            end else begin
                wready <= 1'b0;
            end
            if (aw_got && w_got && !bvalid) begin
                case (waddr_l)
{nl.join(wcases)}
                    default: ;  // ro/const/unmapped: write ignored
                endcase
                bvalid <= 1'b1;
                bresp  <= 2'b00;
                aw_got <= 1'b0;
                w_got  <= 1'b0;
            end else if (bvalid && bready) begin
                bvalid <= 1'b0;
            end
        end
    end

    // Read: latch on the AR handshake cycle, hold rvalid until rready.
    always @(posedge clk) begin
        if (in_reset) begin
            arready <= 1'b0; rvalid <= 1'b0;
            rdata <= 32'h0; rresp <= 2'b00;
        end else begin
            if (arvalid && !rvalid && !arready) begin
                arready <= 1'b1;
            end else begin
                arready <= 1'b0;
            end
            if (arready && arvalid && !rvalid) begin
                rvalid <= 1'b1;
                rresp  <= 2'b00;
                case (araddr[7:0])
{nl.join(rcases)}
                    default: rdata <= 32'h00000000;
                endcase
            end else if (rvalid && rready) begin
                rvalid <= 1'b0;
            end
        end
    end
endmodule
'''


#: The hardware-pin stub pattern driven in simulation (source 1 of
#: the MUX) — a constant so it is visibly distinct from the counter.
SIM_HW_PIN_PATTERN = 0xB7


def render_sim_top(registers=None):
    """Sim-only wrapper: 64-bit channel ports (what the Renode
    IntegrationLibrary's AxiLite driver binds — setSignal<uint64_t>),
    feeding the synthesizable 32-bit core. Output pins dangle onto
    observe-only wires (readback proves their state over the bus)."""
    pin_wires = pin_conns = ''
    for name, _o, access, _r, _d, pins in _reg_specs(registers or []):
        if pins > 0 and access == 'rw':
            lname = name.lower()
            pin_wires += (f'    wire [{pins - 1}:0] '
                          f'{lname}_pins_obs;\n')
            pin_conns += (f',\n        '
                          f'.{lname}_pins({lname}_pins_obs)')
    return f'''// Generated by Polari hwfpga.fpga_verilog — SIMULATION-ONLY
// wrapper: Renode's IntegrationLibrary AxiLite driver binds 64-bit
// channel signals; the real-FPGA artifact is polari_regblock.v.
module top (
    input  wire        clk,
    input  wire        rst,
    input  wire [63:0] awaddr,
    input  wire        awvalid,
    output wire        awready,
    input  wire [2:0]  awprot,
    input  wire [63:0] wdata,
    input  wire [3:0]  wstrb,
    input  wire        wvalid,
    output wire        wready,
    output wire [1:0]  bresp,
    output wire        bvalid,
    input  wire        bready,
    input  wire [63:0] araddr,
    input  wire        arvalid,
    output wire        arready,
    input  wire [2:0]  arprot,
    output wire [63:0] rdata,
    output wire [1:0]  rresp,
    output wire        rvalid,
    input  wire        rready
);
    wire [31:0] rdata32;
    assign rdata = {{32'h0, rdata32}};
{pin_wires}
    polari_regblock dut (
        .clk(clk), .rst(rst),
        .awaddr(awaddr[31:0]), .awvalid(awvalid), .awready(awready),
        .wdata(wdata[31:0]), .wstrb(wstrb), .wvalid(wvalid),
        .wready(wready),
        .bresp(bresp), .bvalid(bvalid), .bready(bready),
        .araddr(araddr[31:0]), .arvalid(arvalid), .arready(arready),
        .rdata(rdata32), .rresp(rresp), .rvalid(rvalid),
        .rready(rready),
        // the "hardware pins" in simulation: a fixed stub pattern
        .hw_pin_in(8'h{SIM_HW_PIN_PATTERN:02X}){pin_conns}
    );
endmodule
'''


def render_sim_main():
    """The co-simulation harness Renode spawns (socket mode:
    argv = receiverPort senderPort [address])."""
    return '''// Generated by Polari hwfpga.fpga_verilog — Renode co-sim harness.
#include <cstdio>
#include <cstdlib>
#include "Vtop.h"
#include "verilated.h"
#include "src/renode_bus.h"
#include "src/buses/axilite.h"

static Vtop *top;
static RenodeAgent *agent;

static void evaluateModel()
{
    top->eval();
}

RenodeAgent* Init()
{
    top = new Vtop;
    AxiLite* bus = new AxiLite();
    bus->clk = &top->clk;
    bus->rst = &top->rst;
    bus->awaddr = (uint64_t *)&top->awaddr;
    bus->awvalid = &top->awvalid;
    bus->awready = &top->awready;
    bus->awprot = &top->awprot;
    bus->wdata = (uint64_t *)&top->wdata;
    bus->wstrb = &top->wstrb;
    bus->wvalid = &top->wvalid;
    bus->wready = &top->wready;
    bus->bresp = &top->bresp;
    bus->bvalid = &top->bvalid;
    bus->bready = &top->bready;
    bus->araddr = (uint64_t *)&top->araddr;
    bus->arvalid = &top->arvalid;
    bus->arready = &top->arready;
    bus->arprot = &top->arprot;
    bus->rdata = (uint64_t *)&top->rdata;
    bus->rresp = &top->rresp;
    bus->rvalid = &top->rvalid;
    bus->rready = &top->rready;
    bus->evaluateModel = evaluateModel;

    agent = new RenodeAgent();
    agent->addBus(bus);
    // Library mode (Renode dlopens the .so and calls
    // initialize_native -> Init): the native channel must exist
    // BEFORE the first bus access or the response send derefs NULL.
    // Socket mode's main() replaces it via connect() afterwards.
    agent->connectNative();
    return agent;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr,
                "usage: %s {receiverPort} {senderPort} [address]\\n",
                argv[0]);
        return 1;
    }
    const char *address = (argc < 4) ? "127.0.0.1" : argv[3];
    Verilated::commandArgs(argc, argv);
    Init();
    agent->connect(atoi(argv[1]), atoi(argv[2]), address);
    agent->simulate();
    delete top;
    return 0;
}
'''


def render_c_defines(map_row, registers):
    """Firmware twin: offsets + reset values, from the same rows."""
    lines = [
        f'/* Generated by Polari hwfpga.fpga_verilog from register '
        f'map "{map_row.name}" — do not edit; edit the rows. */',
        f'#ifndef {map_row.name.upper().replace("-", "_")}_REGS_H',
        f'#define {map_row.name.upper().replace("-", "_")}_REGS_H',
        '',
        f'#define FPGA_BASE 0x{int(map_row.base_address):08X}u',
        '#define FPGA_REG(off) (*(volatile unsigned int *)'
        '(FPGA_BASE + (off)))',
        '',
    ]
    for name, offset, access, reset, desc, _pins in _reg_specs(registers):
        lines.append(f'#define FPGA_{name}_OFFSET 0x{offset:04X}u'
                     f'  /* {access}: {desc} */')
        if access == 'const':
            lines.append(f'#define FPGA_{name}_VALUE 0x{reset:08X}u')
    lines += ['', f'#endif']
    return '\n'.join(lines) + '\n'


def render_testbench(registers):
    """Self-checking bench (verilator --binary): consts read back,
    rw write/readback, heartbeat advances, and the MUX select
    switches STATUS[23:16] between counter and pin pattern."""
    specs = {name: (offset, access, reset)
             for name, offset, access, reset, _d, _p in
             _reg_specs(registers)}
    pin_wires = pin_conns = led_checks = ''
    for name, offset, access, _r, _d, pins in _reg_specs(registers):
        if pins > 0 and access == 'rw':
            lname = name.lower()
            pin_wires += (f'    wire [{pins - 1}:0] {lname}_pins;\n')
            pin_conns += f',\n        .{lname}_pins({lname}_pins)'
            mask = (1 << pins) - 1
            led_checks += f'''
        // {name}: bus write must drive the physical pins
        axi_write(32'h{offset:08X}, 32'hA5A5A5A5);
        axi_read(32'h{offset:08X});
        if ({lname}_pins !== {pins}'h{0xA5A5A5A5 & mask:X})
            $fatal(1, "{name} pins do not follow the register");
        if (rd !== 32'hA5A5A5A5)
            $fatal(1, "{name} readback mismatch: %h", rd);
'''
    dev_off, _, dev_val = specs['DEVICE_ID']
    ver_off, _, ver_val = specs['VERSION']
    st_off = specs['STATUS'][0]
    cmd_off = specs['COMMANDS'][0]
    mux_off = specs['MODE_MUX'][0]
    return f'''// Generated self-checking bench for polari_regblock.
`timescale 1ns/1ps
module tb;
    reg clk = 0, rst = 0;  // active-low: start IN reset
    reg  [31:0] awaddr = 0, wdata = 0, araddr = 0;
    reg         awvalid = 0, wvalid = 0, bready = 0, arvalid = 0;
    reg         rready = 0;
    reg  [3:0]  wstrb = 4'hF;
    wire        awready, wready, bvalid, arready, rvalid;
    wire [1:0]  bresp, rresp;
    wire [31:0] rdata;
{pin_wires}
    polari_regblock dut (
        .clk(clk), .rst(rst),
        .awaddr(awaddr), .awvalid(awvalid), .awready(awready),
        .wdata(wdata), .wstrb(wstrb), .wvalid(wvalid),
        .wready(wready),
        .bresp(bresp), .bvalid(bvalid), .bready(bready),
        .araddr(araddr), .arvalid(arvalid), .arready(arready),
        .rdata(rdata), .rresp(rresp), .rvalid(rvalid),
        .rready(rready),
        .hw_pin_in(8'h{SIM_HW_PIN_PATTERN:02X}){pin_conns}
    );

    always #5 clk = ~clk;

    task axi_write(input [31:0] addr, input [31:0] data);
        begin
            @(posedge clk); awaddr <= addr; awvalid <= 1;
            wait (awready); @(posedge clk); awvalid <= 0;
            wdata <= data; wvalid <= 1;
            wait (wready); @(posedge clk); wvalid <= 0;
            bready <= 1;
            wait (bvalid); @(posedge clk); bready <= 0;
            @(posedge clk);
        end
    endtask

    reg [31:0] rd;
    task axi_read(input [31:0] addr);
        begin
            @(posedge clk); araddr <= addr; arvalid <= 1;
            wait (arready); @(posedge clk); arvalid <= 0;
            wait (rvalid); rd = rdata;
            rready <= 1; @(posedge clk); rready <= 0;
            @(posedge clk);
        end
    endtask

    reg [31:0] hb1, hb2;
    initial begin
        repeat (4) @(posedge clk);
        rst <= 1;  // release the active-low reset
        repeat (2) @(posedge clk);

        axi_read(32'h{dev_off:08X});
        if (rd !== 32'h{dev_val:08X})
            $fatal(1, "DEVICE_ID mismatch: %h", rd);
        axi_read(32'h{ver_off:08X});
        if (rd !== 32'h{ver_val:08X})
            $fatal(1, "VERSION mismatch: %h", rd);

        axi_write(32'h{cmd_off:08X}, 32'hCAFE0042);
        axi_read(32'h{cmd_off:08X});
        if (rd !== 32'hCAFE0042)
            $fatal(1, "COMMANDS readback mismatch: %h", rd);

        axi_read(32'h{st_off:08X}); hb1 = rd & 32'hFFFF;
        repeat (8) @(posedge clk);
        axi_read(32'h{st_off:08X}); hb2 = rd & 32'hFFFF;
        if (hb2 == hb1)
            $fatal(1, "heartbeat is not advancing");

        // MUX: select source 1 -> STATUS[23:16] is the pin pattern
        axi_write(32'h{mux_off:08X}, 32'h1);
        axi_read(32'h{st_off:08X});
        if (((rd >> 16) & 32'hFF) !== 32'h{SIM_HW_PIN_PATTERN:02X})
            $fatal(1, "MUX source 1 should show pin pattern: %h", rd);
        // back to source 0 -> counter (changes between reads)
        axi_write(32'h{mux_off:08X}, 32'h0);
        axi_read(32'h{st_off:08X}); hb1 = (rd >> 16) & 32'hFF;
        repeat (5) @(posedge clk);
        axi_read(32'h{st_off:08X}); hb2 = (rd >> 16) & 32'hFF;
        if (hb1 == hb2)
            $fatal(1, "MUX source 0 should show the moving counter");

{led_checks}
        $display("TB PASS: consts, rw readback, heartbeat, mode MUX");
        $finish;
    end
endmodule
'''
