"""
@module hwdigital.custom.logic_verilog

ncg-3: LogicBlockNode rows -> synthesizable Verilog + a SELF-CHECKING
bench whose expected values come from the python reference evaluator
(logic_sim) — two independent implementations of the same rows must
agree, the same honesty pattern the parity vectors pin for the
solution engines. Plus the REAL iCE40 leg: yosys synth_ice40 ->
nextpnr-ice40 -> icepack/icetime (Dustin 2026-07-16: the digital
no-code maps to Verilog for iCE40-type FPGAs).

Reset is ACTIVE-LOW (house convention, hwfpga). Deterministic test
vectors come from a seeded LCG — seeded randomness is the standing
design decision, never wall-clock entropy.

Literal semantics: 'value' (const) and 'init' (dff/counter) are
MASKED to the node's width before rendering (two's-complement wrap:
value -1 at width 4 renders 4'hF) — the exact masking the python
evaluator applies, so the two implementations agree on negatives.
"""

import os
import shutil
import subprocess

from hwdigital.logic_basis import CLOCKED_KINDS
from hwdigital.custom.logic_sim import (LogicSimulator, design_specs,
                                 is_clocked)

OSS_CAD_BIN = os.path.expanduser('~/tools/oss-cad-suite/bin')
VECTOR_COUNT = 24
LCG_SEED = 0x5EED


def _ident(name):
    """Row names are kebab-case; Verilog identifiers are not."""
    return name.replace('-', '_')


def _vectors(specs, count=VECTOR_COUNT, seed=LCG_SEED):
    """Deterministic input vectors + python-expected outputs per
    cycle (clocked) / per vector (combinational)."""
    inputs = sorted(n for n, s in specs.items() if s['kind'] == 'input')
    sim = LogicSimulator(specs)
    state, rows = seed, []
    for _ in range(count):
        vector = {}
        for name in inputs:
            state = (state * 1103515245 + 12345) & 0x7FFFFFFF
            vector[name] = state & ((1 << specs[name]['width']) - 1)
        sim.set_inputs(**vector)
        if is_clocked(specs):
            sim.step()
        rows.append((dict(vector), dict(sim.outputs())))
    return rows


def render_module(design, specs):
    """The synthesizable module for one design."""
    name = _ident(design.name)

    def bit0(src):
        """LSB of a source — a bare scalar has no bit range to
        select (verilator rejects x[0] on a 1-bit wire)."""
        return (_ident(src) if specs[src]['width'] == 1
                else f'{_ident(src)}[0]')

    ports, wires, assigns, always = [], [], [], []
    for node in sorted(specs):
        s = specs[node]
        ident, width = _ident(node), s['width']
        rng = f'[{width - 1}:0] ' if width > 1 else ''
        ins = [_ident(i) for i in s['inputs']]
        if s['kind'] == 'input':
            ports.append(f'    input  wire {rng}{ident}')
        elif s['kind'] == 'output':
            ports.append(f'    output wire {rng}{ident}')
            assigns.append(f'    assign {ident} = {ins[0]};')
        elif s['kind'] == 'const':
            # Mask BEFORE rendering — a negative value must wrap to
            # the same bits the python evaluator computes, never
            # emit an invalid 4'h-1 literal.
            value = (int(s['params'].get('value', 0))
                     & ((1 << width) - 1))
            wires.append(f'    wire {rng}{ident} = '
                         f"{width}'h{value:X};")
        elif s['kind'] in CLOCKED_KINDS:
            # Same width-mask as the const path (and as
            # LogicSimulator's reset state) for negative inits.
            init = (int(s['params'].get('init', 0))
                    & ((1 << width) - 1))
            wires.append(f'    reg  {rng}{ident};')
            if s['kind'] == 'dff':
                update = f'{ident} <= {ins[0]};'
            else:
                enable = bit0(s['inputs'][0]) if ins else "1'b1"
                update = (f'if ({enable}) '
                          f"{ident} <= {ident} + {width}'d1;")
            always.append(f'''    always @(posedge clk) begin
        if (!rst) {ident} <= {width}'h{init:X};
        else {update}
    end''')
        else:
            expr = {'not': f'~{ins[0]}', 'buf': ins[0],
                    'mux2': (f"{bit0(s['inputs'][2])} ? {ins[1]} : "
                             f'{ins[0]}'
                             if s['kind'] == 'mux2' else '')
                    }.get(s['kind'])
            if expr is None:
                op = {'and': ' & ', 'nand': ' & ', 'or': ' | ',
                      'nor': ' | ', 'xor': ' ^ '}[s['kind']]
                expr = op.join(ins)
                if s['kind'] in ('nand', 'nor'):
                    expr = f'~({expr})'
            wires.append(f'    wire {rng}{ident} = {expr};')
    clock_ports = (['    input  wire clk', '    input  wire rst']
                   if is_clocked(specs) else [])
    nl = '\n'
    return f'''// Generated by Polari hwdigital.custom.logic_verilog from design
// "{design.name}" — do not edit; edit the LogicBlockNode rows (the
// no-code diagram) and regenerate. Reset is ACTIVE-LOW.
module {name} (
{(',' + nl).join(clock_ports + ports)}
);
{nl.join(wires)}
{nl.join(assigns)}
{nl.join(always)}
endmodule
'''


def render_bench(design, specs):
    """Self-checking bench: replay the seeded vectors, $fatal on any
    disagreement with the python reference evaluator."""
    name = _ident(design.name)
    clocked = is_clocked(specs)
    inputs = sorted(n for n, s in specs.items() if s['kind'] == 'input')
    outputs = sorted(n for n, s in specs.items()
                     if s['kind'] == 'output')
    decls = ''.join(
        f"    reg  [{specs[n]['width'] - 1}:0] {_ident(n)} = 0;\n"
        for n in inputs) + ''.join(
        f"    wire [{specs[n]['width'] - 1}:0] {_ident(n)};\n"
        for n in outputs)
    conns = ', '.join(f'.{_ident(n)}({_ident(n)})'
                      for n in inputs + outputs)
    if clocked:
        conns = '.clk(clk), .rst(rst), ' + conns
    steps = []
    for i, (vector, expected) in enumerate(_vectors(specs)):
        sets = ''.join(f'        {_ident(n)} = '
                       f"{specs[n]['width']}'h{v:X};\n"
                       for n, v in vector.items())
        advance = ('        @(posedge clk); #1;\n' if clocked
                   else '        #1;\n')
        checks = ''.join(
            f'        if ({_ident(n)} !== '
            f"{specs[n]['width']}'h{v:X}) "
            f'$fatal(1, "vector {i}: {n} = %h, python expects '
            f'{v:x}", {_ident(n)});\n'
            for n, v in expected.items())
        steps.append(sets + advance + checks)
    clock_body = ('    reg clk = 0, rst = 0;\n'
                  '    always #5 clk = ~clk;\n' if clocked else '')
    reset_release = ('        rst = 0; @(posedge clk); #1; rst = 1;\n'
                     if clocked else '')
    nl = ''
    return f'''// Generated self-checking bench for {name} — expected
// values computed by hwdigital.custom.logic_sim (the python reference).
`timescale 1ns/1ps
module tb;
{clock_body}{decls}
    {name} dut ({conns});

    initial begin
{reset_release}{nl.join(steps)}
        $display("BENCH-OK {len(_vectors(specs))} vectors");
        $finish;
    end
endmodule
'''


def _tool(name):
    """PATH first, then the workstation's oss-cad-suite install."""
    found = shutil.which(name)
    if found:
        return found
    candidate = os.path.join(OSS_CAD_BIN, name)
    return candidate if os.path.isfile(candidate) else None


def run_bench(design, specs, workdir):
    """Verilate + run the self-checking bench. Honest skip dict when
    verilator is unavailable."""
    verilator = _tool('verilator')
    if verilator is None:
        return {'status': 'skip-honest',
                'evidence': 'verilator not found (PATH or '
                            f'{OSS_CAD_BIN}) — install oss-cad-suite '
                            'to run the generated bench'}
    module_v = os.path.join(workdir, f'{_ident(design.name)}.v')
    bench_v = os.path.join(workdir, 'tb.v')
    with open(module_v, 'w') as fh:
        fh.write(render_module(design, specs))
    with open(bench_v, 'w') as fh:
        fh.write(render_bench(design, specs))
    build = subprocess.run(
        [verilator, '--binary', '--timing', '-Wno-fatal', '-o', 'Vtb',
         'tb.v', os.path.basename(module_v)],
        cwd=workdir, capture_output=True, text=True, timeout=300)
    if build.returncode != 0:
        return {'status': 'fail',
                'evidence': 'verilator build failed: '
                            + (build.stderr or '')[-400:]}
    run = subprocess.run([os.path.join(workdir, 'obj_dir', 'Vtb')],
                         capture_output=True, text=True, timeout=120)
    ok = run.returncode == 0 and 'BENCH-OK' in (run.stdout or '')
    return {'status': 'pass' if ok else 'fail',
            'evidence': (run.stdout or run.stderr or '').strip()[-300:]}


def run_ice40_synth(design, specs, workdir, device='hx8k',
                    package='ct256'):
    """The REAL iCE40 leg: yosys synth_ice40 -> nextpnr-ice40 ->
    icepack (bitstream) + icetime (timing). Honest skip without the
    toolchain; a synthesis/PnR failure is a FAIL, not a skip."""
    tools = {name: _tool(name)
             for name in ('yosys', 'nextpnr-ice40', 'icepack',
                          'icetime')}
    missing = sorted(n for n, p in tools.items() if p is None)
    if missing:
        return {'status': 'skip-honest',
                'evidence': f'iCE40 toolchain incomplete (missing '
                            f'{", ".join(missing)}) — oss-cad-suite '
                            f'provides all four'}
    top = _ident(design.name)
    module_v = os.path.join(workdir, f'{top}.v')
    with open(module_v, 'w') as fh:
        fh.write(render_module(design, specs))
    yosys = subprocess.run(
        [tools['yosys'], '-q', '-p',
         f'read_verilog {os.path.basename(module_v)}; '
         f'synth_ice40 -top {top} -json {top}.json'],
        cwd=workdir, capture_output=True, text=True, timeout=300)
    if yosys.returncode != 0:
        return {'status': 'fail', 'evidence': 'yosys synth_ice40 '
                'failed: ' + (yosys.stderr or '')[-400:]}
    pnr = subprocess.run(
        [tools['nextpnr-ice40'], f'--{device}', '--package', package,
         '--json', f'{top}.json', '--asc', f'{top}.asc',
         '--pcf-allow-unconstrained'],
        cwd=workdir, capture_output=True, text=True, timeout=600)
    if pnr.returncode != 0:
        return {'status': 'fail', 'evidence': 'nextpnr-ice40 failed: '
                + (pnr.stderr or '')[-400:]}
    subprocess.run([tools['icepack'], f'{top}.asc', f'{top}.bin'],
                   cwd=workdir, capture_output=True, timeout=120)
    timing = subprocess.run(
        [tools['icetime'], '-d', device, f'{top}.asc'],
        cwd=workdir, capture_output=True, text=True, timeout=120)
    fmax = next((line.strip() for line
                 in (timing.stdout or '').splitlines()
                 if 'MHz' in line), 'timing n/a')
    made_bitstream = os.path.isfile(os.path.join(workdir,
                                                 f'{top}.bin'))
    return {'status': 'pass' if made_bitstream else 'fail',
            'evidence': f'iCE40 {device}/{package}: bitstream '
                        f'{"written" if made_bitstream else "MISSING"}'
                        f'; {fmax}'}


def compile_design(manager, design_name):
    """Everything generated for one design, as data (no tools run)."""
    from hwdigital.custom.logic_sim import load_design
    design, _ = load_design(manager, design_name)
    specs = design_specs(manager, design_name)
    return {
        'design': design,
        'specs': specs,
        'verilog': render_module(design, specs),
        'bench': render_bench(design, specs),
        'clocked': is_clocked(specs),
    }
