/* Generated by Polari grpcbridge.custom.c_twin (grpc-j3) + c_twin_v2 (grpc-j4) — do not edit.
 * class: ButtonClockEvent   contract v1   hash b3193728aa68a383   target avr
 * wire v2   hash2 ef52cd667e39e809   single instance: nothing to tell apart (presence bits only)   prelude 1 byte(s)
 * The struct carries FIELDS ONLY; the hardware-interface identity lives in the gRPC message and the binding row.
 * Regenerate when the contract, an enum mapping or the bindings change. */
#ifndef BUTTONCLOCKEVENT_PACKETS_H
#define BUTTONCLOCKEVENT_PACKETS_H

#ifndef POLARI_RX_PAYLOAD_MAX
#define POLARI_RX_PAYLOAD_MAX 108u
#endif

#ifndef POLARI_PACKET_V2_COMMON_H
#define POLARI_PACKET_V2_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#define POLARI_MAGIC       0x504CU  /* wire bytes: 0x4C 0x50 */
#define POLARI_VERSION     2U       /* wire v2: payload = prelude (packed index + presence) + present fields */
#define POLARI_VERSION_MIN 1U       /* v1 frames still parse (an old firmware / bridge) */
#define POLARI_VERSION_MAX 4U       /* v3: an explicit index byte; v4: an explicit 16-bit index (grpc-j4) */
#define POLARI_HEADER_LEN  12U

/* CRC32 (IEEE reflected, poly 0xEDB88320) — identical to
 * java.util.zip.CRC32 and Python zlib.crc32. Bitwise (no table):
 * cycles are cheap at telemetry rates, flash is not. */
static uint32_t polari_crc32(const uint8_t *d, size_t n)
{
    uint32_t c = 0xFFFFFFFFu;
    size_t i;
    int k;
    for (i = 0; i < n; i++) {
        c ^= d[i];
        for (k = 0; k < 8; k++)
            c = (c >> 1) ^ (0xEDB88320u
                            & (uint32_t)(-(int32_t)(c & 1u)));
    }
    return ~c;
}

static void polari_put_u16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
}

static void polari_put_u32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v;         p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static uint16_t polari_get_u16(const uint8_t *p)
{
    return (uint16_t)(p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t polari_get_u32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

/* Frame a payload into `out` (must hold POLARI_HEADER_LEN+len+4) with the given version byte. Returns the wire
 * length. A class header's <C>_frame() passes its own <C>_WIRE_VERSION. */
static size_t polari_packet_encode_v(uint8_t *out, uint8_t version, uint8_t msg_type,
                                     uint16_t device_id, uint32_t seq,
                                     const uint8_t *payload,
                                     uint16_t len)
{
    polari_put_u16(out, POLARI_MAGIC);
    out[2] = version;
    out[3] = msg_type;
    polari_put_u16(out + 4, device_id);
    polari_put_u32(out + 6, seq);
    polari_put_u16(out + 10, len);
    memcpy(out + POLARI_HEADER_LEN, payload, len);
    polari_put_u32(out + POLARI_HEADER_LEN + len,
                   polari_crc32(out, POLARI_HEADER_LEN + len));
    return POLARI_HEADER_LEN + (size_t)len + 4u;
}

typedef struct {
    uint8_t buf[POLARI_HEADER_LEN + POLARI_RX_PAYLOAD_MAX + 4u];
    size_t have;
    uint16_t need_payload;
    uint8_t version;
    uint8_t msg_type;
    uint16_t device_id;
    uint32_t sequence;
    const uint8_t *payload;
    uint16_t payload_len;
} polari_rx_t;

/* 1 = buf holds a complete CRC-valid frame, 0 = need more bytes, -1 = the candidate at buf[0] is no frame. */
static int polari_rx_check(polari_rx_t *rx)
{
    size_t total;
    if (rx->have >= 1u && rx->buf[0] != (uint8_t)(POLARI_MAGIC & 0xFFu)) return -1;
    if (rx->have >= 2u && rx->buf[1] != (uint8_t)(POLARI_MAGIC >> 8)) return -1;
    if (rx->have < POLARI_HEADER_LEN) return 0;
    if (rx->buf[2] < POLARI_VERSION_MIN || rx->buf[2] > POLARI_VERSION_MAX) return -1;
    rx->need_payload = polari_get_u16(rx->buf + 10);
    if (rx->need_payload > POLARI_RX_PAYLOAD_MAX) return -1;
    total = POLARI_HEADER_LEN + (size_t)rx->need_payload + 4u;
    if (rx->have < total) return 0;
    if (polari_get_u32(rx->buf + total - 4u) != polari_crc32(rx->buf, total - 4u)) return -1;
    return 1;
}

/* Feed one byte; returns 1 when rx holds a complete CRC-valid frame (version / msg_type / payload populated, valid
 * until the next feed). A rejected candidate is NOT thrown away: the parser slides to the next 0x4C among the bytes it
 * already holds and re-examines them, so a frame that starts inside garbage or inside a corrupted frame is kept. */
static int polari_rx_feed(polari_rx_t *rx, uint8_t b)
{
    size_t i;
    int r;
    rx->buf[rx->have++] = b;
    for (;;) {
        r = polari_rx_check(rx);
        if (r == 0) return 0;
        if (r == 1) {
            rx->version = rx->buf[2];
            rx->msg_type = rx->buf[3];
            rx->device_id = polari_get_u16(rx->buf + 4);
            rx->sequence = polari_get_u32(rx->buf + 6);
            rx->payload = rx->buf + POLARI_HEADER_LEN;
            rx->payload_len = rx->need_payload;
            rx->have = 0u;
            return 1;
        }
        for (i = 1u; i < rx->have && rx->buf[i] != (uint8_t)(POLARI_MAGIC & 0xFFu); i++) { }
        memmove(rx->buf, rx->buf + i, rx->have - i);
        rx->have -= i;
    }
}

#endif /* POLARI_PACKET_V2_COMMON_H */

#define BUTTONCLOCKEVENT_MSG_TYPE 2u
#define BUTTONCLOCKEVENT_PAYLOAD_MAX 108u
#define BUTTONCLOCKEVENT_WIRE_VERSION 2u
#define BUTTONCLOCKEVENT_PRELUDE_BYTES 1u
#define BUTTONCLOCKEVENT_HASH_V2 "ef52cd667e39e809"

typedef uint8_t ButtonClockEvent_mask_t;
#define BUTTONCLOCKEVENT_F_BOOT_SESSION ((ButtonClockEvent_mask_t)1u << 0)  /* boot_session (int64) */
#define BUTTONCLOCKEVENT_F_EPOCH_S ((ButtonClockEvent_mask_t)1u << 1)  /* epoch_s (int64) */
#define BUTTONCLOCKEVENT_F_KIND ((ButtonClockEvent_mask_t)1u << 2)  /* kind (string) */
#define BUTTONCLOCKEVENT_F_MS ((ButtonClockEvent_mask_t)1u << 3)  /* ms (int64) */
#define BUTTONCLOCKEVENT_F_NAME ((ButtonClockEvent_mask_t)1u << 4)  /* name (string) */
#define BUTTONCLOCKEVENT_F_SEQ ((ButtonClockEvent_mask_t)1u << 5)  /* seq (int64) */
#define BUTTONCLOCKEVENT_F_UPTIME_MS ((ButtonClockEvent_mask_t)1u << 6)  /* uptime_ms (int64) */
#define BUTTONCLOCKEVENT_F_ALL ((ButtonClockEvent_mask_t)0x7fu)

/* enum mapping ButtonClockEvent.kind (EnumMapping row): 1 byte on the wire */
enum {
    BUTTONCLOCKEVENT_KIND_UNKNOWN = 0,
    BUTTONCLOCKEVENT_KIND_PRESS = 1,
    BUTTONCLOCKEVENT_KIND_LED_ON = 2,
    BUTTONCLOCKEVENT_KIND_LED_OFF = 3,
    BUTTONCLOCKEVENT_KIND_SENSE_RISE = 4,
    BUTTONCLOCKEVENT_KIND_SENSE_FALL = 5,
    BUTTONCLOCKEVENT_KIND_SYNC = 6
};
static inline const char *ButtonClockEvent_kind_name(uint8_t v)
{
    switch (v) {
    case 1: return "press";
    case 2: return "led_on";
    case 3: return "led_off";
    case 4: return "sense_rise";
    case 5: return "sense_fall";
    case 6: return "sync";
    default: return "unknown";
    }
}

typedef struct {
    int64_t boot_session;
    int64_t epoch_s;
    uint8_t kind;  /* enum: BUTTONCLOCKEVENT_KIND_* (0 = unknown) */
    int64_t ms;
    char name[64];
    int64_t seq;
    int64_t uptime_ms;
} ButtonClockEvent_t;

/* struct -> payload: the prelude (presence bits) + ONLY the fields set in `present`. */
static uint16_t ButtonClockEvent_encode(const ButtonClockEvent_t *s, uint8_t *p,
                                    ButtonClockEvent_mask_t present)
{
    uint8_t *start = p;
    uint8_t pre;
    uint16_t n;
    (void)n;
    present &= BUTTONCLOCKEVENT_F_ALL;
    pre = (uint8_t)present;
    p[0] = (uint8_t)pre;
    p += 1;
    if (present & BUTTONCLOCKEVENT_F_BOOT_SESSION) {
        polari_put_u32(p, (uint32_t)s->boot_session);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->boot_session >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKEVENT_F_EPOCH_S) {
        polari_put_u32(p, (uint32_t)s->epoch_s);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->epoch_s >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKEVENT_F_KIND) { *p++ = s->kind; }
    if (present & BUTTONCLOCKEVENT_F_MS) {
        polari_put_u32(p, (uint32_t)s->ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKEVENT_F_NAME) {
        n = (uint16_t)strlen(s->name);
        polari_put_u16(p, n); p += 2;
        memcpy(p, s->name, n); p += n;
    }
    if (present & BUTTONCLOCKEVENT_F_SEQ) {
        polari_put_u32(p, (uint32_t)s->seq);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->seq >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKEVENT_F_UPTIME_MS) {
        polari_put_u32(p, (uint32_t)s->uptime_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->uptime_ms >> 32)); p += 8;
    }
    return (uint16_t)(p - start);
}

/* payload -> struct: ONLY the present fields are written (a partial command leaves the rest alone).
 * Returns 0, or -1 on truncated input. present may be NULL. */
static int ButtonClockEvent_decode(const uint8_t *p, uint16_t len, ButtonClockEvent_t *s,
                               ButtonClockEvent_mask_t *present)
{
    const uint8_t *end = p + len;
    uint8_t pre;
    ButtonClockEvent_mask_t m;
    uint16_t n, cp;
    (void)n; (void)cp;
    if (len < BUTTONCLOCKEVENT_PRELUDE_BYTES) return -1;
    pre = (uint8_t)((uint8_t)p[0]);
    p += 1;
    m = (ButtonClockEvent_mask_t)(pre >> 0) & BUTTONCLOCKEVENT_F_ALL;
    if (present) *present = m;
    if (m & BUTTONCLOCKEVENT_F_BOOT_SESSION) {
        if (end - p < 8) return -1;
        s->boot_session = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKEVENT_F_EPOCH_S) {
        if (end - p < 8) return -1;
        s->epoch_s = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKEVENT_F_KIND) {
        if (end - p < 1) return -1;
        s->kind = *p++;
    }
    if (m & BUTTONCLOCKEVENT_F_MS) {
        if (end - p < 8) return -1;
        s->ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKEVENT_F_NAME) {
        if (end - p < 2) return -1;
        n = polari_get_u16(p); p += 2;
        if ((uint16_t)(end - p) < n) return -1;
        cp = n < 63u ? n : 63u;
        memcpy(s->name, p, cp); s->name[cp] = 0; p += n;
    }
    if (m & BUTTONCLOCKEVENT_F_SEQ) {
        if (end - p < 8) return -1;
        s->seq = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKEVENT_F_UPTIME_MS) {
        if (end - p < 8) return -1;
        s->uptime_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    return 0;
}

/* decode a parsed frame: -2 for any other version (a v1 frame from an old bridge, another index representation):
 * refused, never misread */
static int ButtonClockEvent_decode_rx(const polari_rx_t *rx, ButtonClockEvent_t *s,
                                  ButtonClockEvent_mask_t *present)
{
    if (rx->version != BUTTONCLOCKEVENT_WIRE_VERSION) return -2;
    return ButtonClockEvent_decode(rx->payload, rx->payload_len, s, present);
}

/* frame a payload with this class's version byte and msg_type */
static size_t ButtonClockEvent_frame(uint8_t *out, uint16_t device_id, uint32_t seq,
                                 const uint8_t *payload, uint16_t len)
{
    return polari_packet_encode_v(out, BUTTONCLOCKEVENT_WIRE_VERSION, BUTTONCLOCKEVENT_MSG_TYPE, device_id, seq, payload, len);
}

#endif /* BUTTONCLOCKEVENT_PACKETS_H */
