/* Generated by Polari grpcbridge.custom.c_twin (grpc-j3) + c_twin_v2 (grpc-j4) — do not edit.
 * class: ButtonClockState   contract v1   hash 9d32ede2fa51ab74   target avr
 * wire v2   hash2 ad45a5f45f65b8b0   single instance: nothing to tell apart (presence bits only)   prelude 3 byte(s)
 * The struct carries FIELDS ONLY; the hardware-interface identity lives in the gRPC message and the binding row.
 * Regenerate when the contract, an enum mapping or the bindings change. */
#ifndef BUTTONCLOCKSTATE_PACKETS_H
#define BUTTONCLOCKSTATE_PACKETS_H

#ifndef POLARI_RX_PAYLOAD_MAX
#define POLARI_RX_PAYLOAD_MAX 218u
#endif

#ifndef POLARI_PACKET_V2_COMMON_H
#define POLARI_PACKET_V2_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#define POLARI_MAGIC       0x504CU  /* wire bytes: 0x4C 0x50 */
#define POLARI_VERSION     2U       /* wire v2: payload = prelude (packed index + presence) + present fields */
#define POLARI_VERSION_MIN 1U       /* v1 frames still parse (an old firmware / bridge) */
#define POLARI_VERSION_MAX 4U       /* v3: an explicit index byte; v4: an explicit 16-bit index (grpc-j4) */
#define POLARI_HEADER_LEN  12U

/* CRC32 (IEEE reflected, poly 0xEDB88320) — identical to
 * java.util.zip.CRC32 and Python zlib.crc32. Bitwise (no table):
 * cycles are cheap at telemetry rates, flash is not. */
static uint32_t polari_crc32(const uint8_t *d, size_t n)
{
    uint32_t c = 0xFFFFFFFFu;
    size_t i;
    int k;
    for (i = 0; i < n; i++) {
        c ^= d[i];
        for (k = 0; k < 8; k++)
            c = (c >> 1) ^ (0xEDB88320u
                            & (uint32_t)(-(int32_t)(c & 1u)));
    }
    return ~c;
}

static void polari_put_u16(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
}

static void polari_put_u32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v;         p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static uint16_t polari_get_u16(const uint8_t *p)
{
    return (uint16_t)(p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t polari_get_u32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

/* Frame a payload into `out` (must hold POLARI_HEADER_LEN+len+4) with the given version byte. Returns the wire
 * length. A class header's <C>_frame() passes its own <C>_WIRE_VERSION. */
static size_t polari_packet_encode_v(uint8_t *out, uint8_t version, uint8_t msg_type,
                                     uint16_t device_id, uint32_t seq,
                                     const uint8_t *payload,
                                     uint16_t len)
{
    polari_put_u16(out, POLARI_MAGIC);
    out[2] = version;
    out[3] = msg_type;
    polari_put_u16(out + 4, device_id);
    polari_put_u32(out + 6, seq);
    polari_put_u16(out + 10, len);
    memcpy(out + POLARI_HEADER_LEN, payload, len);
    polari_put_u32(out + POLARI_HEADER_LEN + len,
                   polari_crc32(out, POLARI_HEADER_LEN + len));
    return POLARI_HEADER_LEN + (size_t)len + 4u;
}

typedef struct {
    uint8_t buf[POLARI_HEADER_LEN + POLARI_RX_PAYLOAD_MAX + 4u];
    size_t have;
    uint16_t need_payload;
    uint8_t version;
    uint8_t msg_type;
    uint16_t device_id;
    uint32_t sequence;
    const uint8_t *payload;
    uint16_t payload_len;
} polari_rx_t;

/* 1 = buf holds a complete CRC-valid frame, 0 = need more bytes, -1 = the candidate at buf[0] is no frame. */
static int polari_rx_check(polari_rx_t *rx)
{
    size_t total;
    if (rx->have >= 1u && rx->buf[0] != (uint8_t)(POLARI_MAGIC & 0xFFu)) return -1;
    if (rx->have >= 2u && rx->buf[1] != (uint8_t)(POLARI_MAGIC >> 8)) return -1;
    if (rx->have < POLARI_HEADER_LEN) return 0;
    if (rx->buf[2] < POLARI_VERSION_MIN || rx->buf[2] > POLARI_VERSION_MAX) return -1;
    rx->need_payload = polari_get_u16(rx->buf + 10);
    if (rx->need_payload > POLARI_RX_PAYLOAD_MAX) return -1;
    total = POLARI_HEADER_LEN + (size_t)rx->need_payload + 4u;
    if (rx->have < total) return 0;
    if (polari_get_u32(rx->buf + total - 4u) != polari_crc32(rx->buf, total - 4u)) return -1;
    return 1;
}

/* Feed one byte; returns 1 when rx holds a complete CRC-valid frame (version / msg_type / payload populated, valid
 * until the next feed). A rejected candidate is NOT thrown away: the parser slides to the next 0x4C among the bytes it
 * already holds and re-examines them, so a frame that starts inside garbage or inside a corrupted frame is kept. */
static int polari_rx_feed(polari_rx_t *rx, uint8_t b)
{
    size_t i;
    int r;
    rx->buf[rx->have++] = b;
    for (;;) {
        r = polari_rx_check(rx);
        if (r == 0) return 0;
        if (r == 1) {
            rx->version = rx->buf[2];
            rx->msg_type = rx->buf[3];
            rx->device_id = polari_get_u16(rx->buf + 4);
            rx->sequence = polari_get_u32(rx->buf + 6);
            rx->payload = rx->buf + POLARI_HEADER_LEN;
            rx->payload_len = rx->need_payload;
            rx->have = 0u;
            return 1;
        }
        for (i = 1u; i < rx->have && rx->buf[i] != (uint8_t)(POLARI_MAGIC & 0xFFu); i++) { }
        memmove(rx->buf, rx->buf + i, rx->have - i);
        rx->have -= i;
    }
}

#endif /* POLARI_PACKET_V2_COMMON_H */

#define BUTTONCLOCKSTATE_MSG_TYPE 1u
#define BUTTONCLOCKSTATE_PAYLOAD_MAX 218u
#define BUTTONCLOCKSTATE_WIRE_VERSION 2u
#define BUTTONCLOCKSTATE_PRELUDE_BYTES 3u
#define BUTTONCLOCKSTATE_HASH_V2 "ad45a5f45f65b8b0"

typedef uint32_t ButtonClockState_mask_t;
#define BUTTONCLOCKSTATE_F_BOOT_SESSION ((ButtonClockState_mask_t)1u << 0)  /* boot_session (int64) */
#define BUTTONCLOCKSTATE_F_BUTTON_PRESSES ((ButtonClockState_mask_t)1u << 1)  /* button_presses (int64) */
#define BUTTONCLOCKSTATE_F_CLOCK_SYNCED ((ButtonClockState_mask_t)1u << 2)  /* clock_synced (bool) */
#define BUTTONCLOCKSTATE_F_DRIFT_MS ((ButtonClockState_mask_t)1u << 3)  /* drift_ms (int64) */
#define BUTTONCLOCKSTATE_F_DROPPED_EVENTS ((ButtonClockState_mask_t)1u << 4)  /* dropped_events (int64) */
#define BUTTONCLOCKSTATE_F_EPOCH_S ((ButtonClockState_mask_t)1u << 5)  /* epoch_s (int64) */
#define BUTTONCLOCKSTATE_F_LAST_EDGE_AT ((ButtonClockState_mask_t)1u << 6)  /* last_edge_at (int64) */
#define BUTTONCLOCKSTATE_F_LAST_EDGE_MS ((ButtonClockState_mask_t)1u << 7)  /* last_edge_ms (int64) */
#define BUTTONCLOCKSTATE_F_LED_CHANGED_AT ((ButtonClockState_mask_t)1u << 8)  /* led_changed_at (int64) */
#define BUTTONCLOCKSTATE_F_LED_ON ((ButtonClockState_mask_t)1u << 9)  /* led_on (bool) */
#define BUTTONCLOCKSTATE_F_MS ((ButtonClockState_mask_t)1u << 10)  /* ms (int64) */
#define BUTTONCLOCKSTATE_F_NAME ((ButtonClockState_mask_t)1u << 11)  /* name (string) */
#define BUTTONCLOCKSTATE_F_SENSE_FALLS ((ButtonClockState_mask_t)1u << 12)  /* sense_falls (int64) */
#define BUTTONCLOCKSTATE_F_SENSE_RISES ((ButtonClockState_mask_t)1u << 13)  /* sense_rises (int64) */
#define BUTTONCLOCKSTATE_F_SEQ ((ButtonClockState_mask_t)1u << 14)  /* seq (int64) */
#define BUTTONCLOCKSTATE_F_SET_EPOCH_S ((ButtonClockState_mask_t)1u << 15)  /* set_epoch_s (int64) */
#define BUTTONCLOCKSTATE_F_SET_LED ((ButtonClockState_mask_t)1u << 16)  /* set_led (bool) */
#define BUTTONCLOCKSTATE_F_SET_MS ((ButtonClockState_mask_t)1u << 17)  /* set_ms (int64) */
#define BUTTONCLOCKSTATE_F_SET_SYNC_GENERATION ((ButtonClockState_mask_t)1u << 18)  /* set_sync_generation (int64) */
#define BUTTONCLOCKSTATE_F_SNAPSHOT ((ButtonClockState_mask_t)1u << 19)  /* snapshot (bool) */
#define BUTTONCLOCKSTATE_F_STATUS ((ButtonClockState_mask_t)1u << 20)  /* status (string) */
#define BUTTONCLOCKSTATE_F_SYNC_GENERATION ((ButtonClockState_mask_t)1u << 21)  /* sync_generation (int64) */
#define BUTTONCLOCKSTATE_F_SYNC_UNCERTAINTY_MS ((ButtonClockState_mask_t)1u << 22)  /* sync_uncertainty_ms (int64) */
#define BUTTONCLOCKSTATE_F_UPTIME_MS ((ButtonClockState_mask_t)1u << 23)  /* uptime_ms (int64) */
#define BUTTONCLOCKSTATE_F_ALL ((ButtonClockState_mask_t)0xffffffu)

/* enum mapping ButtonClockState.status (EnumMapping row): 1 byte on the wire */
enum {
    BUTTONCLOCKSTATE_STATUS_UNKNOWN = 0,
    BUTTONCLOCKSTATE_STATUS_IDLE = 1,
    BUTTONCLOCKSTATE_STATUS_COMMANDED = 2,
    BUTTONCLOCKSTATE_STATUS_SYNCED = 3,
    BUTTONCLOCKSTATE_STATUS_SNAPSHOT = 4
};
static inline const char *ButtonClockState_status_name(uint8_t v)
{
    switch (v) {
    case 1: return "idle";
    case 2: return "commanded";
    case 3: return "synced";
    case 4: return "snapshot";
    default: return "unknown";
    }
}

typedef struct {
    int64_t boot_session;
    int64_t button_presses;
    uint8_t clock_synced;
    int64_t drift_ms;
    int64_t dropped_events;
    int64_t epoch_s;
    int64_t last_edge_at;
    int64_t last_edge_ms;
    int64_t led_changed_at;
    uint8_t led_on;
    int64_t ms;
    char name[64];
    int64_t sense_falls;
    int64_t sense_rises;
    int64_t seq;
    int64_t set_epoch_s;
    uint8_t set_led;
    int64_t set_ms;
    int64_t set_sync_generation;
    uint8_t snapshot;
    uint8_t status;  /* enum: BUTTONCLOCKSTATE_STATUS_* (0 = unknown) */
    int64_t sync_generation;
    int64_t sync_uncertainty_ms;
    int64_t uptime_ms;
} ButtonClockState_t;

/* struct -> payload: the prelude (presence bits) + ONLY the fields set in `present`. */
static uint16_t ButtonClockState_encode(const ButtonClockState_t *s, uint8_t *p,
                                    ButtonClockState_mask_t present)
{
    uint8_t *start = p;
    uint32_t pre;
    uint16_t n;
    (void)n;
    present &= BUTTONCLOCKSTATE_F_ALL;
    pre = (uint32_t)present;
    p[0] = (uint8_t)pre;
    p[1] = (uint8_t)(pre >> 8);
    p[2] = (uint8_t)(pre >> 16);
    p += 3;
    if (present & BUTTONCLOCKSTATE_F_BOOT_SESSION) {
        polari_put_u32(p, (uint32_t)s->boot_session);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->boot_session >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_BUTTON_PRESSES) {
        polari_put_u32(p, (uint32_t)s->button_presses);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->button_presses >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_CLOCK_SYNCED) { *p++ = s->clock_synced ? 1u : 0u; }
    if (present & BUTTONCLOCKSTATE_F_DRIFT_MS) {
        polari_put_u32(p, (uint32_t)s->drift_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->drift_ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_DROPPED_EVENTS) {
        polari_put_u32(p, (uint32_t)s->dropped_events);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->dropped_events >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_EPOCH_S) {
        polari_put_u32(p, (uint32_t)s->epoch_s);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->epoch_s >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_LAST_EDGE_AT) {
        polari_put_u32(p, (uint32_t)s->last_edge_at);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->last_edge_at >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_LAST_EDGE_MS) {
        polari_put_u32(p, (uint32_t)s->last_edge_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->last_edge_ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_LED_CHANGED_AT) {
        polari_put_u32(p, (uint32_t)s->led_changed_at);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->led_changed_at >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_LED_ON) { *p++ = s->led_on ? 1u : 0u; }
    if (present & BUTTONCLOCKSTATE_F_MS) {
        polari_put_u32(p, (uint32_t)s->ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_NAME) {
        n = (uint16_t)strlen(s->name);
        polari_put_u16(p, n); p += 2;
        memcpy(p, s->name, n); p += n;
    }
    if (present & BUTTONCLOCKSTATE_F_SENSE_FALLS) {
        polari_put_u32(p, (uint32_t)s->sense_falls);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->sense_falls >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SENSE_RISES) {
        polari_put_u32(p, (uint32_t)s->sense_rises);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->sense_rises >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SEQ) {
        polari_put_u32(p, (uint32_t)s->seq);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->seq >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SET_EPOCH_S) {
        polari_put_u32(p, (uint32_t)s->set_epoch_s);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->set_epoch_s >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SET_LED) { *p++ = s->set_led ? 1u : 0u; }
    if (present & BUTTONCLOCKSTATE_F_SET_MS) {
        polari_put_u32(p, (uint32_t)s->set_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->set_ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SET_SYNC_GENERATION) {
        polari_put_u32(p, (uint32_t)s->set_sync_generation);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->set_sync_generation >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SNAPSHOT) { *p++ = s->snapshot ? 1u : 0u; }
    if (present & BUTTONCLOCKSTATE_F_STATUS) { *p++ = s->status; }
    if (present & BUTTONCLOCKSTATE_F_SYNC_GENERATION) {
        polari_put_u32(p, (uint32_t)s->sync_generation);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->sync_generation >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_SYNC_UNCERTAINTY_MS) {
        polari_put_u32(p, (uint32_t)s->sync_uncertainty_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->sync_uncertainty_ms >> 32)); p += 8;
    }
    if (present & BUTTONCLOCKSTATE_F_UPTIME_MS) {
        polari_put_u32(p, (uint32_t)s->uptime_ms);
        polari_put_u32(p + 4, (uint32_t)((uint64_t)s->uptime_ms >> 32)); p += 8;
    }
    return (uint16_t)(p - start);
}

/* payload -> struct: ONLY the present fields are written (a partial command leaves the rest alone).
 * Returns 0, or -1 on truncated input. present may be NULL. */
static int ButtonClockState_decode(const uint8_t *p, uint16_t len, ButtonClockState_t *s,
                               ButtonClockState_mask_t *present)
{
    const uint8_t *end = p + len;
    uint32_t pre;
    ButtonClockState_mask_t m;
    uint16_t n, cp;
    (void)n; (void)cp;
    if (len < BUTTONCLOCKSTATE_PRELUDE_BYTES) return -1;
    pre = (uint32_t)((uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16));
    p += 3;
    m = (ButtonClockState_mask_t)(pre >> 0) & BUTTONCLOCKSTATE_F_ALL;
    if (present) *present = m;
    if (m & BUTTONCLOCKSTATE_F_BOOT_SESSION) {
        if (end - p < 8) return -1;
        s->boot_session = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_BUTTON_PRESSES) {
        if (end - p < 8) return -1;
        s->button_presses = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_CLOCK_SYNCED) {
        if (end - p < 1) return -1;
        s->clock_synced = (*p++ != 0u);
    }
    if (m & BUTTONCLOCKSTATE_F_DRIFT_MS) {
        if (end - p < 8) return -1;
        s->drift_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_DROPPED_EVENTS) {
        if (end - p < 8) return -1;
        s->dropped_events = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_EPOCH_S) {
        if (end - p < 8) return -1;
        s->epoch_s = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_LAST_EDGE_AT) {
        if (end - p < 8) return -1;
        s->last_edge_at = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_LAST_EDGE_MS) {
        if (end - p < 8) return -1;
        s->last_edge_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_LED_CHANGED_AT) {
        if (end - p < 8) return -1;
        s->led_changed_at = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_LED_ON) {
        if (end - p < 1) return -1;
        s->led_on = (*p++ != 0u);
    }
    if (m & BUTTONCLOCKSTATE_F_MS) {
        if (end - p < 8) return -1;
        s->ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_NAME) {
        if (end - p < 2) return -1;
        n = polari_get_u16(p); p += 2;
        if ((uint16_t)(end - p) < n) return -1;
        cp = n < 63u ? n : 63u;
        memcpy(s->name, p, cp); s->name[cp] = 0; p += n;
    }
    if (m & BUTTONCLOCKSTATE_F_SENSE_FALLS) {
        if (end - p < 8) return -1;
        s->sense_falls = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SENSE_RISES) {
        if (end - p < 8) return -1;
        s->sense_rises = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SEQ) {
        if (end - p < 8) return -1;
        s->seq = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SET_EPOCH_S) {
        if (end - p < 8) return -1;
        s->set_epoch_s = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SET_LED) {
        if (end - p < 1) return -1;
        s->set_led = (*p++ != 0u);
    }
    if (m & BUTTONCLOCKSTATE_F_SET_MS) {
        if (end - p < 8) return -1;
        s->set_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SET_SYNC_GENERATION) {
        if (end - p < 8) return -1;
        s->set_sync_generation = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SNAPSHOT) {
        if (end - p < 1) return -1;
        s->snapshot = (*p++ != 0u);
    }
    if (m & BUTTONCLOCKSTATE_F_STATUS) {
        if (end - p < 1) return -1;
        s->status = *p++;
    }
    if (m & BUTTONCLOCKSTATE_F_SYNC_GENERATION) {
        if (end - p < 8) return -1;
        s->sync_generation = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_SYNC_UNCERTAINTY_MS) {
        if (end - p < 8) return -1;
        s->sync_uncertainty_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    if (m & BUTTONCLOCKSTATE_F_UPTIME_MS) {
        if (end - p < 8) return -1;
        s->uptime_ms = (int64_t)((uint64_t)polari_get_u32(p) | ((uint64_t)polari_get_u32(p + 4) << 32)); p += 8;
    }
    return 0;
}

/* decode a parsed frame: -2 for any other version (a v1 frame from an old bridge, another index representation):
 * refused, never misread */
static int ButtonClockState_decode_rx(const polari_rx_t *rx, ButtonClockState_t *s,
                                  ButtonClockState_mask_t *present)
{
    if (rx->version != BUTTONCLOCKSTATE_WIRE_VERSION) return -2;
    return ButtonClockState_decode(rx->payload, rx->payload_len, s, present);
}

/* frame a payload with this class's version byte and msg_type */
static size_t ButtonClockState_frame(uint8_t *out, uint16_t device_id, uint32_t seq,
                                 const uint8_t *payload, uint16_t len)
{
    return polari_packet_encode_v(out, BUTTONCLOCKSTATE_WIRE_VERSION, BUTTONCLOCKSTATE_MSG_TYPE, device_id, seq, payload, len);
}

#endif /* BUTTONCLOCKSTATE_PACKETS_H */
