/*
 * pin_config.h — the pin claims' register/bit facts, as #defines pin_config.c uses.
 *
 * GENERATED by Polari (cmod.custom.pin_config_gen) from Firmware Solution uno-button-clock, graph uno-button-clock-graph, board arduino-uno-r3, at render time (the exact
 * timestamp lives in the glue record, cmod/custom/glue_builds/uno-button-clock-graph.json — never in this file, so a
 * re-render with nothing changed produces byte-identical output). EDIT THE MODEL (the pin claims /
 * register settings), never this file. No Polari is needed to build it: pin_config_init() is ordinary
 * avr-libc C, called once from main() before the hand-written HAL inits (POLARI_PIN_CONFIG=1 then
 * disables those same DDR/PORT/EICRA/EIFR/EIMSK writes in hal.c so the two never race).
 */

#ifndef POLARI_PIN_CONFIG_H
#define POLARI_PIN_CONFIG_H

/* one #define per claimed pin's register/bit fact pin_config.c uses — derived from the SocPin + 
 * RegisterField rows (board.custom.hardware_chain), never a bare bit number written below. */
#define PIN_CONFIG_D13_DDR               DDRB     /* the DDRB register pin claim uno-button-clock:D13 touches */
#define PIN_CONFIG_D13_BIT               5        /* DDRB.DDB5's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D2_DDR                DDRD     /* the DDRD register pin claim uno-button-clock:D2 touches */
#define PIN_CONFIG_D2_BIT                2        /* DDRD.DDD2's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D3_DDR                DDRD     /* the DDRD register pin claim uno-button-clock:D3 touches */
#define PIN_CONFIG_D3_BIT                3        /* DDRD.DDD3's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D6_DDR                DDRD     /* the DDRD register pin claim uno-button-clock:D6 touches */
#define PIN_CONFIG_D6_BIT                6        /* DDRD.DDD6's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D2_PORT               PORTD    /* the PORTD register pin claim uno-button-clock:D2 touches */
#define PIN_CONFIG_D2_EICRA              EICRA    /* the EICRA register pin claim uno-button-clock:D2 touches */
#define PIN_CONFIG_D2_EICRA_BIT          0        /* EICRA.ISC0's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D2_EICRA_WIDTH        2        /* EICRA.ISC0's bit width */
#define PIN_CONFIG_D3_EICRA              EICRA    /* the EICRA register pin claim uno-button-clock:D3 touches */
#define PIN_CONFIG_D3_EICRA_BIT          2        /* EICRA.ISC1's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D3_EICRA_WIDTH        2        /* EICRA.ISC1's bit width */
#define PIN_CONFIG_D2_EIFR               EIFR     /* the EIFR register pin claim uno-button-clock:D2 touches */
#define PIN_CONFIG_D2_EIFR_BIT           0        /* EIFR.INTF0's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D3_EIFR               EIFR     /* the EIFR register pin claim uno-button-clock:D3 touches */
#define PIN_CONFIG_D3_EIFR_BIT           1        /* EIFR.INTF1's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D2_EIMSK              EIMSK    /* the EIMSK register pin claim uno-button-clock:D2 touches */
#define PIN_CONFIG_D2_EIMSK_BIT          0        /* EIMSK.INT0's low bit (from the SocPin/RegisterField rows, never a bare number) */
#define PIN_CONFIG_D3_EIMSK              EIMSK    /* the EIMSK register pin claim uno-button-clock:D3 touches */
#define PIN_CONFIG_D3_EIMSK_BIT          1        /* EIMSK.INT1's low bit (from the SocPin/RegisterField rows, never a bare number) */

void pin_config_init(void);

#endif /* POLARI_PIN_CONFIG_H */

