/*
 * pin_config.c — pin_config_init(): the fixed init order (DDR, PORT, EICRA, EIFR, EIMSK, PCMSKx, PCICR); sei() stays in main(), after every init, never here.
 *
 * GENERATED by Polari (cmod.custom.pin_config_gen) from Firmware Solution uno-button-clock, graph uno-button-clock-graph, board arduino-uno-r3, at render time (the exact
 * timestamp lives in the glue record, cmod/custom/glue_builds/uno-button-clock-graph.json — never in this file, so a
 * re-render with nothing changed produces byte-identical output). EDIT THE MODEL (the pin claims /
 * register settings), never this file. No Polari is needed to build it: pin_config_init() is ordinary
 * avr-libc C, called once from main() before the hand-written HAL inits (POLARI_PIN_CONFIG=1 then
 * disables those same DDR/PORT/EICRA/EIFR/EIMSK writes in hal.c so the two never race).
 */

#include <avr/io.h>
#include <stdint.h>

#include "pin_config.h"

void pin_config_init(void)
{
    /* uno-button-clock:DDRB:init = 00100000 (write_mask 0x20)
     *   DDB5     = 1     — the pin is configured as an output pin · claim uno-button-clock:D13 · task l_led_init · rule ddr-from-digital-out
     */
    PIN_CONFIG_D13_DDR = (uint8_t)((PIN_CONFIG_D13_DDR & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D13_BIT))) | (((uint8_t)0x01 << PIN_CONFIG_D13_BIT)));   /* bits outside write_mask 0x20 keep the chip's
                                    reset value */

    /* uno-button-clock:DDRD:init = 01000000 (write_mask 0x4C)
     *   DDD2     = 0     — the pin is configured as an input pin · claim uno-button-clock:D2 · task button_init · rule ddr-from-interrupt-in
     *   DDD3     = 0     — the pin is configured as an input pin · claim uno-button-clock:D3 · task sense_init · rule ddr-from-interrupt-in
     *   DDD6     = 1     — the pin is configured as an output pin · claim uno-button-clock:D6 · task led_init · rule ddr-from-digital-out
     */
    PIN_CONFIG_D2_DDR = (uint8_t)((PIN_CONFIG_D2_DDR & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D2_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D3_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D6_BIT))) | (((uint8_t)0x00 << PIN_CONFIG_D2_BIT) | ((uint8_t)0x00 << PIN_CONFIG_D3_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D6_BIT)));   /* bits outside write_mask 0x4C keep the chip's
                                    reset value */

    /* uno-button-clock:PORTD:init = 00000100 (write_mask 0x04)
     *   PORTD2   = 1     — input: the pull-up resistor is activated · output: the pin is driven high · claim uno-button-clock:D2 · task button_init · rule port-pull-up
     */
    PIN_CONFIG_D2_PORT = (uint8_t)((PIN_CONFIG_D2_PORT & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D2_BIT))) | (((uint8_t)0x01 << PIN_CONFIG_D2_BIT)));   /* bits outside write_mask 0x04 keep the chip's
                                    reset value */

    /* uno-button-clock:EICRA:init = 00000110 (write_mask 0x0F)
     *   ISC0     = 10    — The falling edge of INT0 generates an interrupt request. · claim uno-button-clock:D2 · task button_init · rule edge-falling-to-ISC0
     *   ISC1     = 01    — Any logical change on INT1 generates an interrupt request. · claim uno-button-clock:D3 · task sense_init · rule edge-any-to-ISC1
     */
    PIN_CONFIG_D2_EICRA = (uint8_t)((PIN_CONFIG_D2_EICRA & (uint8_t)~(((uint8_t)0x03 << PIN_CONFIG_D2_EICRA_BIT) | ((uint8_t)0x03 << PIN_CONFIG_D3_EICRA_BIT))) | (((uint8_t)0x02 << PIN_CONFIG_D2_EICRA_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D3_EICRA_BIT)));   /* bits outside write_mask 0x0F keep the chip's
                                    reset value */

    /* uno-button-clock:EIFR:init = 00000011 (write_mask 0x03)
     *   INTF0    = 1     — an interrupt request is pending; cleared by hardware when the interrupt routine is executed, or by writing a logical one to it · claim uno-button-clock:D2 · task button_init · rule clear-pending-before-enable
     *   INTF1    = 1     — an interrupt request is pending; cleared by hardware when the interrupt routine is executed, or by writing a logical one to it · claim uno-button-clock:D3 · task sense_init · rule clear-pending-before-enable
     */
    PIN_CONFIG_D2_EIFR = (uint8_t)(((uint8_t)0x01 << PIN_CONFIG_D2_EIFR_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D3_EIFR_BIT));   /* plain write (access w1c): writing a one CLEARS that pending flag; a
                                    read-modify-write would also clear every OTHER pending flag */

    /* uno-button-clock:EIMSK:init = 00000011 (write_mask 0x03)
     *   INT0     = 1     — enabled (when the I-bit in SREG is also set) · claim uno-button-clock:D2 · task button_init · rule enable-external-interrupt
     *   INT1     = 1     — enabled (when the I-bit in SREG is also set) · claim uno-button-clock:D3 · task sense_init · rule enable-external-interrupt
     */
    PIN_CONFIG_D2_EIMSK = (uint8_t)((PIN_CONFIG_D2_EIMSK & (uint8_t)~(((uint8_t)0x01 << PIN_CONFIG_D2_EIMSK_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D3_EIMSK_BIT))) | (((uint8_t)0x01 << PIN_CONFIG_D2_EIMSK_BIT) | ((uint8_t)0x01 << PIN_CONFIG_D3_EIMSK_BIT)));   /* bits outside write_mask 0x03 keep the chip's
                                    reset value */
}

