/*
 * polari_graph.h: the graph's identity, the frame masks, where every file came from — GENERATED by cmod.custom.glue 1 from the no-code graph uno-button-clock-graph (sha256 35e45e943500ffbc1cbae25259ddce881ebd6b2c272e65b61ec35e62928d7795).
 * Regenerate with `pol cmod render uno-button-clock-graph`. Editing by hand is allowed: `pol cmod diff uno-button-clock-graph` shows it, and a render
 * never overwrites a hand edit silently. Plain C on avr-libc (RULE 2); no Python at run time.
 */
#ifndef POLARI_GRAPH_H
#define POLARI_GRAPH_H

#include "buttonclockstate_packets.h"

#define POLARI_GRAPH_NAME   "uno-button-clock-graph"
#define POLARI_GRAPH_SHA256 "35e45e943500ffbc1cbae25259ddce881ebd6b2c272e65b61ec35e62928d7795"


/* the files of this project (sha256 of the bytes written):
 *   button_clock_defs.h      346438094259cb56  copied verbatim from board/custom/firmware/uno/apps/button_clock_defs.h
 *   hal.c                    978c2492405808c9  copied verbatim from board/custom/firmware/uno/hal.c
 *   hal.h                    58cfacfb3cad8403  copied verbatim from board/custom/firmware/uno/hal.h
 *   board_config.h           d5b563cfde8d862b  board gen: the uno-button-clock knobs
 *   buttonclockstate_packets.h 1c9d335a5ae6d1a0  c_twin target=avr, contract v1 9d32ede2fa51ab74 (pinned board/custom/contracts/ButtonClockState.v1.json)
 *   buttonclockevent_packets.h d7c29234aef022c6  c_twin target=avr: a second wire class buttonclockevent_packets.h's own atoms assemble (never a glue class/frame node)
 *   pin_config.h             292371ecfb983951  GENERATED (cmod.custom.pin_config_gen) from uno-button-clock's pin claims
 *   pin_config.c             ----------------  GENERATED (cmod.custom.pin_config_gen) from uno-button-clock's pin claims
 *   polari_graph.c           ----------------  GENERATED (+ apps/button_clock.l_led_init, apps/button_clock.l_led_set, apps/button_clock.boot_session_mint, apps/button_clock.clock_tick, apps/button_clock.clock_set, apps/button_clock.events_queue, apps/button_clock.queue_pop, apps/button_clock.led_toggle, apps/button_clock.sense_isr, apps/button_clock.events_drain, apps/button_clock.telemetry_send, apps/button_clock.apply_command copied verbatim)
 */

#endif /* POLARI_GRAPH_H */
